### ISSUE TITLE
GGI unintended interruption

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#1]
@gsautter this file does not open in GGI 
Zoology in the Middle East

[zoolMidEast.62.3.261.pdf](https://github.com/gsautter/goldengate-imagine/files/614745/zoolMidEast.62.3.261.pdf)

err.log

Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.

out.log

GoldenGATE (2013.02.19.19.30) started, configuration is Default.imagine
Determined default character set: windows-1252
GamtaClassLoader: loading components from data list:
  component class: de.uka.ipd.idaho.goldenGate.plugins.GoldenGatePlugin
  path prefix: Plugins/
  data list names are:
  investigating jars:
  - Plugins/Analyzer.jar
    - de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager
  - Plugins/AnnotationActionProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.AnnotationActionProvider
  - Plugins/Annotator.jar
    - de.uka.ipd.idaho.goldenGate.plugin.annotators.AnnotatorManager
  - Plugins/AnnotionPattern.jar
    - de.uka.ipd.idaho.goldenGate.plugin.annotationPatterns.AnnotationPatternManager
  - Plugins/AttributeSuggestions.jar
    - de.uka.ipd.idaho.goldenGate.plugin.attributes.AttributeSuggestionManager
  - Plugins/AttributeToolProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.AttributeToolProvider
  - Plugins/AuthManagerPlugin.jar
    - de.uka.ipd.idaho.goldenGateServer.uaa.UserAccessAuthorityConstants
    - de.uka.ipd.idaho.goldenGateServer.uaa.client.AuthenticatedClient
    - de.uka.ipd.idaho.goldenGateServer.uaa.client.AuthenticationManager
    - de.uka.ipd.idaho.goldenGateServer.uaa.client.AuthenticationManagerPlugin
  - Plugins/BasicImageEditToolProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.BasicImageEditToolProvider
  - Plugins/BlockOcrProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.ocr.BlockOcrProvider
  - Plugins/CaptionCitationHandler.jar
    - de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler
  - Plugins/DocumentDashboards.jar
    - de.uka.ipd.idaho.goldenGateServer.dcs.GoldenGateDcsStatEngine
    - de.uka.ipd.idaho.goldenGateServer.srs.GoldenGateSrsConstants
    - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.DocumentDashboardGenerator
    - de.uka.ipd.idaho.goldenGateServer.GoldenGateServerConstants
    - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.renderers.GoogleCharts
    - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.DcStatChartRenderer
    - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.DcStatChartData
    - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.DcStatChartEngine
    - de.uka.ipd.idaho.goldenGateServer.dcs.GoldenGateDcsConstants
    - de.uka.ipd.idaho.goldenGateServer.dst.GoldenGateServerDocConstants
  - Plugins/DocumentMetaDataEditor.jar
    - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentMetaDataEditorProvider
  - Plugins/DocumentProcessorImTools.jar
    - de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager
  - Plugins/DocumentStructureDetector.jar
    - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider
  - Plugins/DocumentStyleManager.jar
    - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStyleManager
  - Plugins/DocumentStyleProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStyleProvider
  - Plugins/DwCADocumentExporter.jar
    - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.DwCADocumentExporter
  - Plugins/FigureTableDocumentExporter.jar
    - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.FigureTableDocumentExporter
  - Plugins/FilteredDP.jar
    - de.uka.ipd.idaho.goldenGate.plugin.filteredProcessor.FilteredDocumentProcessorManager
  - Plugins/FontEditorProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.fonts.FontEditorProvider
  - Plugins/GPath.jar
    - de.uka.ipd.idaho.goldenGate.plugin.gPaths.GPathManager
  - Plugins/GScript.jar
    - de.uka.ipd.idaho.goldenGate.plugin.gScript.AnnotateFunction
    - de.uka.ipd.idaho.goldenGate.plugin.gScript.EditDocumentFunction
    - de.uka.ipd.idaho.goldenGate.plugin.gScript.GScriptManager
    - de.uka.ipd.idaho.goldenGate.plugin.gScript.ListAnnotationSourcesFunction
    - de.uka.ipd.idaho.goldenGate.plugin.gScript.ListDocumentProcessorsFunction
    - de.uka.ipd.idaho.goldenGate.plugin.gScript.ListFunctionsFunction
    - de.uka.ipd.idaho.goldenGate.plugin.gScript.RunFunction
  - Plugins/GgServerDocumentExporter.jar
    - de.uka.ipd.idaho.goldenGateServer.dio.client.GoldenGateDioClient
    - de.uka.ipd.idaho.goldenGateServer.dio.GoldenGateDioConstants
    - de.uka.ipd.idaho.goldenGateServer.dst.GoldenGateServerDocConstants
    - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.GgServerDocumentExporter
  - Plugins/ImsDocumentIO.jar
    - de.uka.ipd.idaho.goldenGateServer.ims.data.ImsDocumentList
    - de.uka.ipd.idaho.goldenGateServer.ims.data.ImsDocumentListElement
    - de.uka.ipd.idaho.goldenGateServer.ims.data.ImsDocumentListBuffer
    - de.uka.ipd.idaho.goldenGateServer.ims.client.GoldenGateImsDocumentIO
    - de.uka.ipd.idaho.goldenGateServer.ims.client.GoldenGateImsClient
    - de.uka.ipd.idaho.goldenGateServer.ims.GoldenGateImsConstants
  - Plugins/KeyHandler.jar
    - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider
  - Plugins/List.jar
    - de.uka.ipd.idaho.goldenGate.plugin.lists.ListManager
  - Plugins/MarkupConverter.jar
    - de.uka.ipd.idaho.goldenGate.plugin.markupConverters.MarkupConverterManager
  - Plugins/MultiList.jar
    - de.uka.ipd.idaho.goldenGate.plugin.multiLists.MultiListManager
  - Plugins/NavigationProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.NavigationActionProvider
  - Plugins/ObjectListProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupObjectListProvider
  - Plugins/Pipeline.jar
    - de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager
  - Plugins/RegEx.jar
    - de.uka.ipd.idaho.goldenGate.plugin.regExes.RegExManager
  - Plugins/RegionActionProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.RegionActionProvider
  - Plugins/TableActionProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.tables.TableActionProvider
  - Plugins/TextActionProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.TextActionProvider
  - Plugins/TextBlockActionProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.TextBlockActionProvider
  - Plugins/TextStreamActionProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.TextStreamActionProvider
  - Plugins/UrlDropLinker.jar
    - de.uka.ipd.idaho.im.imagine.plugins.link.UrlDropHandler
  - Plugins/WordActionProvider.jar
    - de.uka.ipd.idaho.im.imagine.plugins.basic.WordActionProvider
  - Plugins/XmlViewer.jar
    - de.uka.ipd.idaho.im.imagine.plugins.xml.XmlViewerProvider
  adding shared jars:
    - Plugins/Bin/AbbreviationUtils.jar
    - Plugins/Bin/BibRefUtils.jar
    - Plugins/Bin/DateTimeUtils.jar
    - Plugins/Bin/GamtaFeedbackAPI.jar
    - Plugins/Bin/GamtaImagingAPI.jar
    - Plugins/Bin/GeoUtils.jar
    - Plugins/Bin/GgServerClient.jar
    - Plugins/Bin/MaterialsCitationUtils.jar
    - Plugins/Bin/QuantityUtils.jar
    - Plugins/Bin/TableUtils.jar
    - Plugins/Bin/TaxonomicNameUtils.jar
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.AnnotationActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.annotators.AnnotatorManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.annotationPatterns.AnnotationPatternManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.attributes.AttributeSuggestionManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.AttributeToolProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.uaa.UserAccessAuthorityConstants
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.uaa.client.AuthenticatedClient
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.uaa.client.AuthenticationManager
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.uaa.client.AuthenticationManagerPlugin
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.BasicImageEditToolProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.ocr.BlockOcrProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dcs.GoldenGateDcsStatEngine
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.srs.GoldenGateSrsConstants
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.DocumentDashboardGenerator
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.GoldenGateServerConstants
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.renderers.GoogleCharts
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.DcStatChartRenderer
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.DcStatChartData
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dcs.client.charts.DcStatChartEngine
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dcs.GoldenGateDcsConstants
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dst.GoldenGateServerDocConstants
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentMetaDataEditorProvider
  got component class
XsltUtils: testing XSL Transformer Factory for internal caching behavior ...
 - got XSL Transformer Factory instance
 - got XSL Transformer instance 1
 - got XSL Transformer instance 2
 - found factory to not be caching internally, can use centralized instance
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStyleManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStyleProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.DwCADocumentExporter
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.FigureTableDocumentExporter
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.filteredProcessor.FilteredDocumentProcessorManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.fonts.FontEditorProvider
  got component class
StringUtils: initializing PostScript character mappings ...
StringUtils: PostScript character mappings initialized.
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gPaths.GPathManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gScript.AnnotateFunction
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gScript.EditDocumentFunction
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gScript.GScriptManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gScript.ListAnnotationSourcesFunction
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gScript.ListDocumentProcessorsFunction
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gScript.ListFunctionsFunction
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.gScript.RunFunction
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dio.client.GoldenGateDioClient
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.dio.GoldenGateDioConstants
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.GgServerDocumentExporter
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.ims.data.ImsDocumentList
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.ims.data.ImsDocumentListElement
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.ims.data.ImsDocumentListBuffer
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.ims.client.GoldenGateImsDocumentIO
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.ims.client.GoldenGateImsClient
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.ims.GoldenGateImsConstants
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.lists.ListManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.markupConverters.MarkupConverterManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.multiLists.MultiListManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.NavigationActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupObjectListProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.goldenGate.plugin.regExes.RegExManager
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.RegionActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.tables.TableActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.TextActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.TextBlockActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.TextStreamActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.link.UrlDropHandler
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.basic.WordActionProvider
  got component class
  component class successfully instantiated.
GamtaClassLoader: investigating class - de.uka.ipd.idaho.im.imagine.plugins.xml.XmlViewerProvider
  got component class
  component class successfully instantiated.
Adding shared jar: Bin/BibRefUtils.DataSources.jar
Adding shared jar: Bin/BibRefUtils.jar
GamtaClassLoader: loading components from data list:
  component class: de.uka.ipd.idaho.gamta.util.gPath.GPathFunction
  path prefix: Functions/
  data list names are:
  investigating jars:
  adding shared jars:
GamtaClassLoader: loading components from data list:
  component class: de.uka.ipd.idaho.gamta.util.gScript.GScriptFunction
  path prefix: Functions/
  data list names are:
  investigating jars:
  adding shared jars:
PDF Image Decoder: installing file 'convert-windows.exe'
 ==> already installed
PDF Image Decoder: installing file 'ISOcoated_v2_300_eci.icc'
 ==> source not found
GoldenGATE Imagine core created, configuration is Default.imagine
 - window opened

**Comment by myrmoteras** [comment]
@gsautter 
Candollea
this file makes the new GGI version stall.
![image](https://cloud.githubusercontent.com/assets/4609956/20649187/365f99de-b4b9-11e6-8a9c-7aff57137d70.png)

[candollea.c2016v711a16.pdf](https://github.com/gsautter/goldengate-imagine/files/614752/candollea.c2016v711a16.pdf)

log.out
[x=112.029236,y=12.665924,w=9.228043,h=5.421875]
     - char codes are ĹıĶ (139 131 136)
   --> split word part ., bounds are java.awt.geom.Rectangle2D$Float[x=121.25728,y=12.665924,w=0.719126,h=5.421875]
     - char codes are Į (12e)
   --> split word part indd, bounds are java.awt.geom.Rectangle2D$Float[x=121.9764,y=12.665924,w=11.169481,h=5.421875]
     - char codes are ũŮŤŤ (169 16e 164 164)
 - splitting 17.05.16
   - char codes are ıķĮİĵĮıĶ (131 137 12e 130 135 12e 131 136)
Getting font 0 serif 6
==> cache hit
   --> split word part 17.05, bounds are java.awt.geom.Rectangle2D$Float[x=576.78,y=12.665924,w=13.645708,h=5.421875]
     - char codes are ıķĮİĵ (131 137 12e 130 135)
   --> split word part ., bounds are java.awt.geom.Rectangle2D$Float[x=590.4257,y=12.665924,w=0.7365588,h=5.421875]
     - char codes are Į (12e)
   --> split word part 16, bounds are java.awt.geom.Rectangle2D$Float[x=591.1623,y=12.665924,w=5.633724,h=5.421875]
     - char codes are ıĶ (131 136)
 - splitting 14:36
   - char codes are ıĴĺĳĶ (131 134 13a 133 136)
Getting font 0 serif 6
==> cache hit
   --> split word part 14, bounds are java.awt.geom.Rectangle2D$Float[x=600.882,y=12.665924,w=5.841913,h=5.40625]
     - char codes are ıĴ (131 134)
   --> split word part :, bounds are java.awt.geom.Rectangle2D$Float[x=606.72394,y=12.665924,w=0.76146245,h=5.40625]
     - char codes are ĺ (13a)
   --> split word part 36, bounds are java.awt.geom.Rectangle2D$Float[x=607.4854,y=12.665924,w=6.2846246,h=5.40625]
     - char codes are ĳĶ (133 136)
 --> got 1393 words in PDF
Generating page images
Extracting image of page 1 of 7
Extracting image of page 5 of 7
Extracting image of page 2 of 7
Extracting image of page 0 of 7
Extracting image of page 4 of 7
Extracting image of page 6 of 7
Extracting image of page 3 of 7
 - generating page image
 - generating page image
 - generating page image
 - generating page image
 - generating page image
 - generating page image
 - generating page image
 - got page image sized 1593 x 2122
 - got page image sized 1593 x 2122

I need to change .log to .txt
[GgImagine.20161127-1536.out.txt](https://github.com/gsautter/goldengate-imagine/files/614758/GgImagine.20161127-1536.out.txt)

**Comment by gsautter** [comment]
`zoolMidEast.62.3.261.pdf` solved, was problem with color initialization, and with multi-part image.

**Comment by gsautter** [comment]
`candollea.c2016v711a16.pdf` opens just fine as well.

**Comment by myrmoteras** [comment]
let me know when you uipload the new built so I can mark it up

**Comment by myrmoteras** [comment]
There is a problem with the figure and captions that do not load to BLR
http://tb.plazi.org/GgServer/html/03D52C00FFFBAC2C6141F9D264B5153A?cacheControl=force

there is a also an error I can’t solve
[cid:image001.png@01D24F54.4F0EC1A0]

**Comment by gsautter** [comment]
That appears to be the labeling from the two images right above the paragraph starting with "Conservation status". Surely needs a filter, I'll add it.

**Comment by myrmoteras** [comment]
@gsautter I can't figure out how to fix this Candollea. I don't understand, why the figure 2 and 3 do not show up, and what is wrong in the markup.
Can you please fix it or tell me how to do?
http://tb.plazi.org/GgServer/summary/FFEC5478FFFAAC296265FF8F65311000

**Comment by gsautter** [comment]
There is _nothing_ wrong with the markup, just with a filter I have to add.

That "ghost" text is simply the "words" (actually labels in Figures 2 and 3) that end up folded into the main text, an it's me who has to filter this out.

We refrained from simply removing in-figure words when we started getting the graphics out, as those words can well be an essential part of them ... just think of a phylogenetic tree with all the words (taxon names !!!) removed.

**Comment by gsautter** [comment]
Regarding the figures on Zenodo: Figure 3 is up there now. What's wrong with Figure 2 is under investigation.

**Comment by gsautter** [comment]
Figure 2 fixed as well.

In general, if a figure doesn't show, odds are it is not properly connected to its caption. To do that:
- Make sure `image` regions and `caption` annotations are showing
- Click on the figure and choose "Assign Caption"
- Click on the caption (any of its words will do)

That connects the figure image and the caption, and then it all works smooth with Zenodo.
