### ISSUE TITLE
repair: figure replacement does not work

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#100]
@gsautter in this doc FFCBE12DFFDFFF9693156853FFB2D01D i replaced as you have described all the images 

with new images that are not scrambled in the cache file
i then removed all the httpUri in the caption.
I saved the file in SRS
I closed the file
new entries in BLR are made, BUT with the old images

When I reopened the file from SRS, the old images have been there.

What needs be changed on my side?

thanks for your input

**Comment by gsautter** [comment]
This is exactly what I was afraid of all long explaining to you how to perform surgery on an IMF ...

I'll take care of it.

**Comment by myrmoteras** [comment]
So, let's write it down that it works. What did I make wrong? I need to know.

**Comment by gsautter** [comment]
Well ... I don't know what exactly your did at all in the first place ... but I'll briefly detail out what I just did.

**Comment by gsautter** [comment]
First of all, the figures are good now, see http://tb.plazi.org/GgServer/html/03F29955FFDDFF9B93826E5AFE24D6E0

**Comment by myrmoteras** [comment]
Ît is written in the  first part of this issue what I did.

**Comment by gsautter** [comment]
Well, what I did is this:
- Open broken-figure document from server in GGI
- Save that document to local disk as IMF (simply dubbed BROKEN.imf from now on)
- TaskManager GGI so you retain the lock on the document
- Rename BROKEN.imf to BROKEN.zip
- Extract BROKEN.zip to BROKEN (into a distinct folder)
- Start GGI and re-decode BROKEN/source.pdf
- Save resulting document as GOOD.imf to same folder as BROKEN.imf
- Close GGI normally
- Rename GOOD.imf to GOOD.zip
- Extract GOOD.zip to GOOD (into a distinct folder)
- Copy following files from folder BROKEN to folder GOOD:
  - annotations.csv
  - document.csv
  - pages.csv
  - regions.csv
  - words.csv
- Go _into_ folder GOOD, select all files, and zip them up into GOOD.zip, making sure to _not_ include any folder paths
- Rename just created GOOD.zip to GOOD.imf
- Start GGI again, open just created GOOD.imf
- Use "Copy Image" and pasting to Paint on a few images to make sure good figures are in reference
- Remove `httpUri` attribute from captions of any previously broken figures
- Use "Save Document to GoldenGATE Server" to upload GOOD.imf
- If any error occurs, just try again once
- Close document in GGI, and GGI proper

In the case at hand, BROKEN and GOOD are `zt03920p084.pdf.broken` and `zt03920p084.pdf.good`, respectively, so to preserve the document name, and also to avoid any confusion between documents.

Hope that manual is sufficient ...

**Comment by gsautter** [comment]
PS: Those figures were broken in _exactly_ the way Figure Repair is supposed to pick up upon ... not sure why it didn't in this very case, but odds are it was due to some error not related to figures.

So please, if you see an figures mingled like in this document, just open _one_ ticket and keep listing the document UUIDs (_not_ the treatment UUIDs). I'll check at least once a day and schedule repair. Ultimately, Figure Repair does _exactly_ what I described above, only without the file renaming, un-zipping, entry copying, and re-zipping, and of course without the TaskManager, and without any effort at your hands beyond reporting the document UUID.
