### ISSUE TITLE
Caption and image mark up overlap

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#101]
![image](https://cloud.githubusercontent.com/assets/4609956/23438621/f43ead4e-fe12-11e6-9b31-94d88fae9277.png)
in this EJT article the figure  and caption overlap. document structure detection solved it this way. When I delte the image, mark the caption and the draw the figure on top of it, I get this (image and caption both are activated.)

![image](https://cloud.githubusercontent.com/assets/4609956/23438731/713c2db2-fe13-11e6-82d9-988a0d5ee1aa.png)

what is the solution?

[412-2071-1-PB.pdf](https://github.com/gsautter/goldengate-imagine/files/809232/412-2071-1-PB.pdf)

**Comment by gsautter** [comment]
Drag a box around the captions and use "Mark Caption" ... that should do the trick.

To be safe, you might want to (a) check that captions have the attributes associating them with their respective figures (`targerPageId` and `targetBox`), and if they don't (b) make sure to show `image` and `graphics` regions as well as `caption` annotations and (c) click on each figure, choose "Assign Caption", and right afterwards click on any word in the respective caption proper.
