### ISSUE TITLE
figure citation: display of caption in hyperlink

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#102]
3D5DFFB52E38F810AC25FF81FFEDFFE7
http://treatment.plazi.org/id/C16487CD-2E3A-F815-AC4C-FB5FFE6EFC4A 

in this doc, the caption are shown in the hyperlink.

![image](https://cloud.githubusercontent.com/assets/4609956/23454835/de171596-fe6d-11e6-9769-272d4115a86f.png)

When I uploaded the IMF to SRS it would not show figure 1 because it was not linked to the caption and did not upload to BLR
I fixed the link.

I also added targetBox what I considered the missing captionTargetBox-0 into the figureCitation but otherwise I did not make any changes

**Comment by gsautter** [comment]
The `captionStart` or `captionStart-X` attribute is supposed to contain te caption _start_, i.e., "Figure 1" or something like that. For the full caption(s), there is `captionText` or `captionText-X`.

The caption text does end up the title of the link, which displays on hovering, but not the link text displaying all the time - that's one of the things `captionStart` is good for.

**Comment by gsautter** [comment]
I fixed the attributes now, so it's all good.
