### ISSUE TITLE
strange figures that wont mark

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#104]
@gsautter is there a way to fix these images, or we need to wait to get a proper PDF?
the pages with figures have a "proof" in the background

[ThailandNaturalHistoryMuseumJournal.10.2.67.pdf](https://github.com/gsautter/goldengate-imagine/files/815352/ThailandNaturalHistoryMuseumJournal.10.2.67.pdf)

**Comment by gsautter** [comment]
Got it ... those "PROOF" watermarks render with zero alpha, i.e., completely transparent ... the decoder wasn't aware of such invisible content thus far. I added a filter to get rid of transparent and mostly transparent content.
