### ISSUE TITLE
PDF does not open

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#105]
another PDF that does not open in GGI

[procEntomolSocWash.119.1.78.pdf](https://github.com/gsautter/goldengate-imagine/files/815357/procEntomolSocWash.119.1.78.pdf)
[GgImagine.20170303-0020.out.zip](https://github.com/gsautter/goldengate-imagine/files/815358/GgImagine.20170303-0020.out.zip)

**Comment by gsautter** [comment]
This one has irregular content in page 2, which incurred a stack underflow during rendering. I added a respective catch, and now it opens just fine.
