### ISSUE TITLE
PDF does not open: ABBYY product

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#106]
this might be the same as #86 , but still does not work. There is also no mentioned upload.

https://doi.org/10.5281/zenodo.345340 This is originally a scan and OCRed in Abbyy 14

[GgImagine.20170303-1337.out.zip](https://github.com/gsautter/goldengate-imagine/files/816768/GgImagine.20170303-1337.out.zip)

**Comment by gsautter** [comment]
Could be the auto-updater has trouble finding the updates due to the turbulence around URL `plazi.cs.umb.edu` ...

Put the following in your `UpdateHosts.cnfg`: `http://tb.plazi.org/GgServer/Updates` and the updates should work again.

**Comment by myrmoteras** [comment]
Adding the above does not result in an update

**Comment by gsautter** [comment]
I just put out a new build to http://tb.plazi.org/GgServer/Downloads/GgImagine-Default.imagine.zip ... hopefully at least downloading that works ... not sure what's wrong with the online update, but extremely sure I didn't change anything in that department, so technically it _should_ work just as used to.
