### ISSUE TITLE
New build of GGI

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#108]
Hi @gsautter 
might it be possible that your could assure that there is a most updated build of GGI available that solves the issues we had, eg opening the EJT documents, by Wednesday. Jeremy and I will be in Paris on Friday fo EJT discussions and thus we need to have this working.

So far, I could not update GGI using the automatic upload functions. Also not with the new link you provided. The few batches you send me allowed me now to convert an EJT http://tb.plazi.org/GgServer/summary/B167FFE1FF901171FFDE1970704D076A this morning

tx

**Comment by gsautter** [comment]
I just put out a new build to http://tb.plazi.org/GgServer/Downloads/GgImagine-Default.imagine.zip ... hopefully at least downloading that works ... not sure what's wrong with the online update, but extremely sure I didn't change anything in that department, so technically it _should_ work just as used to.
