### ISSUE TITLE
font issue: Odonatologica

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#11]
this Odonoatologica article has fonts that can not be edited, and it is not possible to create a stream in the first bibRef.
[10.5281zenodo.163452_Seehausen_Guenther.pdf](https://github.com/gsautter/goldengate-imagine/files/633389/10.5281zenodo.163452_Seehausen_Guenther.pdf)

![image](https://cloud.githubusercontent.com/assets/4609956/20919772/bf71c7d4-bb9d-11e6-9416-763f62dbef67.png)

**Comment by gsautter** [comment]
Not sure about the text stream, that part works perfectly fine in my test ...

Will check out the font.

**Comment by gsautter** [comment]
The fonts are, least to say, wild ... lots of cross-referencing and wrapping, might take a little to sort out.

**Comment by gsautter** [comment]
Resolved, was a subtle detail about descendant fonts ... in such fonts, you derive a font you use from a large, universal base font that contains many more characters than you need in the document at hand. Problem was that such base fonts are _not_ subject to a few restrictions that apply to top level fonts, and the font decoder was wrongfully enforcing those restrictions.

Meaning to say: You now _do_ get glyphs to correct.

Apart from that, Odonatologica appears to use the same nasty triple-case fonts (chars in upper and lower case as well as small-caps) as Candollea ...
