### ISSUE TITLE
feature request: extended values in "issue"

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#111]
electronic publication have issues that beginnn with "e", such as e:3007

![image](https://cloud.githubusercontent.com/assets/4609956/23693356/5a1d5a7c-03d4-11e7-9e61-b36650ed6b57.png)

This is the case in Peerj, Rio, etc.

I would like to recommend that it is possible to make sure that such issue numbers can be stored.

example: FFB3FF9EB22DAC4A3022181FFFF8FFF0

**Comment by gsautter** [comment]
To what avail? Apart from making that _number_ _way_ harder to process?

I've seen the "e" added to the pagination as well, so there doesn't really seem to be a well-defined agreed-upon way of indicating "e-pub" anyway, as people do it in different ways.

And what difference does it make anyway? Apart from indicating "e-pub", which shouldn't matter at all ... people use the PDF anyway, regardless of whether or not some library somewhere on the planet has a paper copy. If anything, it screams "not the real deal", which I think is a prejudice we used to strive to overcome ...

If you want to put this scarlet letter on an article by any means, why not simply append "(e-pub)" to the journal name, which is a string anyway?

**Comment by myrmoteras** [comment]
The difference is, that there is a development in publishing. Often there is no issue or page number anymore, or in epublications an e prefixing the issue.

I guess we have to go with the time

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by gsautter** [comment]
Then I guess we can get ahead of time here (as we so proudly do in other areas) and just forget about this "e" ... as long as there is a DOI, that "e" doesn't help resolving the reference the slightest bit. And if I get you correctly, it is a temporary phenomenon anyway, as e-publications are growing up to become as legit as their ink-and-paper predecessors and counterparts.

No use in promoting the scarlet letter once put upon e-publications by authors not being able to get around referencing them, the less so as it's fading anyway.
