### ISSUE TITLE
GGI crashed

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#112]
[GgImagine.20170307-1837.out.zip](https://github.com/gsautter/goldengate-imagine/files/827610/GgImagine.20170307-1837.out.zip)

**Comment by gsautter** [comment]
Hard to tell from the logs alone ... all I can derive is that the page images of likely several pages failed to load on opening a document.

Do you have a PDF for me to test this with? If page image generation failed during decoding, there would not be the error traces I see, simply as GGI doesn't try and open an IMF that failed to generate from its source PDF in the first place, so there must be other reasons.

If this was a problem loading a document from the server, the UUID would be just as helpful.

**Comment by myrmoteras** [comment]
I think, there were three imf files open at the same time. If this helps I might find out

**Comment by gsautter** [comment]
Now three open files surely shed some light on why the log was so confusing ... can you reproduce the error with any _one_ of those three files open?

After all, failure to properly store a page image might be a result of hitting the memory ropes while adjusting the page images after changes to font transcription ...
