### ISSUE TITLE
finding articles that are only partially marked up on TB?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#114]
Here are two articles that have no treatmentMarkup, but are uploaded to TB.

The question is, how do I find them? What is there masterDocId so I can refer to them in the issues?

basteria.80.1-3.5.2016 Bank et al Lauriidae Enidae Vitrinidae Turkey
vitaMalacologica.14.1_2016 Bank  Neubert Enidae Iran.pdf

**Comment by gsautter** [comment]
There surely _is_ a document UUID, if none visible in the UI before the document shows up in the search portal ...

The document _name_, for which there is a filter in GGI's "Load Document from GoldenGATE Server" dialog, should do the trick. If you decode a PDF into an IMF, the name of the latter by default is the name of the former plus ".imf", and the respective filter field does prefix matching.
The document name is also accessible in GGI via "Edit -> Edit Document Attributes", in the `docName` attribute, once you have it open.

On top of that, you can use the time of first upload, time of last update, user to first upload or last update the document, etc.

**Comment by gsautter** [comment]
I found `vitaMalacologica.14.1_2016 Bank Neubert Enidae Iran.pdf` right away filtering the dialog list for `docName` = `vitaMalacologica.14.1_2016` ...

`basteria.80.1-3.5.2016` should do as a filter value for finding the other one, I guess ...
