### ISSUE TITLE
BibRefs not Detected

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#115]
In this article, the bibRef parser does not work. The article is on TB

basteria.80.1-3.5.2016 Bank et al Lauriidae Enidae Vitrinidae Turkey

**Comment by gsautter** [comment]
What do you mean? "Does not work" in terms of a crash or hangup, or "Does not work" in terms of producing erroneous parses?

In case of the former, the logs might help a great deal.

**Comment by myrmoteras** [comment]
Does not parse.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by gsautter** [comment]
OK, I'll check. Got a UUID for me?

**Comment by myrmoteras** [comment]
basteria.80.1-3.5.2016 Bank et al Lauriidae Enidae Vitrinidae Turkey this is the file name on the SRS store. I don't have the UUID - see #114 

Also, the files we are looking for the IMF version had very long file names that didn't show up, that is these names seem not to be usable to search in the list of IMF files in #117

**Comment by gsautter** [comment]
The server only stores the first 32 characters of a file name ... a prefix of the file name might still do the trick in search. It's only TB that doesn't care about file names, anything with a "Load Document from GoldenGATE Server" surely does - if only by offering a respective filter in the document list dialog.

**Comment by gsautter** [comment]
For what I see, it's not the _parsing_ going wrong, but we are faced wit a failure to _detect_ the references in the first place ... The two steps are combined into one function (via a pipeline), but they are still two steps ...

**Comment by gsautter** [comment]
I have to state this document is a layout nightmare ... the non-justified main text misleads paragraph detection in quite a few places ... plus, it looks like a PhD student's draft a lot more than like a PhD's publication.

**Comment by gsautter** [comment]
The references are marked and parsed, have fun proceeding with the markup.

The UUID is D549FFF0FFC6FFD5FFDDFFA1FFAEFFF7

**Comment by gsautter** [comment]
The reason why the references failed to tag is a bit of a mystery to me ... especially since I couldn't really seem to reproduce the problem after fixing a few all-caps double names of authors.
