### ISSUE TITLE
Storing imf problem

### ISSUE THREAD

**Issue by millerjeremya** [gsautter/goldengate-imagine#118]
Tried to save several times to this file onto local drive: 
masterDocId="626BFFDFA20EFFCEDD210E0EFFB9FFB1"
Got this error message:
![image](https://cloud.githubusercontent.com/assets/4322250/23750831/fe25b2f4-04ce-11e7-8e93-a6f5b2798de8.png)

**Comment by gsautter** [comment]
Hard to tell without a log ... Have you tried saving to an "Image Markup Directory" instead?

What happens if you try saving to a different location, maybe a different partition? I know the error doesn't quite sound like it, but could it be your D partition is full?
