### ISSUE TITLE
Font: can't fix Ƌ to  ♂ 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#119]
in most cases in EJT, Ƌ can be replaced now with "edit font" command. But in this case

626BFFDFA20EFFCEDD210E0EFFB9FFB1
it does not work.

![image](https://cloud.githubusercontent.com/assets/4609956/23751556/34e1c3c0-04d2-11e7-84ac-40b0472da8a5.png)

WE also tried to change this in the word.csv, but it would not accept it.

**Comment by gsautter** [comment]
If you change the `words.csv`, this will very well be accepted, it just doesn't render through to the page images ... if you look at the XML, you see the word strings, and those should be correct. Which also means that it shows up correctly in TB.

However, I admit it's a nuisance ... and likely one related to #116 ... I'm currently investigating the latter. Has something to do with fonts re-using char images from other fonts, and if they do so in weird ways, that appears to cause problems. First two instances of this phenomenon, so it should be a rare thing.

I close this one, as I'm pretty sure the solution is one and the  same as in #116 .
