### ISSUE TITLE
scrambled images

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#12]
@gsautter here is an old problem with scrambled images in a recent article

![image](https://cloud.githubusercontent.com/assets/4609956/20920944/4e7315ec-bba2-11e6-96cd-2bbddda8016d.png)

http://tb.plazi.org/GgServer/html/3C548B6AFF8C6B02FF97F8C5FC7BFD11

http://tb.plazi.org/GgServer/summary/C06DF312FF8F6B08FFEDFFE3FFFCFF8E

**Comment by gsautter** [comment]
Looking at the upload time, this one was converted in June ... could well be that was back when the PDF decoder still scramled images ... triggered a repair, should be trough in some 15 minutes.
