### ISSUE TITLE
double reference on plazi.org

### ISSUE THREAD

**Issue by millerjeremya** [gsautter/goldengate-imagine#120]
I noticed in this treatment
http://treatment.plazi.org/id/9E5287A7A20CFFCADCCC0CB6FBA2F87F
That there are two copies of the one cited reference. 
![image](https://cloud.githubusercontent.com/assets/4322250/23751678/ae2b5516-04d2-11e7-9273-f8d25e701627.png)
Is there a way that I can fix this?

**Comment by gsautter** [comment]
Looks like the two responsible `bibRefCitation` annotations are matched by different selectors in the XSLT ... could be I have to resort to JavaScript here, just like for the `figureCitation`s ...

**Comment by gsautter** [comment]
On a different note: How do `subSubSection`, `heading`, and `emphasis` annotations end up having a `typeStatus` attribute? I'm rather sure nothing in out automated process would set that attribute on annotations of either type. So why did you?

**Comment by gsautter** [comment]
Fixed ... using JavaScript now for duplicate elimination, just like for the figure previews.
