### ISSUE TITLE
bibRef parsing

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#123]
when several authors are listed, only the first author is marked

![image](https://cloud.githubusercontent.com/assets/4609956/24073344/ad9e0910-0bf6-11e7-96cc-f9f984c41f7d.png)

FF9DFFC5FF960269FF93FFF5FFEB9504

p.s. I went through all the bibRefs and parsed them properly

p.p.s about 10 bibrefs have not been disocovered, so I marked them and then used parsed bibref. in this case, all the authors have been discovered

**Comment by gsautter** [comment]
I tend to think this single ampersand in the middle (and not between either all or only the least two authors) might have interfered with pattern matching here ... little we could do about that without incurring a lot of false positives.

About failure to discover references before parsing, this tends to happen for "authors" like "ICZN", which do not match patterns aimed at actual person names.

**Comment by gsautter** [comment]
On a second note, I cannot seem to reproduce any reference to get marked as such ... but the above still applies to getting RefParse confused about author lists ... especially around author lists abbreviated with intermediate "..." ellipses, listings of author initials alternating between "FS" and "F. S.", years being in parentheses or not, etc. Just an extremely sloppily lain out journal. That doesn't work all too well with patterns, which rely on syntactic regularity above everything else.

Apart from that, I realize I have to check whitespace handling in this one, mostly in the bibliography, and I will.

**Comment by gsautter** [comment]
Went over this one in more detail now, and have to remark that the layout of the bibliography is _extremely_ sloppy. It's not even consistent regarding whether or not to put the year in parentheses. And that is what messes up the reference style vote - RefParse is all about consistent punctuation.
