### ISSUE TITLE
font issue: chinese symbols

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#124]
in this article, chinese symbols are not detected
![image](https://cloud.githubusercontent.com/assets/4609956/24073546/412241e0-0bf9-11e7-8a3e-b617fc6d04a8.png)

FF9DFFC5FF960269FF93FFF5FFEB9504

**Comment by gsautter** [comment]
Our PDF facilities don't handle Chinese right now ... I couldn't even implement this, as I have no way of knowing whether or not what the software does makes any kind of sense ... no use in writing code for handling data you yourself cannot make any sense of.
