### ISSUE TITLE
omitting OCR: text blocks

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#125]
these sort of text blocks are not OCRed. Happens also in other journals
![image](https://cloud.githubusercontent.com/assets/4609956/24074280/c8a17224-0c05-11e7-8c54-aec3948edd1f.png)

[0222933.2016.1257074.pdf](https://github.com/gsautter/goldengate-imagine/files/852602/0222933.2016.1257074.pdf)

**Comment by gsautter** [comment]
Could you try selecting the abstract? I tend to think this is merely a rendering issue, with the gray backdrop of the abstract obscuring the markup.

I found something similar on Friday, and solved it on the train. Comes with the next update.
