### ISSUE TITLE
images only partially added to BLR

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#126]
only the first image has been uploded to BLR FFEEFF892824FF94A606FFDBFFFFFFBB 

https://doi.org/10.5281/zenodo.400738 as part of https://zenodo.org/record/400737#.WM59-SYrLAQ

**Comment by gsautter** [comment]
The captions of Figures 2, 3, 4, and 5 are lacking the association to the images ... please use "Assign Caption" to establish that connection, the the figures will show.
