### ISSUE TITLE
file does not open: unable to find images of all pages

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#127]
here a pdf that does not open

![image](https://cloud.githubusercontent.com/assets/4609956/24329601/81db1136-120b-11e7-8807-4572b6a25973.png)

[plants-05-00023.pdf](https://github.com/gsautter/goldengate-imagine/files/870613/plants-05-00023.pdf)

[GgImagine.20170325-1903.out.zip](https://github.com/gsautter/goldengate-imagine/files/870614/GgImagine.20170325-1903.out.zip)

**Comment by gsautter** [comment]
"Unable to find images for all pages" is an error you get when opening _scanned_ PDFs and there are some pages the converter cannot find a page image for.

Looking at this very PDF, it appears pretty much born-digital to me ... use that option for opening it and you should be fine.

**Comment by myrmoteras** [comment]
did you try it out? it does not work when dragging and dropping it into GGI

**Comment by myrmoteras** [comment]
it does not open when opening it with born digital
[GgImagine.20170327-2217.out.zip](https://github.com/gsautter/goldengate-imagine/files/873722/GgImagine.20170327-2217.out.zip)
