### ISSUE TITLE
geocooridnate tagger: bug

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#128]
wrong coordinates calculated. It seems, that in the case where there is an empty space between the degree and the following minute, that the the degrees are omitted in the calculation of the decimal degree

![image](https://cloud.githubusercontent.com/assets/4609956/24343183/683ee666-12c5-11e7-8022-2328558be739.png)

F11BF612FFC3FFEEFFDAEE14885BE175

I fixed it for the holotypes, but not for the rest, so you see records that ought to be in New Zealand are scattered all over.

**Comment by gsautter** [comment]
Well, looking at http://tb.plazi.org/GgServer/xml/0D228E6AFFC1FFECFF4DEAB189B0E61D , it seems more like those minutes of arch are lacking any kind of respective marker (high comma, forward or back tick, minute sign, etc.), which messes with the regular expression patterns. Will have to check the latter.

**Comment by gsautter** [comment]
This one is possible to fix with some regular expression adjustments. However, the more we relax those patterns, the more we're risking to incur false positives, which would be detrimental to accuracy in distribution data extraction. It's a tight rope ...

**Comment by myrmoteras** [comment]
let's see, whether we find more example  in Zootaxa, where it comes from. In a sense, though, it seems to be just an empty space between a degree symbol and a decimal minute?!

**Comment by gsautter** [comment]
The problem is there is no minute _symbol_ for the patterns to go at ... I tried a few pattern tweaks that fix this particular problem, but am still unsure if the patterns have become too little restrictive to ensure precision. We'll have to test this on a few more cases, I guess.

**Comment by gsautter** [comment]
Another pathological case that has been lingering forever ... and one due to nothing but sloppy copy editing ... laying it to rest.
