### ISSUE TITLE
file does not open: unable to find images of all pages (reopen from  #127)

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#129]
This file does not open in any ways.  Just open it an you see that the conversion stops.

see the logs file in  #127 

[GgImagine.20170327-2301.err.zip](https://github.com/gsautter/goldengate-imagine/files/873823/GgImagine.20170327-2301.err.zip)

**Comment by gsautter** [comment]
For failure to open as scanned, see #127 .

The failure to open as born-digital looks like a PostScript issue in the font decoder, will check.

**Comment by gsautter** [comment]
PostScript issues tracked down and fixed, decodes just fine now as born-digital. Fix comes with the next build.

I've put the IMF on the server for you, document name is  `plants-05-00023.pdf.imf`, UUID is `606EFFD6691CFF80BB730960FFACFFA2`
