### ISSUE TITLE
Feature request: publication date: add year, month, day

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#131]
We should make an effort to record as accurately as possible publication dates. In most cases, the day, month, year is available in the metadata somewhere. If not, then we should not write the by default the last day of the year.  This is wrong, and in this community, the exact date is relevant. 

For old legacy publications, this might not be so relevant, but by out services to provide accurate access to recent publications, this is relevant.

We should give it  high priority to fix.

**Comment by gsautter** [comment]
This is not an error, but a feature request. Classic bibliographic metadata only includes the year, and we do have that. It's only very recently in terms of our target documents that the exact publication date is even made available.

**Comment by gsautter** [comment]
But yes, I have not forgotten this one. Hope to get around to implementing it soon.

**Comment by gsautter** [comment]
This is finally implemented, deployed, and included in the style templates.
