### ISSUE TITLE
text grabled: continuation from #129

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#132]
I've put the IMF on the server for you, document name is plants-05-00023.pdf.imf, UUID is 606EFFD6691CFF80BB730960FFACFFA2

this file has a never seen error eg pag 6. I opened the IMF above and run  "detect document structure"

![image](https://cloud.githubusercontent.com/assets/4609956/24585048/5e42f042-1781-11e7-9214-ebd02d634f3b.png)

there is also an issue with a wrong page header 

![image](https://cloud.githubusercontent.com/assets/4609956/24585080/12a480a0-1782-11e7-912e-541f6cb3b836.png)

![image](https://cloud.githubusercontent.com/assets/4609956/24585082/1bb1fd76-1782-11e7-9305-0b05b2fc398a.png)

**Comment by gsautter** [comment]
Total catastrophe this one ... generated by some open source TeX extension, incredibly sloppy and crappy. Those words actually _do_ exist in duplication, with half of it not showing for some reason.

**Comment by gsautter** [comment]
Will be interesting to try and get clean page images, but I'm afraid this might turn out a lost cause. In such a shoddily published journal, do we really expect a considerable number of high quality treatments?
