### ISSUE TITLE
EJT contract_ related journals

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#133]
European Journal of Taxonomy
Adansonia  #135 
Geodiversitas #134 
Zoosystema 
Naturae #140 
Antrhropozoologica #139

**Comment by myrmoteras** [comment]
shared issues
figure detection: graphics
font issues

**Comment by myrmoteras** [comment]
Adansonia, Anthropozoologica, Zooystema with similar outline
![image](https://cloud.githubusercontent.com/assets/4609956/24607866/1808dcb0-1874-11e7-9009-8366cd48d99a.png)

**Comment by gsautter** [comment]
What was the question here, again?

**Comment by myrmoteras** [comment]
We need to check, which features in the layout in the above journals are the same, which ones are different to understand where to change the template

**Comment by gsautter** [comment]
You _should_ be able to re-open the issue (and you've done it before in other cases).

However, we have a whole tracker dedicated to this field now (https://github.com/plazi/EJT-testbed/issues).

And it's definitely not really a GGI issue. This is why I closed it in the first place.
