### ISSUE TITLE
EJT contract: Geodiversitas

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#134]
http://sciencepress.mnhn.fr/en/periodiques/geodiversitas

issues:
http://sciencepress.mnhn.fr/sites/default/files/articles/pdf/g2017n1.pdf 
font 
figureCitation does not work
Table detection
image issue

![image](https://cloud.githubusercontent.com/assets/4609956/24600856/d452055e-1856-11e7-9462-d198e9c776ff.png)

![image](https://cloud.githubusercontent.com/assets/4609956/24600746/4392ac9e-1856-11e7-95b2-e18a3acc0711.png)

![image](https://cloud.githubusercontent.com/assets/4609956/24600813/9784ee34-1856-11e7-8b2a-497e4f8fbc02.png)

![image](https://cloud.githubusercontent.com/assets/4609956/24600828/ac7b3df2-1856-11e7-889b-52dc54add09e.png)

**Comment by myrmoteras** [comment]
figure issues
![image](https://cloud.githubusercontent.com/assets/4609956/24600880/f4711e2e-1856-11e7-9ae8-7bca78561737.png)

**Comment by myrmoteras** [comment]
font issues

![image](https://cloud.githubusercontent.com/assets/4609956/24600924/28499a0a-1857-11e7-865d-79da0026cdcf.png)

fonts can't be fixed

![image](https://cloud.githubusercontent.com/assets/4609956/24600954/4d97160c-1857-11e7-8f4e-4eef1576e1e8.png)

**Comment by myrmoteras** [comment]
font issue

words falling apart and fonts can't be fixed

![image](https://cloud.githubusercontent.com/assets/4609956/24601003/7eb44ca0-1857-11e7-8937-f23bd14eb149.png)

**Comment by gsautter** [comment]
OK, nice, 5 issues in one ... this will be endless.

**Comment by gsautter** [comment]
The small-caps stuff should be resolved with #140 , as should be the missing char images in font correction.

**Comment by gsautter** [comment]
Regarding the split-up figures, I don't think there is much we can do about it ... if they are too far apart, they end up in different blocks.

**Comment by gsautter** [comment]
The figure and table citations look an awful lot like downstream problems of the font issues, which are resolved.
