### ISSUE TITLE
EJT contract: Adansonia

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#135]
http://sciencepress.mnhn.fr/en/periodiques/adansonia/38/2

http://sciencepress.mnhn.fr/sites/default/files/articles/pdf/a2016n2a1.pdf

http://treatment.plazi.org/GgServer/summary/FF98FFE63A184E0FFFF1D9395734FFA0

font issues
bibRef nor discovered and parsed
taxonomicName: brackets, subsequent reviser
taxonomicNameLabel not added
type status

**Comment by myrmoteras** [comment]
font issues

![image](https://cloud.githubusercontent.com/assets/4609956/24601169/2bae7732-1858-11e7-94b9-6c31429a7b91.png)

![image](https://cloud.githubusercontent.com/assets/4609956/24601181/397ffa98-1858-11e7-98c8-459d7aca0064.png)

**Comment by myrmoteras** [comment]
bibRef parsing does not work

![image](https://cloud.githubusercontent.com/assets/4609956/24601732/59987e3e-185a-11e7-9a4f-1c76a5baa983.png)

**Comment by myrmoteras** [comment]
taxonomicNameLabel not disovered

**Comment by myrmoteras** [comment]
botanic taxonomic names: 

Brackets, and reviser not added

![image](https://cloud.githubusercontent.com/assets/4609956/24601960/2d642448-185b-11e7-9dda-a798f78eff01.png)

**Comment by myrmoteras** [comment]
type status (generally in Botany given as holo-....., iso-.....

![image](https://cloud.githubusercontent.com/assets/4609956/24602490/4617bd4a-185d-11e7-867b-112d8af3bcf9.png)

**Comment by gsautter** [comment]
And another 5-in-1 to never end.

**Comment by gsautter** [comment]
About the taxon names: Simply remove the paragraph breaks and the full authorities and status labels will be detected.

**Comment by gsautter** [comment]
Font issues most likely related to #140

**Comment by gsautter** [comment]
Bibliographic reference parsing issues are most likely a downstream effect of font issues, which get in the way of regular expression patterns that find the author names and list.

**Comment by myrmoteras** [comment]
they are, because you can manipulate the fonts, and then add bibRefs and once this is there, the parsing works

**Comment by gsautter** [comment]
Font issues are all but resolved, pending some detail catches detailed out in other tickets (#140), and everything else in this one is downstream problems of the original font issues, so I'm closing this one.
