### ISSUE TITLE
EJT contract: Anthropozoologica

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#139]
http://sciencepress.mnhn.fr/en/periodiques/anthropozoologica/50/2

http://sciencepress.mnhn.fr/sites/default/files/articles/pdf/az2015n2a5.pdf

urn:lsid:plazi.org:pub:C95AFFB2BA44FFD0AC3FBD22FFDCFFAF

https://zenodo.org/record/439867#.WOIn8lp960r

**Comment by myrmoteras** [comment]
graphic / image not properly detected Fig 6

![image](https://cloud.githubusercontent.com/assets/4609956/24604942/2effb66c-1867-11e7-844e-75f7fbb2ceab.png)
the next figure has then be properly detected

**Comment by myrmoteras** [comment]
Fig in captions two words

![image](https://cloud.githubusercontent.com/assets/4609956/24605025/6f75cd4e-1867-11e7-9202-e6d152e6fd72.png)

**Comment by myrmoteras** [comment]
Font issues
![image](https://cloud.githubusercontent.com/assets/4609956/24605054/915b9222-1867-11e7-9ff2-93e54af9bb23.png)

**Comment by gsautter** [comment]
Most likely related to #140

**Comment by gsautter** [comment]
Figure 6 renders just fine ... it's only that it get chopped up into individual blocks by page structure detection ... draw a box around the whole and use "Mark Graphics", and you have it all in one. Remove the `httpUri` attribute from the caption before storing to the server, and the figure will be replaced on Zenodo.

**Comment by gsautter** [comment]
Regarding the captions, we have a tiny problem here: in a sans-serif font, 'G' and 'g' are pretty easy to tell apart, but 'I' and 'i' not so much. This results in the decoder getting the small-cap 'G', but failing to do so on the 'I', as both Unicode-map to their lower case counterparts. This is one for the correction dialog, which I now have made sure to include all the characters again (see #140).

**Comment by gsautter** [comment]
The small-caps issues have all but disappeared with the fix for #140 ... working on the rest (mostly 'f' mistaken for 'F')

**Comment by gsautter** [comment]
Turns out the 'f' vs. 'F' issue really is one of similarity ... guess I'll have to subject all the small-caps candidates to the same neighborhood analysis as used in OCR based decoding ...

**Comment by gsautter** [comment]
Figure 3 is a question of page content flipping, which is intended to get bottom-up tables into a horizontal position. Will have to check how to prevent flipping in this case ...

**Comment by gsautter** [comment]
Resolved the issue with Figure 3 based upon the size of the area with non-left-right words in comparison to any larger surrounding graphics.

**Comment by gsautter** [comment]
Added a special small-caps catch for "i" vs. "I" and "f" vs. "F" now, as scaling and vertical position analysis don't help with these two (scaling helps with "w" vs. "W", for instance, and vertical position helps with "p" vs. "P"). Said catch basically uses the same neighborhood based disambiguation technique as used in OCR based font decoding. And it works like a charm.
