### ISSUE TITLE
Zootaxa broken images

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#14]
@gsautter http://tb.plazi.org/GgServer/summary/6F13793CFFEFFFFDDE679B5F8A5B0311

In this file, the images are broken. Is it possible to fix it?
tx

**Comment by gsautter** [comment]
If you look at the date of the lat update in any of the treatments in this one (eg http://tb.plazi.org/GgServer/html/932A0144FFE2FFF0DEF0997C89610433), you see that it was uploaded April 18th, 2016. That was outside our year-by-year Zootaxa processing schedule, namely way ahead of it, and thus before we fixed image extraction.

It will be repaired along with the others (currently running 2010).

**Comment by myrmoteras** [comment]
Do you think this, and may be some coral treatments, can be fixed by next Wednesday  when I need them for a lecture?
d

**Comment by gsautter** [comment]
Just give me a list of the article UUIDs, and I'll schedule these documents to be repaired earlier.

Next Wednesday should not be a problem if I have these UUIDs by Friday.
