### ISSUE TITLE
EJT contract: Naturae

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#140]
http://sciencepress.mnhn.fr/sites/default/files/articles/pdf/naturae-4-pdf.pdf

https://zenodo.org/record/439881#.WOItOlp960o

**Comment by myrmoteras** [comment]
font issue
![image](https://cloud.githubusercontent.com/assets/4609956/24606196/45f94234-186c-11e7-95bf-37ebbdbf724b.png)

**Comment by gsautter** [comment]
Now this one will surely help me get my French up to speed for real ... not sure how well the parsers will handle this.

**Comment by gsautter** [comment]
Tracked and fixed ... was  legacy problem in decoding Type1C fonts (the first ones implemented) which caused too many characters to be skipped over in rendering. Fixed that now, and both the small caps are recognized correctly and all the rendered char images are available for double-checking and correcting.

The document is on the server with name `naturae-4-pdf.pdf.imf` and UUID `CC14FFF6FFF1FF8B6E62FF96FFC26514`.
