### ISSUE TITLE
andansoni: wrong images

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#141]
this is the file I used to look at the structure for the EJT proposal #135 
http://treatment.plazi.org/GgServer/summary/FF98FFE63A184E0FFFF1D9395734FFA0
since this is already uploaded, I might be helpful to fix this. 

It is one of the articles that cause multiple propblems, see upload of file.
But here there is the issue of images:
The first two of four images are uploded, but not the last two. The 3rd figure is also not properly converted
It seems that the conversion of figures need some tweaking. Se also issue #139 

original
![image](https://cloud.githubusercontent.com/assets/4609956/24608997/3f629e2c-1879-11e7-8cdb-e906606fab55.png)

extracted
![image](https://cloud.githubusercontent.com/assets/4609956/24609022/583630f8-1879-11e7-9396-3f1644165050.png)

**Comment by gsautter** [comment]
See my mails ... this line drawing comes at 3000 DPI (!!!), totally depleting the server's memory on loading ...

**Comment by gsautter** [comment]
I'll try and somehow scale it down to a manageable resolution, say 1200 DPI ...

**Comment by gsautter** [comment]
I managed to scale down this behemoth image with a command line tool, and then finally got the whole thing to Zenodo: https://zenodo.org/record/439841 ... sorry for wasting a few record IDs before getting this to work.
