### ISSUE TITLE
figure not uploaded to BLR

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#143]
@gsautter in this article FFCC8B0CFFA3FF80A43F537CFFC6F93F
 , the figures are not uploaded to BLR. I can't figure out why. Please let me know how to fix this

https://doi.org/10.5281/zenodo.546880

http://tb.plazi.org/GgServer/html/03F5F374FFA1FF84A05D55ABF93AFAC3

http://tb.plazi.org/GgServer/summary/FFCC8B0CFFA3FF80A43F537CFFC6F93F

**Comment by gsautter** [comment]
The captions are not properly associated with the figures, for what it seems ...

**Comment by gsautter** [comment]
OK, the association between images and captions is fine, but the backing image material is not quite so: This PDF is definitely scanned, but the scans are stored in the IMF as figures, just like they would be in a born-digital document ... on top of that, the list of supplements (`supplements.csv`) is empty safe for the original PDF, which basically means that the document doesn't "know" its supplementary scans. No chance for the Zenodo uploader to get a hand on any scan cut-outs it could upload for the figures.

I have no idea how you decoded this one, and what happened to `supplements.csv` afterwards, but it's definitely quite out of the ordinary.

**Comment by gsautter** [comment]
This PDF is pretty strange in its entirety ... there are minuscule 1x1 pixel images (in addition to what most surely is the scans) in pages 2, 3, and 6. All white, but zoomed to quite some size. No idea why the PDF is structured this way, no idea what those single-pixel images are meant for. Looks like we need another filter ...

**Comment by gsautter** [comment]
Added a filer for extremely low resolution figures in page image generation, and the scans show up fine. Also got them on the server, and then on Zenodo.

**Comment by gsautter** [comment]
Left to wonder, however, how those scans got lost in the first place ... for what it seems they were already present on the server, for otherwise the upload would have taken way longer. The only explanation I have is that this PDF was first decoded as scanned, and uploaded to the server, then again decoded from scratch as born-digital, and uploaded to the server again ... that's the only way such a mess could possible happen.

Whatever, this one is solved.

**Comment by millerjeremya** [comment]
It could be that this example has a similar problem: 
http://tb.plazi.org/GgServer/summary/FFEEFFB22C17FFEEFF9E8F29FFCBFFD8
Again a scanned document, images not showing up even though they appear (as far as I can tell) to be marked correctly. 
Again, supplements.csv is pretty sparse:

"id","type","mimeType","attributes"
"source","source","application/pdf","mimeType<application/pdf>type<source>"

In both documents, there was nothing special about the process, simply read and marked up using GG imagine.

**Comment by millerjeremya** [comment]
Another example with (apparently) the same problem:
http://tb.plazi.org/GgServer/summary/FFF2D503FFD8154B7903FF201A02FF92

**Comment by myrmoteras** [comment]
https://github.com/gsautter/goldengate-imagine/issues/143#issuecomment-300774191
