### ISSUE TITLE
merge annotations from two documents

### ISSUE THREAD

**Issue by millerjeremya** [gsautter/goldengate-imagine#144]
My student has marked up a Zootaxa article that has already been automatically processed. The automatic method seems to have worked perfectly, except that of course the materials citations are not parsed. My student has annotated the materials citations. Is there a way to merge my student's annotated materials citations into the Plazi processed imf?
I tried opening both the Plazi imf and my students imf at the same time, but copy attributes of materialsCitation annotation doesn't work between documents. I also looked at annotations.csv, but wasn't certain I could modify this (by copying materialsCitations annotations from one document to the other in a text editor) without unanticipated consequences.

**Comment by gsautter** [comment]
Guess Donat told you that trick ... right?

Anyway, if you save both to your local disk, best as IMD (basically non-zipped IMFs) with names that are clearly as possible to distinguish, you _can_ copy data between the two `annotation.csv`s. Just make sure to not only copy the `materialsCitation` annotations, but also the subordinate details. And also make damn sure to use Notepad++ or the like and _not_ Excel, as the latter tends to interpret and modify data.

Afterwards, load the merged-up document in GGI and upload it to the server, where it should amend the existing one.
