### ISSUE TITLE
file does not show up in BLR

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#151]
this is the deposit of the file https://zenodo.org/record/580884#.WR1dqZ197ZR in BLR. There are links to treatments, but they do not show up, nor can I find the name. 
How can I find the UUID of the article so I can include the article here?

**Comment by gsautter** [comment]
Finally nailed this one ... a few duplicate table cells, which resulted in multiple `td` annotations with the same ID, foiled the transformation to XML. Fixed that now. A really weir one.

**Comment by gsautter** [comment]
If the treatments don't show up right away, try `?cacheControl=force`, OK?
