### ISSUE TITLE
name issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#155]
@gsautter 

Following our discussion with name issue: here is one where only the species epithet has been marked up, 

http://tb.plazi.org/GgServer/# see 2017-05-25, http://tb.plazi.org/GgServer/summary/FF93FFAB2840FFD7F767FF87FFA3B03E

**Comment by gsautter** [comment]
For "Lethe", I guess we're lacking a genus there ... another monograph with odd/incomplete treatment taxa. one species just starts the paragraph, and two others come up with a capital starting letter. Hard one to sort out, as FAT on contemporary publications does quite well presuming ICZN compliant taxa ... guess this is one of the oddjobs that just require some manual intervention.
