### ISSUE TITLE
name issue: taxonLabel missing for new subfamily, genera

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#156]
@gsautter in this case there is no indication for a new subfamily, genus, etc. 
http://treatment.plazi.org/GgServer/summary/FFAA9E75FFB7FF9BD2278D50ED097120

**Comment by gsautter** [comment]
Classic case of thesaurus problem ... "new genus" or "gen. nov." is what it knows right now, as these are the grammatically correct word orders. "nov. gen." has to be added, along with "nov. spec.", etc.

Will do this right away, it's great offline work for the train.

**Comment by gsautter** [comment]
This one has finally been included in one of the last builds.
