### ISSUE TITLE
unable to open pdf

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#157]
@gsautter I am trying to open this file, but it does not work.
It might be, because it had a protection, which I removed with a PWD remover.

[Logs.zip](https://github.com/gsautter/goldengate-imagine/files/1056296/Logs.zip)

[MyremcNews_21.117.pdf](https://github.com/gsautter/goldengate-imagine/files/1056293/MyremcNews_21.117.pdf)

**Comment by gsautter** [comment]
Our PDF decoder can break a lot of impediments, but _not_ read passwords. If it opens in Acrobat for reading without a password, the decoder should be able to handle it. If the password dialog still comes in Acrobat, there's little I can do ... maybe ABBYY might help?

**Comment by gsautter** [comment]
After checking the logs (just got out of the "dark zone"), this one looks like a color space problem, which is surely independent of having password or having no password. Will check ...

**Comment by gsautter** [comment]
Fixed ... yet a new color space variant that we'd never encountered before ...
