### ISSUE TITLE
wrong higher taxonomy

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#158]
@myrmotera here is a wrong higher taxonomy
https://zenodo.org/record/286113#.WTgejq597AQ

**Comment by gsautter** [comment]
Then please open the IMF and correct it ... all of this automated processing works on a best effort basis, and the occasional error just happens, and always will. We don't have a perfect system, simply as there can never be one, we're just good at minimizing error probabilities.
