### ISSUE TITLE
File does not open in GGI

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#160]
[abrusan__krambeck_2006.pdf](https://github.com/gsautter/goldengate-imagine/files/1065986/abrusan__krambeck_2006.pdf)
[Logs.zip](https://github.com/gsautter/goldengate-imagine/files/1066001/Logs.zip)

**Comment by gsautter** [comment]
The logs look like an ordering problem in word sanitization ... will check ...

**Comment by gsautter** [comment]
Fixed ... was a sorting irregularity in word neighborhood analysis.
