### ISSUE TITLE
materialsCitation: Wrong country

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#161]
on this case, India is shown in the map (specimen), next to the proper record of Guatemala. 
http://tb.plazi.org/GgServer/html/5E79879BFFE9C96BC2F28A2D94BD5B8E

However, I can't find the India in the text

**Comment by gsautter** [comment]
"Hind", the Persian name of India ... another one to add to the black list, I guess.

Done.
