### ISSUE TITLE
adding Zootaxa to the pipeline

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#162]
@gsautter the current flow of documents from Zootaxa is interrupted. We need to find a new channel. 

As a first step, I would recommend that I copy paste each article from my AMNH Zootaxa account to a directory that will trigger the conversion
As a second step, that we figure out how to do this automatically again, using either the AMNH or a Swiss library account that we might get.
As a third step, there is a chance that Zootaxa will provide us direct access - this is in discussion. But I am not sure, how this will resolve

**Comment by gsautter** [comment]
@myrmoteras if you download via AMNH, couldn't you just as well store those PDFs locally, run the batch on the whole folder, and then upload all the resulting IMFs? Basically the same way you processed some 15 years of backlog last year?

Also, I hope Ross at least still has access to the scripts that do the page scraping, download, and upload ... we might run those somewhere. Terry might have some new opportunities coming with his new job, for instance.

On a different note, I think this is the wrong forum ... this is most definitely not a GGI issue. Let's restrict this one to conversion and extraction issues, please.

**Comment by myrmoteras** [comment]
@gsautter: I just tried out to run the batch mode, but got this message

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Donat>d:

D:\>cd D:\GoldenGateImagine20170529

D:\GoldenGateImagine20170529>java -jar -Xmx9216m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\2017\temp" DT=BD
Loading parameters
GoldenGATE Imagine core created, configuration is null
Image Markup Tool 'StructureDetector' not found,
check entry 'imageMarkupTools' in GgImagineBatch.cnfg

D:\GoldenGateImagine20170529>

The GGI version I used is the most recent I can obtain
NEW IN VERSION 2017.04.14.19.37

Any help? Thanks d

**Comment by myrmoteras** [comment]
Btw – this is the command I used

java -jar -Xmx9216m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\2017\temp" DT=BD

d

From: Donat Agosti
Sent: Thursday, July 13, 2017 10:39 AM
To: 'gsautter/goldengate-imagine' <reply@reply.github.com>
Subject: RE: [gsautter/goldengate-imagine] adding Zootaxa to the pipeline (#162)

@gsautter: I just tried out to run the batch mode, but got this message

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Donat>d:

D:\>cd D:\GoldenGateImagine20170529

D:\GoldenGateImagine20170529>java -jar -Xmx9216m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\2017\temp" DT=BD
Loading parameters
GoldenGATE Imagine core created, configuration is null
Image Markup Tool 'StructureDetector' not found,
check entry 'imageMarkupTools' in GgImagineBatch.cnfg

D:\GoldenGateImagine20170529>

The GGI version I used is the most recent I can obtain
NEW IN VERSION 2017.04.14.19.37

Any help? Thanks d

**Comment by gsautter** [comment]
The command looks good.

The fact that the batch does find it should first execute 'StructureDetector' furthermore tells me that it should read `GgImagineBatch.cnfg` alright.

If you have a line like `//configName = "Default.imagine";` in `GgImagineBatch.cnfg`, simply remove the two slashes and it should work just fine. My bad the two slashes are there, will take care of that right away.

If you have a line like `//configName = "Default.imagine";` in `GgImagineBatch.cnfg` (without the two slashes), it might be that the GGI installation you're running the batch from is lacking the "Default.imagine" configuration. In that case, check if there is a `<GGI>/Configurations/Default.imagine` folder, and if not, start GGI with web access and download said configuration.

**Comment by myrmoteras** [comment]
Ok – this seems to work- I am letting it run over night and see tomorrow

**Comment by gsautter** [comment]
Just sent you a hot fix JAR with a fix. The latter will of course also be in the next build.
