### ISSUE TITLE
batch processing error

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#164]
[zootaxa.4288.1.1.pdf](https://github.com/gsautter/goldengate-imagine/files/1147775/zootaxa.4288.1.1.pdf)
`
Processing document 'E:\diglib\zootaxa\2017\temp\zootaxa.4288.1.1.pdf'
 - loaded PDF of 1414699 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FA7E2A39FFC4FFF3FFD3067BFFF2FFC5'
 - assigned document style 'zootaxa.2013.monograph'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 128 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 405 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 2 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 19 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Running Image Markup Tool 'Clean Table Annotations'
Running Image Markup Tool 'Remove Duplicate Annotations'
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Error processing document 'E:\diglib\zootaxa\2017\temp\zootaxa.4288.1.1.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.gamta.AnnotationUtils.liesIn(AnnotationUtils.java:115)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.classifyMaterialsCitationProperNames(MaterialsCitationHandler.java:3149)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.markMaterialsCitations(MaterialsCitationHandler.java:1752)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.process(MaterialsCitationHandler.java:498)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$MonitorableAnalyzerDocumentProcessor.process(AnalyzerManager.java:229)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:328)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:283)
        at de.uka.ipd.idaho.goldenGate.plugin.filteredProcessor.FilteredDocumentProcessorManager$FilteredDocumentProcessor.process(FilteredDocumentProcessorManager.java:152)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:547)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:430)
Processing document 'E:\diglib\zootaxa\2017\temp\zootaxa.4289.1.1.pdf'
 - loaded PDF of 33835059 bytes
Extracting page content
Assessing font char usage
Importing page words
`

**Comment by gsautter** [comment]
Will check on the train.

**Comment by gsautter** [comment]
I have trouble finding the spot where this happens ... the line numbers in the error message don't really correspond to my latest code. Could you start GGI and do an update? I'll keep on searching in parallel.

**Comment by myrmoteras** [comment]
I run an update before I started this batch. I let it run, update and run those files again that did not work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gsautter** [comment]
I've now put a fix for this on the server, along with a new build.

As this error happens in code that is part of the Configuration (rather than the application core), an online update should do as well.
