### ISSUE TITLE
material citations test file

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#167]
this is a treatment with hundreds of material citations, some marked up, some omittied. Might be a good one to play with

http://tb.plazi.org/GgServer/html/9C4872296D74FFD1FF6DFF3902CBF924

**Comment by gsautter** [comment]
Wow ... this one is monstrous.

What immediately jumps my eye is the slash and double slash separated materials attributes in the "Type material" paragraph - a more unusual form of punctuation, I guess.

The "Additional material" part is a cornucopia of data, that's true. And nice to see most of it was marked pretty much OK.

I do see that I have to tweak / extend some proper name patterns, namely for:
- enumerated initials like "F. & T. Terzani"
- further location name infixes like "Pernegg a. d. Mur" or "Hluboká nad Vltavou" or "Grünau im Almtal"
- some more tolerance for non-catalog collection codes like "CFT"

**Comment by gsautter** [comment]
I've uploaded a refined materials citation handler (tagger/parser) on Tuesday, covering all these aspects. Hope this gets us better data than the previous version.

Ultimately, however, materials citation parsing can only be a best-effort endeavor, especially regarding location names, as there is too much diversity (both in the location names proper and in the materials citations as a whole) to base the parsing on any fixed rules.

The handler tries to disambiguate as much as possible by means of inference, but if forma varies all too much, like in this example, there will always be a few errors.
