### ISSUE TITLE
treatment structure: host should be "biology / ecology"

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#169]
![image](https://user-images.githubusercontent.com/4609956/28407225-aed1ea74-6d33-11e7-8479-d2b77caf8e66.png)

this might be a low hanging fruit to make paragraphs about host relationships part of the type=ecology/biology subsubsection

**Comment by gsautter** [comment]
OK, you got it ... just another rule in the paragraph classifier that's behind treatment structuring. Update comes with next build.

I think we should actually start (???) a list of in-line titles that point to specific `subSubSection` types.

**Comment by myrmoteras** [comment]
Let me know, where you want to have the list. In the google doc manual to IMF?

**Comment by gsautter** [comment]
I guess a GoogleDoc would be the right way to go ... or a Wiki page. Do we have a Wiki? If so, we've been neglecting it for a good few years ... it's just that Wiki pages are so much easier to edit as well as structure.
