### ISSUE TITLE
font issue: miscoding that can not be removed

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#17]
@gsautter in this case, I can not fix the font

![image](https://cloud.githubusercontent.com/assets/4609956/21027022/5bb7bb6a-bd8f-11e6-8c7b-9bb505c38a16.png)
[AM52_38_49.pdf](https://github.com/gsautter/goldengate-imagine/files/640558/AM52_38_49.pdf)

**Comment by gsautter** [comment]
What do you mean you "cannot fix the font"? What happens when you try via "Edit Font" on the words?

I know we had a respective issue earlier this week (#11), but that's since been fixed.

**Comment by myrmoteras** [comment]
I can not fix it with "Edit Font". it does not show up.

**Comment by gsautter** [comment]
OK, in that case a look at the logs might help shed some light ...

**Comment by myrmoteras** [comment]
![image](https://cloud.githubusercontent.com/assets/4609956/21027840/ecd84cba-bd92-11e6-80f1-e22bf98fcc60.png)

too long - just run the above file and you have the error.

**Comment by gsautter** [comment]
I could not reproduce any error, or really anything going wrong, on "Edit Font" ... everything according to plan, the dialog opens just as supposed to, and corrections are written through just fine.

On a more general note, I'm left to wonder what all those special characters are used for in this document ... there is a few I'm pretty sure I've never even seen before.
