### ISSUE TITLE
pdf not processing in batch processing

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#174]
[zootaxa.4294.3.2.pdf](https://github.com/gsautter/goldengate-imagine/files/1202318/zootaxa.4294.3.2.pdf)

**Comment by gsautter** [comment]
The error log would be helpful, and also the time when you last updated. Might have something to do with the new Authority Augmenter that I included last Wednesday, and the log would tell me.

**Comment by gsautter** [comment]
Same issue as #175
