### ISSUE TITLE
pdf not processing in batch mode

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#175]
[zoobank.4300.4.2.pdf](https://github.com/gsautter/goldengate-imagine/files/1202335/zoobank.4300.4.2.pdf)
[zoobank.4300.4.4.pdf](https://github.com/gsautter/goldengate-imagine/files/1202336/zoobank.4300.4.4.pdf)

this referes to zootaxa.4300.4.2

 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 14 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 0 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Indexing taxonomic names
Resolving in-bucket authority conflicts
Merging compatible buckets
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 24 taxon names
Error processing document 'D:\diglib\zootaxa\2017\temp\zoobank.4300.4.2.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.plugins.taxonomicNames.authority.AuthorityAugmenter.process(AuthorityAugmenter.java:476)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$MonitorableAnalyzerDocumentProcessor.process(AnalyzerManager.java:229)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:328)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:543)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:430)
Processing document 'D:\diglib\zootaxa\2017\temp\zoobank.4300.4.4.pdf'
 - loaded PDF of 7136678 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is '7339FFA5FFC5FF9AD95FEE5D99481363'
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 15 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 15 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 1 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Indexing taxonomic names
Resolving in-bucket authority conflicts
Merging compatible buckets
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 24 taxon names
Error processing document 'D:\diglib\zootaxa\2017\temp\zoobank.4300.4.4.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.plugins.taxonomicNames.authority.AuthorityAugmenter.process(AuthorityAugmenter.java:476)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$MonitorableAnalyzerDocumentProcessor.process(AnalyzerManager.java:229)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:328)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:543)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:430)
Processing document 'D:\diglib\zootaxa\2017\temp\zoobank.4300.4.5.pdf'
 - loaded PDF of 7819280 bytes
Extracting page content
Assessing font char usage
Importing page words

**Comment by gsautter** [comment]
As just assumed in #174 , looks like this is an Authority Augmenter issue ... will check.

**Comment by gsautter** [comment]
Was an edge case in Authority Augmenter that caused the exception somewhere downstream. Fixed now, updated build and configurations are out.

To use them on your machine for the batch, you'll simply have to start GGI once with online access so it fetches the update.
