### ISSUE TITLE
pdf processing takes too long zootaxa.4299.2.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#177]
This document has been running for an hour now, and I killed it
[zootaxa.4299.2.1.pdf](https://github.com/gsautter/goldengate-imagine/files/1202586/zootaxa.4299.2.1.pdf)

D:\GoldenGateImagine_20170221>java -jar -Xmx9216m GgImagineBatch.jar "DATA=D:\diglib\zootaxa\2017\temp" DT=BD
Loading parameters
GoldenGATE Imagine core created, configuration is Default.imagine
Image Markup Tool 'StructureDetector' loaded
Image Markup Tool 'MetaDataAdder' loaded
Image Markup Tool 'KeyHandler' loaded
Image Markup Tool 'ParseBibliography.imTool' loaded
Image Markup Tool 'MarkBibRefCitations.imTool' loaded
Image Markup Tool 'MarkTaxonNames.imTool' loaded
Image Markup Tool 'TableAnnotCleaner' loaded
Image Markup Tool 'RemoveDuplicateAnnots' loaded
Image Markup Tool 'TreatmentTaggerStyled.imTool' loaded
Image Markup Tool 'ExtractMaterialsCitations.imTool' loaded
Image Markup Tool 'CheckAnnotNesting' loaded
Processing document 'D:\diglib\zootaxa\2017\temp\zootaxa.4299.2.1.pdf'
 - loaded PDF of 597873 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is '7150FFD17072FFB3BF4D9A16FFA6FFCC'
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 40 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 429 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 0 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 206 taxon names
Running Image Markup Tool 'Clean Table Annotations'
Running Image Markup Tool 'Remove Duplicate Annotations'
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Processing document

**Comment by gsautter** [comment]
Got it ... found a combinatorical explosion hazard when dealing with enumerations. In this case, a "distribution" paragraph lists some 20 countries, and assembling that enumeration just runs out of hand.

I've changed the Materials Citation Handler now to abandon a paragraph as soon as an enumeration of more than two country names is found.

However, I've also found a similar problem for long enumerations of location names. Fixed the problem proper, but the number of potential interpretations of the sequence of potential materials citation details is still riddled with the same problem. I'll have to figure out a way of catching that.

#178, #179, and #180 are the very same problem, so I'm closing the latter three tickets, as the fix to this one will fix them as well.

**Comment by gsautter** [comment]
Should be fixed with the new build just uploaded to http://tb.plazi.org/GgServer/Downloads/GgImagine-Default.imagine.zip
