### ISSUE TITLE
pdf processing takes too long zootaxa.4299.3.2.

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#178]
[zootaxa.4299.3.2.pdf](https://github.com/gsautter/goldengate-imagine/files/1202661/zootaxa.4299.3.2.pdf)

This file stalls, and can only be killed by killing Java. It run 1 hour

![image](https://user-images.githubusercontent.com/4609956/28998647-e8a34d2e-7a30-11e7-8f66-68cd831b4365.png)

Processing document 'D:\diglib\zootaxa\2017\temp\zootaxa.4299.3.2.pdf'
 - loaded PDF of 4491641 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FFCFFFF1FF95FD2F3A7AFFA3D921C61D'
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 24 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 16 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 1 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 9 taxon names
Running Image Markup Tool 'Clean Table Annotations'
Running Image Markup Tool 'Remove Duplicate Annotations'
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Processing document

**Comment by gsautter** [comment]
Same as #177, closing as duplicate.
