### ISSUE TITLE
pdf not processed  zootaxa.4299.3.2

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#189]
[zootaxa.4299.3.2.pdf](https://github.com/gsautter/goldengate-imagine/files/1210369/zootaxa.4299.3.2.pdf)

I don't have the log for this one from the batch I was running

**Comment by gsautter** [comment]
It's _identical_ to #178 ... same file even. Have been testing with this one since Sunday. Will resolve with #178.
