### ISSUE TITLE
distorted images

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#194]
in this Bulletin, the images are distorted. I like to get this publication processed to show that we can't just extract  articles with treatments, and how such illustrations can be used to document ontologies - a no brainer for us, but not everybody

![image](https://user-images.githubusercontent.com/4609956/29239222-b29efdb8-7f49-11e7-8ce6-191c837fc7a5.png)

![image](https://user-images.githubusercontent.com/4609956/29239257-bd973d74-7f4a-11e7-8c64-225491cb346e.png)

the file is here (56MB)
http://digitallibrary.amnh.org/bitstream/handle/2246/6124/B355.pdf?sequence=1&isAllowed=y

**Comment by gsautter** [comment]
I'll look into it soon as #177 (and all its duplicates) are resolved.

**Comment by gsautter** [comment]
This one uses a highly exotic 5-channel (!!!) color space for the images (even though it's actually only using the very first channel, for black) ... I'll try and figure out a way ...

**Comment by gsautter** [comment]
And did it ... first example for a thus far unused color space implementation always has the potential for a surprise, simply because it's the very first test of that particular snippet ever. Thanks for finding this example.

**Comment by gsautter** [comment]
Fixed in the new build I just put up at http://tb.plazi.org/GgServer/Downloads/GgImagine-Default.imagine.zip

**Comment by myrmoteras** [comment]
@gsautter it works only in the version above, but when I update my current version of GGI it seem not to work. Or could this be, because the images are stored, but how can I find the respective folder in my many supplements?

**Comment by gsautter** [comment]
`<GGI>/PageImages` and `<GGI>/Supplements` are always good places to look for cached errors, and what you describe surely does sound like a cache problem.

If the erroneous PNGs were produced via the GGI batch with `CACHE=<cacheFolder>` parameter specified, `<cacheFolder>/PageImages`, `<cacheFolder>/Supplements`, and `<cacheFolder>/TempDocs/<docName>` are also good places to look. The latter folder is the one that stores the intermediate results of batch processing so in case of an error the batch can start over right where it crashed.
