### ISSUE TITLE
font decoding: italics h bug

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#20]
@gsautter again the previous problem. But this time the letter does not show up in the font decoding menu, thus nothing to correct, whilst before I could fix half of it (either italic h= he or h, which led to wrong names with either Cheiracantheidium or Chiracanthidium.

![image](https://cloud.githubusercontent.com/assets/4609956/21042058/7a19ea46-bdef-11e6-9a15-d6908e72bbbb.png)

![image](https://cloud.githubusercontent.com/assets/4609956/21042075/8f45a2de-bdef-11e6-8d71-45a57053e457.png)

[AM52_38_49.pdf](https://github.com/gsautter/goldengate-imagine/files/641548/AM52_38_49.pdf)  example on page 47

**Comment by gsautter** [comment]
Now this is _really_ weird ... could you provide me with your decoding logs? Whenever I tested any of the PDFs you reported this before, it worked just like supposed to.

**Comment by gsautter** [comment]
As to the "Cheiracantheidium" vs. "Chiracanthidium" issue, I do see both "C<weirdChar>eiracantheidium" and "C<weirdChar>iracanthidium" in the screen shot, so correcting <weirdChar> to "h" should do.

**Comment by myrmoteras** [comment]
Did you check this PDF? This is not like other PDF
What is the decoding log?

**Comment by myrmoteras** [comment]
as I point out. correcting the h as h solves one, but makes an error: correcting h as he solve the first part of the word (CHEi..), but not the second (..antHEidium which should read  ..antHidium)

**Comment by gsautter** [comment]
Tried again, and I just cannot reproduce it. I do get the mis-decoded weird character, but when I fix it in "Edit Font", it gets corrected in all occurrences, just like supposed to.

The correct transcription for that weird character is "h" and "h" alone, not "he". Note that even the source PDF reads "Ch EI racanthidium" in some instances, and  "Ch I racanthidium" in others. Looks to me as there are simply two concurrent spellings, at least in the reference group.
