### ISSUE TITLE
imf - zenodo doi issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#201]
it seems as most of the extracted  article  DOI links in the zenodo deposit of the articles are broken, see eg https://zenodo.org/record/841808#.WZbTiFJL_ZR 

Related identifiers:
Cites:
BacherS.2012.Stillnotenoughtaxonomists:replytoJoppaetal.TrendsinEcologyandEvolution27:65-66.http://dx.doi.org/10.1016/j.tree.2011.11.003, CostelloM.J.,WilsonS.&Houlding.B.2011.Predictingtotalglobalspeciesrichnessusingratesofspeciesdescriptionandestimatesoftaxonomiceffort.SystematicBiology,firstpublishedonline18Aug.2011http://dx.doi.org/10.1093/sysbio/syr080, 
![image](https://user-images.githubusercontent.com/4609956/29457716-f2165dde-841b-11e7-8c34-250d8242c7d5.png)

If possible, fixing this should be given high priority

**Comment by gsautter** [comment]
First of all, this is definitely _not_ a GGI issue ... let's really have a separate tracker for BLR.

**Comment by gsautter** [comment]
Was a glitch in the exporter, fixed now. The corrections of all the depositions will happen when we add the exact publication date, which I should be able to finish implementing this weekend. The updates might take a while to run, through.
