### ISSUE TITLE
image decoding: error

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#21]
@gsautter Fig 7 in this document has a problem

https://doi.org/10.5281/zenodo.167770
	
![image](https://cloud.githubusercontent.com/assets/4609956/21046895/21f5e672-be07-11e6-91fa-cff3be0bc0c3.png)

http://treatment.plazi.org/id/DE59D352-FFC1-FFA1-FF6B-FCDAFC462671

http://tb.plazi.org/GgServer/summary/2260AB2AFFC6FFABFFCDFF8CFF972501

**Comment by gsautter** [comment]
Hard to tell ... was this decoded on the server? I just ran the PDF through GGI, and got this:
![image](https://cloud.githubusercontent.com/assets/5789714/21051339/1f3b2550-be20-11e6-9b42-9584eda0d502.png)

The image proper, copied right from GGI via "Copy Image" looks like this:
![image](https://cloud.githubusercontent.com/assets/5789714/21051385/4a7a5380-be20-11e6-915e-1b2951c2d752.png)

**Comment by gsautter** [comment]
The very GGI build I put up for download early this morning ...

**Comment by myrmoteras** [comment]
Mit dem hab ich nichts zu tun gehabt. Das ist via den laufenden Zootaxa process entstanden - nehm ich an

**Comment by myrmoteras** [comment]
entschuldige. das hab ich vor ein paar Wochen gemacht - ist ja nicht zootaxa

**Comment by gsautter** [comment]
Might well be a few weeks ago, yes ... we didn't have all those image decoding issues fixed back then. Works now, though. Good test case for double checking if the fixes implemented on and tested with other PDFs also solve the general case, and they apparently do.

**Comment by gsautter** [comment]
Figure repair will take care of this.

**Comment by myrmoteras** [comment]
will this be corrected on BLR? Would be good, since by chance this came up in the office of one of the Museum board members this morning. Otherwise, a perfect demo

**Comment by gsautter** [comment]
Figure repair also makes the correction on Zenodo, yes ... that's what we built it for, remember?
