### ISSUE TITLE
Caption and figureCitation missing zootaxa.4311.3.11

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#210]
in this case the figureCaption and figureCitation have not been markedd up (I added them manually). But now I cannot link them to the caption. Can you  tell me how to do it?

![image](https://user-images.githubusercontent.com/4609956/29650065-9cf76538-8898-11e7-906b-cc4fdebbce7b.png)

**Comment by gsautter** [comment]
Take a look at the caption proper ... there's something missing ... it's kind of hard to link to figures that come without a number, and that caption merely starts with "FIGURES. Chrysacris ...". Just too ambiguous to link automatically. Another case of pathologically sloppy copy editing ...

What I might do in manual linking is simply offer all captions to link to if none at all matches the number in the selected figure citation. Would solve this case for you ...

**Comment by gsautter** [comment]
Having sifted through the code handling manual assignment, what you should be able to do right now is this:
- mark the caption (or leave it if already done)
- remove the figure citation
- select only "Figs 1" (if not possible, use "Split Word" on "I-I" to separate the letters from the dash)
- use "Mark Figure Citation"
- select the caption in the dialog that opens and hit OK

**Comment by gsautter** [comment]
If the latter doesn't work, the IMF would be helpful for testing ... or is this one already on the server? If so, the UUID would be very helpful and highly appreciated.

**Comment by myrmoteras** [comment]
the file name is zootaxa.4311.3.11  and the imf is uploaded
I don't know the UUID since they do not show up on todays news

**Comment by gsautter** [comment]
What I outlined above works out just fine for manually marking a figure citation and linking it to the figure. Guess this one's resolved ... there's just no automated linking to captions that come without a number, as that's just all too ambiguous in the general case.
