### ISSUE TITLE
b&w color inverse:  Bull. Am. Mus Nat hist B415

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#214]
in this Bull Am Nat Hist the color is inverse

![image](https://user-images.githubusercontent.com/4609956/29740830-5241e40e-8a60-11e7-8c6a-311cec8fc214.png)

the file is big so here the handle http://digitallibrary.amnh.org/handle/2246/6723

**Comment by gsautter** [comment]
Is it only this very image, or all the B&W images throughout the PDF?

**Comment by gsautter** [comment]
I just decoded it, and it comes up perfectly fine ...
![image](https://user-images.githubusercontent.com/5789714/29743032-b5eb1b50-8a89-11e7-8082-d38a7f7a33a3.png)

In #213 you mentioned decoding on your laptop ... sure that thing is running the latest version of GGI?

**Comment by myrmoteras** [comment]
What do I have to do to get the same result on my machine? Of can you upload the IMF you decoded and I  pick up and finish it?

In my case, only the maps show up this way, the SEMs etc are ok

**Comment by gsautter** [comment]
In #213 you mention working on your laptop ... could it be you have an older version there? That would explain the different results, as there are some recent fixes in bitmap decoding, especially concerning grayscale images.

However, to get my result, you might just get the latest build, clear the caches, and re-run the PDF, as I only ran the pages with the maps, not the whole PDF. Just not required to test images, as pages are decoded independently. Or I can decode the whole thing for you.

**Comment by myrmoteras** [comment]
I am running this again and let you know adap

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by myrmoteras** [comment]
I run it again, including removing all the cache and page images, and with an updated version on my machine. I am getting all the grayscale inverse.

**Comment by gsautter** [comment]
OK, that's weird ... I'll create the IMF for you.

**Comment by gsautter** [comment]
The IMF is on the server, UUID `735C952FFFCAB1543860CC2CB35C6E75`.

I've corrected the fonts already, will check the decoder on the train tomorrow.

**Comment by StephenWalker23** [comment]
So happy for the great work of Dr Akuna the great herbal healer that has cured me of my 20years HEPATITIS A&B after using his herbal mixture that was sent down to me from Africa within 3 days, i was completely cured i can't believe it that Dr Akuna can cure me of my HEPATITIS A&B Disease after Doctor prove no cure for it, but today i am a free Man and i own you a word of appreciation, and that is why i am writing this to tell the world how powerful you are to the humanity. May God keep blessing you more and more. Dr Akuna is specialis in other kinds of illness: Typhoid Fever, Yellow Fever, Meningitis, Cholera, HIV, Cold Sore,Herpes virus all types, Common Cold and More. Write to his WHAT APP LINE OR CALL HIM:+2348154625070 Or CONTACT HIS EMAIL:DRAKUNASOLUTIONTEMPLE@GMAIL.COM or  his web:https://drakunasolutiontempleofallkindsofsicknessistreated.wordpress.com/2017/12/08/about-me/

**Comment by StephenWalker23** [comment]
So happy for the great work of Dr Akuna the great herbal healer that has cured me of my 20years HEPATITIS A&B after using his herbal mixture that was sent down to me from Africa within 3 days, i was completely cured i can't believe it that Dr Akuna can cure me of my HEPATITIS A&B Disease after Doctor prove no cure for it, but today i am a free Man and i own you a word of appreciation, and that is why i am writing this to tell the world how powerful you are to the humanity. May God keep blessing you more and more. Dr Akuna is specialis in other kinds of illness: Typhoid Fever, Yellow Fever, Meningitis, Cholera, HIV, Cold Sore,Herpes virus all types, Common Cold and More. Write to his WHAT APP LINE OR CALL HIM:+2348154625070 Or CONTACT HIS EMAIL:DRAKUNASOLUTIONTEMPLE@GMAIL.COM or  his web:https://drakunasolutiontempleofallkindsofsicknessistreated.wordpress.com/2017/12/08/about-me/ ...
