### ISSUE TITLE
Zootaxa zootaxa.4315.1.1; plates

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#220]
In this Zootaxa zootaxa.4315.1.1 there are a number of plates at the end, that are not included in the upload.
They are supplementary material, but nevertheless. They also seem not to be linked from the main text. So it would be even more relevant, to link them to the main document on Zenodo.  https://zenodo.org/record/858445

**Comment by gsautter** [comment]
The plates are on Zenodo, it's just that the PDF deposition was lacking the links. Will investigate how this situation could emerge.

**Comment by gsautter** [comment]
A prerequisite for figures to show up on Zenodo is for their captions to be marked ... the captions form the anchors for the upload, act as the description for the deposition, and bear the HTTP URIs.

I marked the captions now, and the upload is in progress.
