### ISSUE TITLE
missing activated figure citations: 7F18FF91FF8AFFC3FFE36200FFC9FFA3 zootaxa.4313.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#222]
in this today processed monograph, the links to the figures cited are missing

http://tb.plazi.org/GgServer/html/832187E9FF38FF76FF7467E4FE11FC07

http://tb.plazi.org/GgServer/summary/7F18FF91FF8AFFC3FFE36200FFC9FFA3

Most of the figures also seem to be missing on BLR, see eg https://zenodo.org/communities/biosyslit/search?page=1&size=20&q=Brueelia%20aguilarae#

**Comment by gsautter** [comment]
Looks like the upload had failed for some reason ... I just re-triggered it.
