### ISSUE TITLE
figs not linked: zootaxa.4316.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#223]
FF90FF90FFB0FFFEFF82DB64FFA8FFBC 

![image](https://user-images.githubusercontent.com/4609956/29997117-59e7fd8c-900b-11e7-981a-103784d5e38c.png)

in this Zootaxa, the figs are not linked

**Comment by gsautter** [comment]
Looks like the figures just weren't uploaded ... if you go for "Downloads -> Plain XML", you can see whether or not the `figureCitation`s are tagged, and not linked merely for lack of an `httpUri` attribute. Like in this case.

In that latter circumstance (only lacking HTTP URIs), the markup proper works just fine, only the uploader fails to put the images on Zenodo and the links into the document, making this rather a BLR issue.

Anyway, I've re-triggered the upload via the admin console, so matter fixed.
