### ISSUE TITLE
pdf does not open: LoÂpez-Guerrero etal 2017

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#226]
[LoÂpez-Guerrero etal 2017.pdf](https://github.com/gsautter/goldengate-imagine/files/1281017/LoApez-Guerrero.etal.2017.pdf)
[GgImagine.20170906-1140.err.zip](https://github.com/gsautter/goldengate-imagine/files/1281021/GgImagine.20170906-1140.err.zip)

**Comment by gsautter** [comment]
Thanks for the logs - this looks a lot like an encoding problem to me, one that strikes while decoding the PostScript portions of some Type1 font. Will investigate.

**Comment by gsautter** [comment]
Thanks for this PDF ... was he first case of somewhat off-default (if in-standard) Type1 fonts. And the off-default part incurred some error in the PostScript interpreter as it was reading into the padding optionally following the "end of font data" marker.
Just good to get across such examples, as they (and only they) facilitate gradually enhancing our PDF decoding facilities.

The underlying problem of the error at hand is fixed now, comes with the next build.
