### ISSUE TITLE
bibliographic references tagger not working well 4A4A441EFF91026DFFA5FFA38058FFCC

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#229]
in this case, many bibliographic references are not found 

![image](https://user-images.githubusercontent.com/4609956/30114805-32d3c2f6-9319-11e7-9f5b-3c31de595a0e.png)

**Comment by gsautter** [comment]
This isn't exactly a case of actual references not being found.

This dialog offers everything that might be a bibliographic citation (in the sense that there is a matching entry in the bibliography), and that category also includes taxon name authorities that come with author and year.
If the tagger cannot find any bibliography entry that matches both author name and year, in interactive (as opposed to batch) mode, it doesn't simply filter out all those potential citations, but offers them to you for manual assignment. In the very most cases of `not a citation`, there actually is no corresponding entry in the bibliography, so this is not really an assignment error.
This dialog is simply covering all the bases as there theoretically might be misses, even though they are extremely rare in practice.
