### ISSUE TITLE
figCitation

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#23]
@gsautter this is the last for today: Can you give me a hand to add the figCitation and make them work, so the nice sea dragons show up? or how can I do it myself
thanks

http://tb.plazi.org/GgServer/summary/FFFD9846FFBCFFEA8C58A2781854FFC6

**Comment by gsautter** [comment]
First and foremost, by pointing me to the PDF on Zenodo rather than the summary on TB for each issue ... I always have to take some 5 steps to get my hands on the PDF and test things.

**Comment by gsautter** [comment]
From the XML it looks like this one is simply due to bad English ... it cites "figure X" instead of "Figure X" (mind the title case).

**Comment by myrmoteras** [comment]
I would like to either make those links yourself, or tell me how I can make it myself so that the link to BLR will show up in the figureCitation. The annotation of the figureCitation is the problem

**Comment by gsautter** [comment]
PDF is decoding as I type this, need to check what I advise you.

**Comment by myrmoteras** [comment]
Why decode the PDF? All the markup including loading of the figures to BLR is already done.

**Comment by gsautter** [comment]
Seen the dotted horizontal lines in the tables? Those things are made up of small-scale "..." _characters_ !!! Shaking head in disbelief ...

**Comment by gsautter** [comment]
Got it ... have a little hen and egg problem in the plug-in providing the "Mark Figure Citation" functionality. I'll fix it right away.

**Comment by myrmoteras** [comment]
at least, this is rewarding, these strange pip fishes

**Comment by gsautter** [comment]
Sure ... the layout is a b***h, though ... what kind of a journal is this? Makes Zootaxa look like child's play to mark, and even the latter doesn't cease to surprise with oddities.

**Comment by myrmoteras** [comment]
will you add the figCitation to this and upload, so I can use it?

**Comment by gsautter** [comment]
It's really not as easy, as going only for title case figure citations in "normal" documents has advantages in both precision and speed ... still trying to figure out how to catch these lower case figure citations here and not deteriorate general performance ... always a tightrope.

**Comment by myrmoteras** [comment]
but what about not solve the world's problem now, but just tell me how to fix this manually, or if you can fix it in this case, and rather have a drink or too tonight?
I like to have a tool set to fix such issues ad hoc. There will always be things that are not right.

So, imagine me as the guy in the garage fixing a car, not building the car....

**Comment by gsautter** [comment]
Fixed it, finally ... the thing now goes case insensitive if it doesn't find any figure citations in case sensitive mode. Still fast in the usual case of "Figure X", but can also handle "figure X" now.
Also, you have a new function on captions: "Mark Citations". To have this function available, make sure `caption` annotations are showing, and then just click on the caption of the figure you want to mark citations for.
The difference to "Mark Figure Citation" in the text is that the latter marks exactly that one figure citation, while the former marks _all_ citations of the figure whose caption you clicked on.
I'm also considering adding a "Mark Figure & Table Citations" entry to the "Tools" menu. What do you think?

Doing figure citations manually is always critical, as the attributes have to be correct, and they are quite a hassle to put in via the "Edit Attributes" dialog.

**Comment by myrmoteras** [comment]
Is it fixed in the doc, or should I know be able to fix it?


Sent from Samsung Mobile.


-------- Original message --------
From: gsautter
Date:10/12/2016 21:51 (GMT+01:00)
To: gsautter/goldengate-imagine
Cc: Donat Agosti , Author
Subject: Re: [gsautter/goldengate-imagine] figCitation (#23)


Fixed it, finally ... the thing now goes case insensitive if it doesn't find any figure citations in case sensitive mode. Still fast in the usual case of "Figure X", but can also handle "figure X" now.
Also, you have a new function on captions: "Mark Citations". To have this function available, make sure caption annotations are showing, and then just click on the caption of the figure you want to mark citations for.
The difference to "Mark Figure Citation" in the text is that the latter marks exactly that one figure citation, while the former marks all citations of the figure whose caption you clicked on.
I'm also considering adding a "Mark Figure & Table Citations" entry to the "Tools" menu. What do you think?

Doing figure citations manually is always critical, as the attributes have to be correct, and they are quite a hassle to put in via the "Edit Attributes" dialog.

-

**Comment by gsautter** [comment]
Now you should be able to fix it ... just highlight the captions, click on them, and use "Mark Citations of Figure".

**Comment by myrmoteras** [comment]
@gsautter I need your help in getting  the images of this journals into BLR and then marked up in the doc.
http://tb.plazi.org/GgServer/summary/30437113946AFF91825DFF8D9E42FFE8


![image](https://cloud.githubusercontent.com/assets/4609956/22647633/f562205e-ec72-11e6-9579-154bc941417f.png)

1. GGI does not find (fig. 2). I marked it up as figureCitation manually
2. Figure 2 has been broken in two words F igure. I fixed this
3. I then used "mark Figure" but nothing happened.

**Comment by gsautter** [comment]
I guess merging "F" and "igure" into "Figure" and then marking the caption should have done the trick with that figure citation as well ... we fixed the lower case issue a few builds back.

If the caption doesn't have the attributes `targetBox` and `targetPageId`, click on the figure, choose "Assign Caption", and then click on any work in the caption proper. That should create said two attributes.

**Comment by gsautter** [comment]
Regarding BLR, it could be we're currently only uploading embedded figures, not cut-outs of scanned page images. Will check ...

**Comment by myrmoteras** [comment]
ok - I wait until you tell me whether you include also cut-outs, which would be all the figure in this entire journal

**Comment by gsautter** [comment]
Looks like all these figures are up on BLR now, and the split-word issue has moved on to more recent tickets ...
