### ISSUE TITLE
image conversion inverted: 5C64FF86CA11FFCF7B09FFAFD8704048

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#237]
![image](https://user-images.githubusercontent.com/4609956/30159227-3224e6dc-93c8-11e7-91e3-2056b31f5c36.png)

[systEnt.42.837-846.pdf](https://github.com/gsautter/goldengate-imagine/files/1284352/systEnt.42.837-846.pdf)
![image](https://user-images.githubusercontent.com/4609956/30159317-7a120c22-93c8-11e7-8411-156285496175.png)

![image](https://user-images.githubusercontent.com/4609956/30159455-eca19bea-93c8-11e7-9d59-3b341c30f94a.png)

also Fig 3 has not been recognized as figure and the figure captions have been tagged as text, and do now show up in BLR https://zenodo.org/record/887101#.WbEp2aiCzAQ

![image](https://user-images.githubusercontent.com/4609956/30160874-b4795af4-93ce-11e7-91ce-ce727e1ca70c.png)

**Comment by gsautter** [comment]
Regarding the inverted figures: Figure 5 is so dark in the original that it might well be inverted right there , as is Figure 7 ... I'll try and adjust the "inverted image correction" threshold to avoid these false positives.

Regarding the labels in Figure 3, I'll check.

**Comment by gsautter** [comment]
In Figure 3, the text labels come up just fine for me ... it's just that the "A" is outside the figure boundaries ... hard one to get right, I'm afraid.

**Comment by gsautter** [comment]
Figures 5 and 7 look like a color space issue ... will investigate.

**Comment by gsautter** [comment]
Fixed figures 5 and 7. Comes with the next build.
