### ISSUE TITLE
taxonomicNameLabel: new value: candollea.c2017v721a6: 43551658FF88FF9EFF8E1364215DFFF6	

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#239]
can you add this new value for sp. n.: spec. nova 

![image](https://user-images.githubusercontent.com/4609956/30246348-a53622b8-95f7-11e7-8c5a-ade06fa57b61.png)

**Comment by gsautter** [comment]
Done, comes with the next build.
