### ISSUE TITLE
Font issue: can't change these letters candollea.c2017v721a6:  43551658FF88FF9EFF8E1364215DFFF6	

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#240]
I can't fix Mologosy to Malagasy and CandollEa to Candollea

![image](https://user-images.githubusercontent.com/4609956/30246353-d62f6352-95f7-11e7-98d8-33c82d504914.png)

BTW: there are many strange fonts here that I had to change

[candollea.c2017v721a6.pdf](https://github.com/gsautter/goldengate-imagine/files/1290283/candollea.c2017v721a6.pdf)

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/30246406-9356689e-95f9-11e7-86fc-d241787c47fd.png)

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/30246515-b13cc634-95fc-11e7-965e-d5e8f79daad8.png)

two degrees

**Comment by gsautter** [comment]
Please try decoding this PDF with "<Render Glyphs Only>". This option basically tells the decoder to use the Unicode mapping as is, and only render the glyphs for inspection.

Above option should actually be the starting point when you decode any PDF, as most come with a faithful Unicode mapping. Only if you see the fonts are obfuscated, you should switch to actually decoding them against some character set (most likely Latin).

Only rendering the glyphs also speeds up the overall decoding process quite a bit, as the font decoding part is quite some effort.

**Comment by gsautter** [comment]
Apart from that, you're right that the page title font comes up incomplete in the font editor. I'll check why that happens. Looks like one for the train ride tonight.

**Comment by myrmoteras** [comment]
Does this mean, that I cannot drag and drop the files as I use to do to start the conversion?!

**Comment by gsautter** [comment]
Well, drag & drop obviously doesn't offer the options you have in the "File -> Open" dialog.

I could well change the default (which is used on drag & drop) to "<Render Glyphs Only>", however.

**Comment by myrmoteras** [comment]
sorry, what do the "" mean? There isn't such an option

decoding this PDF with "". 

![image](https://user-images.githubusercontent.com/4609956/30250636-350cd576-9652-11e7-9ccd-cb7f764ea560.png)

**Comment by gsautter** [comment]
Sorry ... looks like markdown doesn't like angle brackets all too much. Meant "&lt;Render Glyphs Only&gt;"

**Comment by gsautter** [comment]
The problem that some characters cannot be changed in "Edit Embedded Fonts" has been resolved with yesterday's build. It resulted from multiple fonts deriving from the same font face and using the name of the latter. Such collisions are resolved in the last build, so now each and every character is up for correction.
