### ISSUE TITLE
geoCoordinate: does not calculate decimal degree: 43551658FF88FF9EFF8E1364215DFFF6	

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#241]
![image](https://user-images.githubusercontent.com/4609956/30246548-c820b65c-95fd-11e7-8caf-8642a2fd5a7e.png)

**Comment by gsautter** [comment]
Well, the coordinates are not tagged at all for what I see in the screenshot.

This basically means the patterns identifying geo-coordinates fail for some reason, most likely the punctuation marks between the numbers. Will check.

**Comment by gsautter** [comment]
If you tag the coordinates manually, the Analyzer that usually does the tagging and also the signed decimal conversion of course doesn't kick in.

Would be a major requirement to GGI in general to add some automated parsing after manual tagging. Sure worthwhile considering, but a good bit of effort to implement.

**Comment by gsautter** [comment]
After some investigation, I can say it definitely is the high comma marking minutes and seconds of arch that gets in the way ... another one to consider in the patterns. Comes with the next build.
