### ISSUE TITLE
Font issue: wrong letters that can't be changed candollea.c2017v721a12.pdf FF95FF956D5AFF9EFF9EE6642008FFBA

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#243]
[Candollea is the journal from the Bot Garden Geneva that I will visit coming Thursday to discuss [
collaborations.]

These letters can't be changed. I imported this 

[candollea.c2017v721a12.pdf](https://github.com/gsautter/goldengate-imagine/files/1290784/candollea.c2017v721a12.pdf)

![image](https://user-images.githubusercontent.com/4609956/30251656-6817c932-9664-11e7-9dfc-220be16e3b2b.png)

![image](https://user-images.githubusercontent.com/4609956/30251660-76e25e32-9664-11e7-85bb-41c1cde56beb.png)

![image](https://user-images.githubusercontent.com/4609956/30251667-b2b0a9c8-9664-11e7-9c6d-b4f6f7adc649.png)

![image](https://user-images.githubusercontent.com/4609956/30251667-b2b0a9c8-9664-11e7-9c6d-b4f6f7adc649.png)

See next #244 imported without decoding works better, but entirely perfect

**Comment by gsautter** [comment]
I meant "render glyphs only" in #242 ... sorry the angle brackets got in the way.

Figuring out why certain characters are missing even though they are used is my todo for this night on the train.

**Comment by gsautter** [comment]
Found it ... a really odd problem, with fonts used in a legal but somewhat counter intuitive way.
