### ISSUE TITLE
wrong letters: opend with "no decoding"  candollea.c2017v721a12.pdf  FF95FF956D5AFF9EFF9EE6642008FFBA

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#244]
![image](https://user-images.githubusercontent.com/4609956/30252073-6317229a-966c-11e7-9efe-215398ae78e4.png)

![image](https://user-images.githubusercontent.com/4609956/30252099-9363d858-966c-11e7-93ce-2cd70f81750f.png)

**Comment by gsautter** [comment]
"no decoding" naturally waives all checks on the rendered characters, so as it doesn't render them in the first place. That also disables checks for small-caps, etc. "render glyphs only" usually is the better option.
