### ISSUE TITLE
font issue, missing letters candollea.c2017v721a2 FFC4B60A12463D77FFDEFF2CFFFED30D

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#245]
in this case, there are font issues, as well as missing letters. 
This doc has been processed Render Glyphs Only"

![image](https://user-images.githubusercontent.com/4609956/30252961-e28b998e-967b-11e7-8999-f20d1bd2a4e9.png)

![image](https://user-images.githubusercontent.com/4609956/30252970-04691ff4-967c-11e7-8c03-df9fefd15d50.png)

[candollea.c2017v721a2.pdf](https://github.com/gsautter/goldengate-imagine/files/1290929/candollea.c2017v721a2.pdf)

**Comment by gsautter** [comment]
The missing letters are a new thing ... however, I could not reproduce this error in the latest state of the code.

As to the small-caps, they actually Unicode-map to lower case letters. However, the new build should get them right, as I've made some improvements in that department.
