### ISSUE TITLE
missing figures in BLR: FF95FF956D5AFF9EFF9EE6642008FFBA

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#246]
from this document, the first three figures are missing in BLR. 

https://zenodo.org/record/888344#.WbWojKhL_AQ

**Comment by gsautter** [comment]
In this case, the captions were not assigned to the figures, so the Zenodo uploader has preciously little of a chance here:
![image](https://user-images.githubusercontent.com/5789714/30253920-3ea6c9a6-968f-11e7-9b9a-41b6e7401ac0.png)
Please check the caption attributes and assign the figure to the caption first thing if a figure doesn't show on Zenodo. I do nothing else, either.

Also, please use "Mark Caption" to mark captions, not "Annotate -> caption", as the latter only creates the annotation proper, whereas the former also takes care of text stream flow, etc. Guess I showed you said function at some point ...
