### ISSUE TITLE
bibRef parsing limit exceeded EJT-283_Philippe

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#249]
this reference with this many authors cannot be parsed

![image](https://user-images.githubusercontent.com/4609956/30330247-ce68e574-97d4-11e7-823d-0d1e987a3cfd.png)

**Comment by gsautter** [comment]
Another case of a combinatorical explosion, I'm afraid, even though in a place I might have foreseen it. I'll include this one as a test case in the previously announced RefParse overhaul.

**Comment by gsautter** [comment]
An IMF UUID would help a great deal with testing. Or at least a direct download link for the source PDF.

**Comment by myrmoteras** [comment]
this is the first in all the years. I only know two other papers in my field that has as many authors. The problem will come up once we start to get into physics...

**Comment by myrmoteras** [comment]
all these EJT pdfs are from our test body and Terry specifically built this github for it: https://github.com/plazi/EJT-testbed

**Comment by gsautter** [comment]
Ah, OK, thanks for the link.

Anyway, as stated above, I'd try and prevent such combinatorical explosions in the RefParse overhaul.

I figured out how to do this a good while ago, as we've had the same problem in FAT when the tagger for potential authorities ran into longish lists of person names, like the ones quite frequently found in acknowledgements ... solved there, and the same approach will come to bear in RefParse.

**Comment by gsautter** [comment]
Implemented, comes with a new build soon as RefParse overhaul is complete.
