### ISSUE TITLE
figure not properly extracted

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#25]
@gsautter here is a svg that has not properly converted

https://zenodo.org/record/168630/files/figure.svg

![image](https://cloud.githubusercontent.com/assets/4609956/21096804/a0af1a18-c061-11e6-9ffb-a0010080528d.png)

**Comment by gsautter** [comment]
Small wonder, that's a 2002 Zootaxa, converted way before we even considered taking a stab at the graphics. And if this one didn't have any scrambled images, Figure Repair didn't kick in, either, as it's aimed at the images only ... will see what I can do about this kind of trouble.

**Comment by myrmoteras** [comment]
before you do something, put this then aside as todo once we have a better overview what is else missing, needed to fix

**Comment by gsautter** [comment]
OK, looking into the seahorse figures now. Could be the fix (or better: repair mechanism) is one and the same, though ...

**Comment by gsautter** [comment]
I tend to think this one should be fixed with any of the current updates,

PS: what does this very problem have to do with GGI at all
