### ISSUE TITLE
Zootaxa: Batch processing failure

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#251]
Todays barch processing did not work, because all the files had invalid Document Metadata. Specifically, the publication type has been set to "Book / Thesis / Monograph" and the Pub Date has been in the wrong format

![image](https://user-images.githubusercontent.com/4609956/30363756-b1e317c0-9861-11e7-87cf-b1b9c8553ba8.png)
[zootaxa.4319.3.4.pdf](https://github.com/gsautter/goldengate-imagine/files/1298485/zootaxa.4319.3.4.pdf)
[zootaxa.4319.3.7.pdf](https://github.com/gsautter/goldengate-imagine/files/1298486/zootaxa.4319.3.7.pdf)
[zootaxa.4319.3.9.pdf](https://github.com/gsautter/goldengate-imagine/files/1298488/zootaxa.4319.3.9.pdf)

**Comment by gsautter** [comment]
The publication date actually should be parsed any normalized to the required `YYYY-MM-DD` format ... I integrated that a good while ago. Hard to tell why it didn't work with these PDFs ... will check.

**Comment by gsautter** [comment]
Looks like a style template selection problem as the root cause ... small wonder a whole series of documents didn't work out under that kind of circumstances.

Parsing the publication date is a different issue, if most likely related ... will investigate.

**Comment by gsautter** [comment]
Figured it out ... the code parsing the date only took "Sep" for "September" thus far, but not "Sept" ... added it, comes with the next build.

The mistaken publication type is a downstream result of the latter, as the syntactically wrong publication date prevents a full match to any publication type, which in turn ends up with the default being selected.

**Comment by myrmoteras** [comment]
@gsautter it works now.
