### ISSUE TITLE
GGI does not open a document

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#258]
This is a test document from a journal created at the Uni Bern for which they want to create XML. It does not open at all in GGI.

tested drag and drop, glyphs

[3533-13278-1-PB.pdf](https://github.com/gsautter/goldengate-imagine/files/1313768/3533-13278-1-PB.pdf)
[GgImagine.20170919-1149.out.zip](https://github.com/gsautter/goldengate-imagine/files/1313769/GgImagine.20170919-1149.out.zip)

**Comment by gsautter** [comment]
Reproduced ... will investigate.

**Comment by gsautter** [comment]
This is an interesting one ... first encounter with pages using default color spaces ... yet another twisted feature to observe.

**Comment by gsautter** [comment]
Solved. Just the first-ever use of a standard default feature I never realized wasn't implemented yet ... comes with the next build.

**Comment by myrmoteras** [comment]
still not in the new build- can you get me the new build so I can demo this to Uni Bern?
