### ISSUE TITLE
scambled image

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#26]
@gsautter here a scrambled image recentyl posted
https://zenodo.org/record/158447#.WFF2_1orK0o

https://zenodo.org/record/169104#.WFF3llorK0p

https://zenodo.org/record/169106#.WFF5CVorK0o

**Comment by gsautter** [comment]
If you take a look at the treatments citing those figures, you'll see that they were all uploaded April 19th, 2016, and the PDFs converted before that, in extrapolation.

It's the time of conversion that really makes the difference here, not when the figures went on Zenodo. Back in April, yes, certain figures were still being scrambled. But Figure Repair will take care of that soon as the respective PDFs come up in the queue.

**Comment by myrmoteras** [comment]
what is the cutoff date after which bad images need attention?

**Comment by gsautter** [comment]
Hard to tell ... there have been many minor improvements over time, not at last full color space handling, which was added only in early November. Figure Repair will handle it.

If there is any cutoff date, I'd tend to say everything _decoded_ after Nov 30th, 2016 needs inspection, everything before that should be handled by Figure Repair.
Only once Figure Repair is through, anything remaining will become worthwhile reporting as well, if with the question why Figure Repair didn't kick in or failed to fix it.
