### ISSUE TITLE
image conversion inverse: EJT-321_Maxwell, EJT-322_Lin

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#260]
in this image, the color are inverse
[image](https://user-images.githubusercontent.com/4609956/30602016-a6af9e9e-9d63-11e7-91ca-f7379a97e820.png)

[EJT-321_Maxwell.pdf](https://github.com/gsautter/goldengate-imagine/files/1314887/EJT-321_Maxwell.pdf)

and here another one
![image](https://user-images.githubusercontent.com/4609956/30602228-46bfef24-9d64-11e7-9919-c02000b99053.png)
[EJT-322_Lin.pdf](https://github.com/gsautter/goldengate-imagine/files/1314910/EJT-322_Lin.pdf)

**Comment by gsautter** [comment]
Yet another color space combination that requires additional parameters on decoding ... fixed it, comes with the next build.
