### ISSUE TITLE
font issue: Bug

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#261]
recently, we are getting regularly miscoded texts with a mixture of capital and lower case letters. 

![image](https://user-images.githubusercontent.com/4609956/30819170-307e31b2-a21e-11e7-9978-6e6ae2892216.png)

http://tb.plazi.org/GgServer/html/0383962D5D73D66161D99239FBB04D70

**Comment by gsautter** [comment]
Sorry to say, but just like all the other case mixup issues you've reported thus far, I just cannot seem to reproduce this one:
![image](https://user-images.githubusercontent.com/5789714/30823860-f1c2c9dc-a22d-11e7-8d2c-ac20e9df8c4c.png)

Have you tried running it with "Render Glyphs Only"? Does the result remain the same?

**Comment by myrmoteras** [comment]
These are done with the batch mode this morning. Ggi should be as up to date as it cans

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gsautter** [comment]
Ultimately, this is a duplicate of #256. Let's stick with one ticket per issue, please. No use distributing analysis and solution attempts, only makes it harder to follow later on.
