### ISSUE TITLE
genus not found: what does GGI do?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#266]
what happens in a case that GGI does not find a genus in the lookup?
![image](https://user-images.githubusercontent.com/4609956/30954154-6d4c01a6-a42f-11e7-9509-dd59b30f7b61.png)

eg http://treatment.plazi.org/id/038F2526FFEA7D22899FFA08072DE0A4

**Comment by gsautter** [comment]
If the genus is labeled as "gen. nov." or similar, it will still be recognized. The same applies if it is part of a "spec. nov." labeled binomial. And all that only applies if the font style fits, which means the genus has to be in italics if all the catalog verified genera are.

Bottom line: No worries, FAT can very well handle most of these cases. It's designed to do so.
