### ISSUE TITLE
abbyy document import problem

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#268]
https://drive.google.com/drive/folders/0B6bzTXSXEgR-azNfd005QlJlM1k 
here is an issue with a ABBYY OCR-ed BHL document.  The original document is ...BHL, the ABBYY doc is cope1892.pdf

It seems that the image in the PDF is declared far too big. It is not possible the get this document properly converted into GGI, even though the document has been produced the same way with OCR underlying the image.
Do you have an idea how this could be solved? What are the next steps to consider? Is there a way to fix the definition of the image size in the PDF generated by BHL?

**Comment by gsautter** [comment]
Most likely you downloaded this document as an excerpt from the BHL website, right? They've been having this issue of messing up page dimensions on excerpt creation for a long while, basically dropping the resolution to the default 72 DPI, and overblowing page dimensions accordingly.

What you can do to solve this is download the whole PDF from BHL, which then has the correct page bounding boxes, and create the excerpt locally with your Acrobat.
