### ISSUE TITLE
rotated table decoding bug  zootaxa.4325.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#269]
[zootaxa.4325.1.1.pdf](https://github.com/gsautter/goldengate-imagine/files/1343017/zootaxa.4325.1.1.pdf)

In this publication there are rotated tables that do not decode properly, eg p 41

![image](https://user-images.githubusercontent.com/4609956/30999858-fc251770-a4d7-11e7-8a04-725bc05ce592.png)

![image](https://user-images.githubusercontent.com/4609956/30999875-141a3090-a4d8-11e7-8d4c-ccfaff242d19.png)

**Comment by gsautter** [comment]
Table rotation proper works just fine on this one ...

However, I was able to reproduce the problem, and it's in the non-italics font used throughout the table. If you try the copy & paste test from Acrobat to Notepad++ (or any text editor), you'll see that the non-italics fonts just copy to garbage.

This is one of the cases where "Render Glyphs Only" does _not_ cut it and you need to use actual font decoding. "Latin" did the trick for me.
