### ISSUE TITLE
upload warning

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#27]
@gsautter here is a 250page ms following... that no got processed

Zootaxa 2456: 1–243 (2010)
www.mapress.com/zootaxa/ Monograph
ZOOTAXA
Review of Gonatocerus (Hymenoptera: Mymaridae) in the
Neotropical region, with description of eleven new species

**Comment by myrmoteras** [comment]
ok - this does not upload
![image](https://cloud.githubusercontent.com/assets/4609956/21226883/d3f88940-c2d7-11e6-88d0-6ceb2c5da7a6.png)


what do I have to do?

**Comment by gsautter** [comment]
Try again now, I just restarted Jetty and paused Figure Repair to free up some resources.

**Comment by myrmoteras** [comment]
![image](https://cloud.githubusercontent.com/assets/4609956/21227066/9f1ebb76-c2d8-11e6-954c-334fbebb4115.png)

restart again

**Comment by gsautter** [comment]
I do see a update coming in in the console ...

**Comment by myrmoteras** [comment]
but the source file doesn't make it.

**Comment by gsautter** [comment]
Not sure that is on the server end of things, though, as I see nothing like it in the console ...

I suggest you store the IMF, best to an "Image Markup Directory" as that is easiest on your local resources, close and re-open GGI, re-open the document, and then try and upload again.

**Comment by myrmoteras** [comment]
![image](https://cloud.githubusercontent.com/assets/4609956/21228520/5d7f2cd6-c2de-11e6-8a8a-9f7fad160d41.png)

**Comment by myrmoteras** [comment]
using the image markup directory leads to the same result

![image](https://cloud.githubusercontent.com/assets/4609956/21228572/9facadf4-c2de-11e6-98c2-c6130b6df13d.png)

 - graphics@95.[150,1436,2078,2079].json
 - graphics@96.[150,1436,2078,2079].json
 - graphics@97.[150,1436,2078,2079].json
 - graphics@98.[150,1436,2078,2079].json
 - graphics@98.[288,407,1709,1710].json
 - graphics@99.[150,1436,2078,2079].json
 - graphics@99.[408,476,373,374].json
 - source.pdf
Auto-Closing InputStream for 'Plugins/ImsDocumentIOData/cache/663432361/D720FFDA046FFFFDFFF5B267FFDCFF98/source.D720FFDA046FFFFDFFF5B267FFDCFF98.pdf'
java.lang.OutOfMemoryError: Java heap space
GoldenGATE exiting with status 1
 - documents closed
 - plugins shut down
 - help closed
 - settings stored
 - instance disposed
 - status set
GoldenGATE exiting with status 1
 - documents closed
 - plugins shut down
 - help closed
 - settings stored
 - instance disposed
 - status set
......................................
Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Exception in thread "LoaderThread" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.substring(Unknown Source)
	at java.lang.String.subSequence(Unknown Source)
	at java.util.regex.Pattern.split(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at java.lang.String.split(Unknown Source)
	at de.uka.ipd.idaho.im.util.ImDocumentIO.setAttributes(ImDocumentIO.java:1471)
	at de.uka.ipd.idaho.im.util.ImDocumentIO.loadDocument(ImDocumentIO.java:598)
	at de.uka.ipd.idaho.im.util.ImDocumentIO.loadDocument(ImDocumentIO.java:342)
	at de.uka.ipd.idaho.im.imagine.application.GoldenGateImagineUI$45.run(GoldenGateImagineUI.java:1692)

**Comment by gsautter** [comment]
See #28 ... I suspect this is a local memory issue rather than a server side one. Does increasing maximum RAM on your end change things?

**Comment by myrmoteras** [comment]
Ok - normally I assign 10GB - but since I have not adjusted this when I downloaded a new version, it is ca 1GB. Let's see what's happening. I have been astonished for the sluggish behavior... now it is back on 10GB at least it now doesn't stop... but using 97%CPU for several minutes to get from 77% to 78%

**Comment by gsautter** [comment]
There's just shy of half a million words in this one, so adding the words to the document, loading all those attributes, and chaining this extremely long text stream does take a little while ... just a monstrous document this.

**Comment by myrmoteras** [comment]
so it run through, but now there  is nothing to see anymore. and the GGI window, blank as it is , is frozen

**Comment by gsautter** [comment]
As long as your CPU load stays up, that means there is something going on ... however, _displaying_ these 500+ pages is a pretty steep call as well. I guess once the first page shows, the last thing you should do is scroll or zoom around.

**Comment by myrmoteras** [comment]
moving around is not the problem. But to edit it, that is to use the tool "treatment structure" takes a long time to open - I let it run to see.

**Comment by myrmoteras** [comment]
how do I know, that something is still ongoing waiting for?
![image](https://cloud.githubusercontent.com/assets/4609956/21233221/b4e3501e-c2ee-11e6-929d-1e35179d3921.png)

**Comment by gsautter** [comment]
Well, running analysis logic takes wrapping the document as XML in most cases (exceptions being "Detect Document Structure" and "<XYZ> Document Metadata"), and creating that wrapper does take some time as well, as it involves running all along the text streams, the longest of which is nearly half a million words long in this document ...

Bottom line: as long as there is CPU load, there's something going on. Something that might be taking fractions of a second in a normal article, but is just a lot more effort in such a huge monograph.

**Comment by myrmoteras** [comment]
the treatments is a genus level, but not at species level.

it took ca 10 minutes to open the treatmentstructure dialogue window, but is is open now..

**Comment by gsautter** [comment]
Squeezing half a million words into that XML wrapper, likely along with tens of thousands of annotations, just does take a while ... complicated enough to represent a page and text stream based document to an Analyzer as the very XML it is used to, with write-through capability on top (that wrapper alone took me a few weeks to build and get right), but doing so for a document this size is yet a different issue altogether.

**Comment by myrmoteras** [comment]
the heading does not work, since it is not marked up - would have needed a fourth level...

![image](https://cloud.githubusercontent.com/assets/4609956/21233904/42b6cc70-c2f1-11e6-8a37-31207c8fbc9d.png)

But this document we need to get done - too much of relevant information inside, such as host plants, treatment citation, distribution data...

![image](https://cloud.githubusercontent.com/assets/4609956/21233945/6013acca-c2f1-11e6-8a3e-28d8ff5b67c6.png)

I guess I need a day or so to get it done.

**Comment by gsautter** [comment]
For documents like this, it might be worthwhile to provide a custom treatment heading selection step ... working on properties like (short) paragraph length and an (at least at the start) bold taxonomic name occupying at least the majority of it ... what do you think?

If treatments are numbered, we have that now, with an additional check on both sequential numbering and numbering sequence completeness as the safety nets that make it applicable in batch processing. But without the numbering, there's just very little to go at, as taxon names in bold alone are just not distinctive enough to work reliably in the general case. However, it would be quite possible to create a treatment heading tagger based upon exactly that and provide it at user's disposal for cases in which a user decides such rules are applicable. What do you think?

**Comment by gsautter** [comment]
I guess this one has been lingering for all too long for a ticket about a very specific (and peculiar) document ... time to lay it to rest.
