### ISSUE TITLE
image decoding bug

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#270]
just came across this and tested out, but did not work. 

Not important right now, but an example to keep in mind.

[hydrobiologia_A_1021297304421.pdf](https://github.com/gsautter/goldengate-imagine/files/1343043/hydrobiologia_A_1021297304421.pdf)

![image](https://user-images.githubusercontent.com/4609956/31000310-f19d2664-a4da-11e7-8ec2-09b57684d913.png)

![image](https://user-images.githubusercontent.com/4609956/31000313-feedcba2-a4da-11e7-94f7-3c06e89a76c4.png)

**Comment by gsautter** [comment]
I'll take a look, that's a good one for the train home tonight.

**Comment by gsautter** [comment]
This is a really nasty one ... the image comes in hundreds of horizontal stripes that are just rendered together. Try copying it in Acrobat and you'll see what I mean ...

I'll try and fix assembly of the overall image.

**Comment by gsautter** [comment]
Also detected a bug in the decoder for a specific type of image compression, fixing it now.

**Comment by gsautter** [comment]
Fixed it, comes with next build.
