### ISSUE TITLE
file does not open: 2002_LonginoCoddingtonColwell

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#272]
2002_LonginoCoddingtonColwell
[2002_LonginoCoddingtonColwell.pdf](https://github.com/gsautter/goldengate-imagine/files/1347214/2002_LonginoCoddingtonColwell.pdf)
[GgImagine.20171001-1651.err.zip](https://github.com/gsautter/goldengate-imagine/files/1347215/GgImagine.20171001-1651.err.zip)

**Comment by gsautter** [comment]
Due to an exactly identical error as in #271, I'm closing this one as a duplicate, event though I'll retain both documents as test cases. Basically because whatever fix I find for #271 will also fix this one.
