### ISSUE TITLE
figure broken

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#273]
![image](https://user-images.githubusercontent.com/4609956/31056137-5a12e6d6-a6cd-11e7-9850-fd4ac6597da9.png)

![image](https://user-images.githubusercontent.com/4609956/31056140-6811f556-a6cd-11e7-8685-c4121e360a14.png)

[EJE_eje-201202-0009.pdf](https://github.com/gsautter/goldengate-imagine/files/1347250/EJE_eje-201202-0009.pdf)

**Comment by gsautter** [comment]
Already fixed, very same issue as in #270. Fix comes with the next build, but before making that, I want to take care of the font issues (#271 and #272) as well.
