### ISSUE TITLE
ORCID: origin FFDBFFC4461B2E06DC3E635F7120FE01

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#275]
@gsautter any idea from where these ORCID originate?
![image](https://user-images.githubusercontent.com/4609956/31124470-427ff7bc-a84d-11e7-920e-867268f69734.png)

https://zenodo.org/deposit/1001646

FFDBFFC4461B2E06DC3E635F7120FE01

**Comment by gsautter** [comment]
Sorry, no idea ... our metadata extractor definitely doesn't extract them.

Maybe Zenodo pulls in CrossRef records and augments the author metadata? Just a wild idea ... Lars would probably know.
