### ISSUE TITLE
bibref parsing wrong: FFEE902BFFAA106D6C78792AFFFB960B

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#278]
This is a case for examples, where the bibRef parsing is utterly wrong. 
I fixed the bibrefs, so please keep this for your collecting of bibref parsring review 

![image](https://user-images.githubusercontent.com/4609956/31168112-f9968880-a8fc-11e7-9ed3-2f90d868c82f.png)

FFEE902BFFAA106D6C78792AFFFB960B

**Comment by gsautter** [comment]
Got it ... looks like the "and" in the author list is throwing off the parser, as it (a) is a relatively rare feat and (b) occurs only in two of these references, while most others end in "et al.". Not much to verify via comparing individual references in this case ...

Specifying author list specifics via a template would definitely solve this. And I'll try and see to it that the revised parser also covers this in the generic case.
