### ISSUE TITLE
materialsCitation parser Null FFB4F01C6067FFE6FF85FF9BC55CFFAB 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#279]
materialsCitation parser Null
![image](https://user-images.githubusercontent.com/4609956/31212410-0cca0f74-a9a9-11e7-9629-51ac21805e6a.png)

FFB4F01C6067FFE6FF85FF9BC55CFFAB

**Comment by gsautter** [comment]
Reproduced and fixed, comes with next build. Thanks for reporting.

I've processed the document and uploaded the result.
