### ISSUE TITLE
metadata: Authors not detected zootaxa.4337.1.4 CD0E87BAF20DFF91FF24FE92FEFCFC36

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#284]
It seems that we run into a problelm with Zootaxa articles whos's authors are not discovered. In this case, only the last author has been extracted. I have seen this in a couple of cases and try to keep an eye on them to understand, whether this is a larger issues

**Comment by gsautter** [comment]
Thanks for the treatment ID ... was fun trying to load an IMF with it ... should be `3137FFC2F20FFF9FFFB3FFD3FFC6FFFE`, I guess, at least judging by the summary link in http://tb.plazi.org/GgServer/html/CD0E87BAF20DFF91FF24FE92FEFCFC36

**Comment by gsautter** [comment]
Turns out this wasn't a template problem, so we are safe in that department.

Was a bug in the metadata extractor, more specifically in the handling of multi-valued attributes (basically author and editor). Fixed now, build to come soon.

**Comment by myrmoteras** [comment]
@gsautter , it would be heplful to get the new release asap, because otherwise I have to keep opening every batch parsed  file to check before I am uploading it. TX

**Comment by gsautter** [comment]
That update has been out since 8:30am this morning. Just allow web access on startup and let GGI pull the update.
