### ISSUE TITLE
Table: too much extended zootaxa.4337.2.3.pdf

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#286]
![image](https://user-images.githubusercontent.com/4609956/31707839-b0dd23dc-b3ed-11e7-9ad6-25095e00b296.png)

also, some of the tables not entirely detected

zootaxa.4337.2.3.pdf

**Comment by gsautter** [comment]
That will hardly ever happen with the new detector, which uses table boundary lines as anchors for detection, as opposed to the plain, graphics agnostic word block density based approach in the current one. Thus closed.
