### ISSUE TITLE
image processing: broken image

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#293]
http://www.ville-ge.ch/cjb/publications/cando721/c2017v721a5_low.pdf
the images in this Candollea article a pretty much broken

![image](https://user-images.githubusercontent.com/4609956/31986018-336408d8-b967-11e7-940e-babdeeb6342b.png)

![image](https://user-images.githubusercontent.com/4609956/31986044-49a657b8-b967-11e7-8ab3-da1730cfe1bf.png)

**Comment by gsautter** [comment]
Regarding the alignment in Figure 5, I cannot say for sure what exactly went wrong there ... however, this looks like another instance of our (outdated and replaced) light-on-dark filter kicking in where it simply should not.

In the latest version, however, it works just fine:
![image](https://user-images.githubusercontent.com/5789714/32028731-5f8df2be-b9f0-11e7-9520-4d9bb0f06fbf.png)
![image](https://user-images.githubusercontent.com/5789714/32028794-ac73aa06-b9f0-11e7-9da2-c7a086d22004.png)

**Comment by gsautter** [comment]
I'll make a new build tomorrow, but this one is solved.
