### ISSUE TITLE
import of different page format

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#30]
@gsautter here is the Flora of Switzerland, scanned and OCRed. But GGI can't deal with it, since it thinks it has two pages
What can we do?
[orchiadaceae_593_605_scan.pdf](https://github.com/gsautter/goldengate-imagine/files/656798/orchiadaceae_593_605_scan.pdf)

**Comment by gsautter** [comment]
Landscape pages ... not your standard publication, I guess.

However, respective options are already implemented in the PDF decoder, just not accessible via the UI yet, as I'm still trying to figure out an intuitive as possible way of doing that.

In the meantime, I can convert the file for you if you have a space I can put the IMF in afterwards.

**Comment by myrmoteras** [comment]
before you start doing a lot of work. check out, whether it works. If ok, I then scan the reminder of this family (30 pages more).

**Comment by myrmoteras** [comment]
There is one more question: how to link the images. They have not caption (how to write this for the BLR? metadata) and then how to create a link from the text that implicitely refers to the images?

**Comment by gsautter** [comment]
Whether or not using embedded OCR works is surely something I'll check, but ultimately, that's a feature and thus just has to work ...

**Comment by gsautter** [comment]
Linking images in the absence of captions is an unprecedented thing, however ... What we could do is annotate kind of in-text captions and link the figures to those, but the sensibility of that approach pretty much depends on how well the text describes the figures. Guess we'll have to check this on some sample.

**Comment by myrmoteras** [comment]
@gsautter here is finally the file - some of the printed pages are pretty pale and the scans turned out not all to be optimal - see what you can do
tx for looking into this

[orchiadaceae_593_637_scan_ocr.pdf](https://github.com/gsautter/goldengate-imagine/files/657709/orchiadaceae_593_637_scan_ocr.pdf)
