### ISSUE TITLE
file does not open in GGI: kopfweh corpus  Aura new epidemol insights CurrOpNeurol 2006.pdf

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#300]
[Aura new epidemol insights CurrOpNeurol 2006.pdf](https://github.com/gsautter/goldengate-imagine/files/1424126/Aura.new.epidemol.insights.CurrOpNeurol.2006.pdf)
[GgImagine.20171028-1056.err.zip](https://github.com/gsautter/goldengate-imagine/files/1424127/GgImagine.20171028-1056.err.zip)

**Comment by gsautter** [comment]
This was a subroutine related issue in the Type1 font engine.

Fixed now, comes with next build.
