### ISSUE TITLE
svg issue: graphic not complet

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#303]
opne in illustrator
![image](https://user-images.githubusercontent.com/4609956/32133786-529fabd8-bbdf-11e7-9db2-403e921f818b.png)

in ggi
![image](https://user-images.githubusercontent.com/4609956/32133792-6054f26a-bbdf-11e7-8d4e-c1570873b9dd.png)

original
![image](https://user-images.githubusercontent.com/4609956/32133795-6d78ec76-bbdf-11e7-8b05-960bdd0bcc08.png)

[Ferrari_oral triptans_meta-analysis_Lancet 2001.pdf](https://github.com/gsautter/goldengate-imagine/files/1424176/Ferrari_oral.triptans_meta-analysis_Lancet.2001.pdf)

**Comment by gsautter** [comment]
Why are you comparing Figure _2_ in GGI to Figure _1_ in the PDF? Tested both, and they render perfectly fine.
