### ISSUE TITLE
svg issue: non of the graphics does decode properly: kopfweh corpus: HA at USZ Sokolovic JHAPain 2013

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#305]
[HA at USZ Sokolovic JHAPain 2013.pdf](https://github.com/gsautter/goldengate-imagine/files/1424187/HA.at.USZ.Sokolovic.JHAPain.2013.pdf)

**Comment by gsautter** [comment]
Just tested the graphics on Pages 4 and 6 (Figures 3 and 4), and they decode and render perfectly fine. Could you provide me a screenshot of what garbled result you got, please?

**Comment by gsautter** [comment]
If you're referring to the figures in Page 3 (Figures 1 and 2), there's pretty little we could do ... these two come as 150 DPI bitmaps and thus naturally decline in quality when zoomed beyond 100%.
