### ISSUE TITLE
bibRef issues: does not detect bibrefs 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#307]
![image](https://user-images.githubusercontent.com/4609956/32134411-475c15b4-bbed-11e7-8a6f-22c48b08dd53.png)
[up side down Killer Aurau Ophthalm 2005.pdf](https://github.com/gsautter/goldengate-imagine/files/1424233/up.side.down.Killer.Aurau.Ophthalm.2005.pdf)

once detected, they parse perfectly.

file uploaded

**Comment by gsautter** [comment]
Another reason to re-work reference _detection_ ... but in that regard a duplicate of #306.
