### ISSUE TITLE
fixing errors: omitted letters

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#31]
@gsautter how can I fix a letter that is missing?

![image](https://cloud.githubusercontent.com/assets/4609956/21260159/f55853f6-c384-11e6-9a7c-1cff029f512a.png)

**Comment by gsautter** [comment]
Drag a box around the whole word (including the "E") and use "Mark Word".

**Comment by gsautter** [comment]
Why does ABBYY get that wrong, anyway? Can you correct there?

**Comment by myrmoteras** [comment]
this mark word is not offered

**Comment by gsautter** [comment]
Try switching on the OCR overlay.

**Comment by myrmoteras** [comment]
I can't to get it to work without loosing the entire word

**Comment by gsautter** [comment]
That's just fine ... remove the existing word and add a new one that includes the "E".
