### ISSUE TITLE
images don't decode well: kopfweh corpus

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#310]
![image](https://user-images.githubusercontent.com/4609956/32134764-67d28c9a-bbf4-11e7-9813-833e9c3fa8c2.png)

these images cannot be marked properly. How to fix this?
[Indocid not suma Allodynia 2004.pdf](https://github.com/gsautter/goldengate-imagine/files/1424264/Indocid.not.suma.Allodynia.2004.pdf)

**Comment by gsautter** [comment]
The two at the top are 200 DPI bitmaps, they just don't get any better.

The one at the bottom, as well as the one a page further up, are vector graphics. Just drag a box around them and use "Mark Graphics" (not "mark Image").
