### ISSUE TITLE
bibref detection and parsing wrong; Candollea 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#314]
[Chautems&Perret2017_Candollea.pdf](https://github.com/gsautter/goldengate-imagine/files/1427133/Chautems.Perret2017_Candollea.pdf)
![image](https://user-images.githubusercontent.com/4609956/32170481-fa52e6a6-bd74-11e7-996f-3d7bcd53220a.png)

author detection does not work
![image](https://user-images.githubusercontent.com/4609956/32170678-d3b52724-bd75-11e7-8001-4cd6a19521a8.png)

![image](https://user-images.githubusercontent.com/4609956/32170759-3090f7de-bd76-11e7-8f3f-d0a0509980f5.png)

![image](https://user-images.githubusercontent.com/4609956/32170813-6db5412e-bd76-11e7-8ab4-2a800f6b0d43.png)

**Comment by gsautter** [comment]
See #248 ... it's even the same screenshots ...
