### ISSUE TITLE
upload seems not work: how to know whether mark up is wrong or server problem

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#315]
here is a file that does not upload to BLR E32CFF9BFF88FFF2F976FF6A1552FFF6
I can't find anything that should stop it, but that it has graphics inside. Or it might have something to do with server issues https://github.com/plazi/Plazi-Communications/issues/743

**Comment by gsautter** [comment]
I just re-triggered the upload from the server admin console, and instantaneously got an error: "Invalid DOI" ... there's something missing in `0.1007/s11230-016-9695-z` ... looks like removing the resolver URL prefix was a bit over eager.
