### ISSUE TITLE
materialsCitation tagger issue: bug

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#316]
this is a case where the batch hung up - ie worked for a long time and did not move

[GgImagine.20171031-0612.err.zip](https://github.com/gsautter/goldengate-imagine/files/1429776/GgImagine.20171031-0612.err.zip)
`Processing document 'E:\diglib\zootaxa\temp\zootaxa.4341.2.2.pdf'
 - loaded PDF of 15686915 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'AF06FFBCFF8B73222675FFCFFF90C85C'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 36 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Add Document Meta Data'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Taxonomic Keys'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 27 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 1 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 20 taxon names
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Clean Table Annotations'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Remove Duplicate Annotations'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Detecting materials citation paragraphs
Getting document person names
Marking materials citations
Setting materials citation attributes
Detecting materials citation paragraphs
Getting document person names
Marking materials citations
Setting materials citation attributes
Detecting materials citation paragraphs
Getting document person names
Marking materials citations
Setting materials citation attributes
Detecting materials citation paragraphs
Getting document person names
Marking materials citations
Setting materials citation attributes

D:\GoldenGateImagine20170823>
[zootaxa.4341.2.2.pdf](https://github.com/gsautter/goldengate-imagine/files/1429778/zootaxa.4341.2.2.pdf)
`

**Comment by gsautter** [comment]
Setting the attributes of materials citations is a straightforward matter ... hard to tell how that one could take long or even hang. If any of the steps are prone to incurring excessive computational effort, it's marking the materials citations, but that one looks like having finished just fine.

Please try restarting the batch on the PDF in question. Thanks to storing intermediate results (which ends in the "Document stored to temporary folder" log entry), it should pick up right at the materials citations. Any change on the second run? If so, it most likely was a resource issue.
