### ISSUE TITLE
parsing names

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#32]
"Parse Taxon name" does not do anything, that is the result is just empty. How can I get this to work to get all the higher categories?

(I am off to lunch, start at 1pm again)

**Comment by gsautter** [comment]
What do you mean "empty"?

**Comment by myrmoteras** [comment]
no attributes:
![image](https://cloud.githubusercontent.com/assets/4609956/21261988/11f3dc1a-c38f-11e6-852a-ca9ca6a546b4.png)

**Comment by gsautter** [comment]
Are there any other taxon names marked in the document? As that's what the name parser draws higher taxonomy from ...

**Comment by myrmoteras** [comment]
I assume yes.  It is probably well worth looking at this article, since the markup is not very satisfying. The easiest is to take this document, remove all the marked up elements and just run FAT again.

http://treatment.plazi.org/GgServer/summary/0268333C9E44C00AFFF4FFA96C02EF75

**Comment by myrmoteras** [comment]
here is another article where parse names does not work. especially when extending a name that has been discovered as a genus but then added the species epithet.
e.g. 
![image](https://cloud.githubusercontent.com/assets/4609956/21421858/57da5e52-c835-11e6-97c3-062bff32e4e3.png)

[Tohme_Tohme_2014_LSJ_AntsLebanon.pdf](https://github.com/gsautter/goldengate-imagine/files/668473/Tohme_Tohme_2014_LSJ_AntsLebanon.pdf)

**Comment by gsautter** [comment]
see also #37

**Comment by gsautter** [comment]
As to this very name, how common practice is it to abbreviate a subgenus (without even adding a dot to indicate an abbreviation) and spell out the rest? That's currently just not covered by the patterns - possible to add, for sure, but also with some danger of incurring errors in other documents. For that latter reason, I'd like to know how frequent this form of abbreviation is, and ultimately whether or not covering such cases is worth the risk of incurring errors.

**Comment by myrmoteras** [comment]
the patter Author (SubGenus) speciesEpithet Author is common. Whether the subgenus abbreviation has a dot or no I am not clear, Probably not too often.

I am not sure, what other errors this could produce. We can try to collect more cases

**Comment by gsautter** [comment]
"Author (SubGenus) speciesEpithet Author" ??? Or did you mean "Genus (SubGenus) speciesEpithet Author"? The latter is generally covered by FAT's patterns, but only if (a) the subgenus is spelled out (3 or more letters) or (b) the subgenus is an abbreviation with a dot indicating so. It's only the dot-less abbreviation that's not currently covered.

On the other hand, what about "Genus (Author) speciesEpithet Author"? How frequent is that? FAT filters authors via (a) authorities recognized at the end of taxon names and (b) last names extracted from the bibliography, which tends to tell subgenera from genus authors pretty well. Just not so much with single letter abbreviations for either.

**Comment by gsautter** [comment]
Another very specific edge case that has been lingering for al too long to still be relevant, I guess ... laying it to rest.
