### ISSUE TITLE
table: merging tables: second table without header FFFDFFA5FFBEFFC88947DE39FF81F161

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#327]
in this case, where the table has no header, the following point is raised
![image](https://user-images.githubusercontent.com/4609956/32265730-83b82b48-bee4-11e7-821e-704d9f6e393e.png)

**Comment by gsautter** [comment]
Just observed that very phenomenon on #323 ... this is a warning rather than an error, and comes up because most table continuations do repeat the column headers. In such cases, a header mismatch does indicate an error, and thus the warning. Simply ignore it in this specific case.
