### ISSUE TITLE
Flora der Stadt Zürich: misssing words

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#33]
@gsautter I can't fix this, that is to get the missing words into the text

http://tb.plazi.org/GgServer/summary/0268333C9E44C00AFFF4FFA96C02EF75

![image](https://cloud.githubusercontent.com/assets/4609956/21288252/3c6aadb2-c47e-11e6-8efd-a667daf605f3.png)

I finished the markup - if you can, would be interesting how you add the images - let me know and I can do it for the Flora Helvetica

tx

**Comment by gsautter** [comment]
Have you tried showing the OCR overlay and then using "Mark Word" on each of the words? Likely easier if you zoom in to some 200% or so.

**Comment by myrmoteras** [comment]
Yes. I have tried. May be not with the highest magnification.



Sent from Samsung Mobile.


-------- Original message --------
From: gsautter
Date:17/12/2016 22:31 (GMT+01:00)
To: gsautter/goldengate-imagine
Cc: Donat Agosti , Author
Subject: Re: [gsautter/goldengate-imagine] Flora der Stadt Zürich: misssing words (#33)


Have you tried showing the OCR overlay and then using "Mark Word" on each of the words? Likely easier if you zoom in to some 200% or so.

-

**Comment by myrmoteras** [comment]
Btw the file is now in the imf store


Sent from Samsung Mobile.


-------- Original message --------
From: gsautter
Date:17/12/2016 22:31 (GMT+01:00)
To: gsautter/goldengate-imagine
Cc: Donat Agosti , Author
Subject: Re: [gsautter/goldengate-imagine] Flora der Stadt Zürich: misssing words (#33)


Have you tried showing the OCR overlay and then using "Mark Word" on each of the words? Likely easier if you zoom in to some 200% or so.

-

**Comment by gsautter** [comment]
Zoom doesn't really play a role in whether or not "Mark Word" is available or not, or does work or not - zooming in just makes it easier to drag the box exactly around the word you intend to mark.

On the other hand, "Mark Word" is only available with the OCR overlay showing, so OCR overlay needs to be at 30% or higher to mark words.

**Comment by myrmoteras** [comment]
I used ocr overlay


Sent from Samsung Mobile.


-------- Original message --------
From: gsautter
Date:17/12/2016 23:03 (GMT+01:00)
To: gsautter/goldengate-imagine
Cc: Donat Agosti , Author
Subject: Re: [gsautter/goldengate-imagine] Flora der Stadt Zürich: misssing words (#33)


Zoom doesn't really play a role in whether or not "Mark Word" is available or not, or does work or not - zooming in just makes it easier to drag the box exactly around the word you intend to mark.

On the other hand, "Mark Word" is only available with the OCR overlay showing, so OCR overlay needs to be at 30% or higher to mark words.

-

**Comment by gsautter** [comment]
"Mark Word" definitely does work ...
