### ISSUE TITLE
Table not discovered FF84FF82FFA6C62B1D72893EA90BFFEC 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#332]
![image](https://user-images.githubusercontent.com/4609956/32315358-13ef2848-bfac-11e7-8c48-9e0879cd968b.png)
[zootaxa.4341.4.12.pdf](https://github.com/gsautter/goldengate-imagine/files/1436854/zootaxa.4341.4.12.pdf)

**Comment by gsautter** [comment]
The lines should do the trick in the instant we use them.
