### ISSUE TITLE
font issue upper case; bug  FFC2FE08D542674EFFDFFFC0524FFFEE

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#333]
the capital letter font issue is not disappearing, which is a problem for batch processing. That means I would have to open each single article to check, whether the fonts are ok

![image](https://user-images.githubusercontent.com/4609956/32316024-c456a682-bfae-11e7-878e-0c0d5f32e156.png)

**Comment by gsautter** [comment]
Not sure why, but I just cannot seem to reproduce this one ... really excited to run some tests with your machines in two weeks.

![image](https://user-images.githubusercontent.com/5789714/32343974-8a151272-c005-11e7-9ec8-b476beabe43f.png)
