### ISSUE TITLE
flora der schweiz

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#34]
[orchiadaceae_593_637_scan_ocr.pdf](https://github.com/gsautter/goldengate-imagine/files/661282/orchiadaceae_593_637_scan_ocr.pdf)

**Comment by myrmoteras** [comment]
@gsautter I marked up the Flora of Switzerland using GG piB. It is easier to get it to a point where treatment markup works. Here  it is

http://tb.plazi.org/GgServer/summary/1D3CAFD3C5441126FFA1368AFAEE1D1D

That means, for the time being, getting the landscape publication in IMF done is not needed anymore. But in case we might get funding, then this might come up again.

**Comment by myrmoteras** [comment]
@gsautter here is another landscape formatted genus. Can you please convert it so I can continue to do the markup? One more for the LINDAS primer.

[Cerastium_806_819_ocrUnder.pdf](https://github.com/gsautter/goldengate-imagine/files/689825/Cerastium_806_819_ocrUnder.pdf)

**Comment by gsautter** [comment]
Here you go ... comes via mail because GitHub doesn't like the `.imf` file extension, as it seems.

You have all the new conversion options available in the latest built (Dec 20th, http://tb.plazi.org/GgServer/Downloads/GgImagine-Default.imagine.zip), by the way.

**Comment by myrmoteras** [comment]
thanks
what do I need to choose for the landscape pages?
![image](https://cloud.githubusercontent.com/assets/4609956/21718381/5d51a24e-d417-11e6-9390-b03beb22e819.png)

**Comment by gsautter** [comment]
If pages are landscape (or anything, really, basically one scanned page per PDF page), use "Single Pages".

"Double Pages" tells GGI that scans (PDF pages) contain two pages each, to be split roughly down the middle, which we have had with some books.

"Auto-detect" is what we used to have, namely to assume portrait pages to be the former, and landscape pages to be the latter. That's the reason this option is the default.
