### ISSUE TITLE
font wrong: batch processing: zootaxa4372.2.6

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#348]
![image](https://user-images.githubusercontent.com/4609956/32750589-63fdf57e-c8c3-11e7-9349-c03b27c88657.png)
[zootaxa.4372.2.6.pdf](https://github.com/gsautter/goldengate-imagine/files/1468712/zootaxa.4372.2.6.pdf)

run manually with basic Latin

font problem solved, but letters missing, table detection not

![image](https://user-images.githubusercontent.com/4609956/32750929-6e550322-c8c4-11e7-9cbf-ca652670d7cb.png)

![image](https://user-images.githubusercontent.com/4609956/32751043-b9001416-c8c4-11e7-8125-d7d225a88126.png)

**Comment by gsautter** [comment]
Table detection is something I'm still working to finish for next week ... when I'm not hunting font problems, that is ...

**Comment by gsautter** [comment]
Could reproduce the missing letters with "Render Glyphs Only", it's simply another one of the not so friendly fonts.
With "Latin", on the other hand,, it looks pretty much fine in my test run. I really need to run a few tests on your very machine to figure out what these decoding problems are due to ...

**Comment by myrmoteras** [comment]
this issue is not solved, since I cannot get this document processed.

**Comment by gsautter** [comment]
The point is it doesn't seem to be an issue in general, nothing I could seem to fix, simply because it works just like supposed to on my machine.

I'll check it out on yours next week and figure out why all these font issues happen that seem to be restricted to this very machine.

**Comment by myrmoteras** [comment]
did you check out the text in the table? for example Sumatra is there as umatra, etc

**Comment by gsautter** [comment]
Yes. I do look very closely before saying the fonts are fine.

**Comment by myrmoteras** [comment]
Ok then, can you upload the doc to TB so I can finish processing it?

**Comment by gsautter** [comment]
Here you go, UUID is FF84FFADFFB6452F4458FFCEFFD1AE78

I've ran Document Structure (without correcting, though) and Metadata so the batch won't kick in.

Let's _not_ make this a regular thing ... I need some time to finish the tables, and I have other things on my list as well.

**Comment by myrmoteras** [comment]
thanks, this is processed now
