### ISSUE TITLE
taxonomicName missing and incomplete Copeia.105.4.659 6D37FFA3FFED706EFF811D7EFFB3284F

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#349]
![image](https://user-images.githubusercontent.com/4609956/32754146-ded7efc8-c8cf-11e7-937f-4e2549c796d8.png)

in this article, many names are either missing or are incompletely marked up.

I fixed at least all the relevant names.

**Comment by gsautter** [comment]
Testing this one, FAT found basically all the "Antennatus" species, listing "catalogs" as the evidence, which tells me CoL does list them, and FAT detects them for that reason.
The one name that did indeed get missed out upon is "Histrio histrio", not sure why just yet.

**Comment by gsautter** [comment]
An odd part in the taxon of this treatment is the "in Radcliffe" part of the authority ... This part most likely needs to be cut in normalization, does it? Not as hard to do (cut authority name from ", in"), but am I making sense? And anyway, how frequent is such a suffix to an authority?

**Comment by gsautter** [comment]
The reason "Histrio" got eliminated as a genus to look up in the catalogs is that it also is a species in this very article and thus appears more often in lower case than capitalized. Might sound odd in this case, but this for that Lepidoptera genus by the name of "Data" for the reason this elimination rule exists.
I might add another rule deactivating the capitalization catch if the lower case version occurs right after the capitalized version ...

**Comment by gsautter** [comment]
Done, added the word repetition rule, which now saves a genus from elimination even if there is an equally spelled species, provided the two appear together, e.g. "Monomorium monomorium" or "Histrio histrio". That should still catch the "Data" it is aimed at.
