### ISSUE TITLE
materialsCitation: misapplied MC boundaries FFC72971FFA22218C30BFFB8FFDEAF5E

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#350]
This is an example where MC went awry, despite that the MC are separated by ";"
zootaxa.4347.3.12.pdf

**Comment by gsautter** [comment]
OK, I'll hunt this down, forget about the tables.

**Comment by gsautter** [comment]
Really makes my day to get yet another one before having to run for work.

**Comment by gsautter** [comment]
It's not even on the server, so I'll carry this scarlet letter with me all day, feeling like a finger pointed straight at me. I'll feel bad all day about this.

**Comment by gsautter** [comment]
Really rewarding to get up at 4:30, start working right away, and still not managing to get all of yesterdays tickets checked before having to run for my day job.

**Comment by gsautter** [comment]
I wanted to go to the office at 8:00 so I could come home earlier and get back to the tables, but that's not going to happen now.

**Comment by myrmoteras** [comment]
Guido:
NONE of this has been labled as URGENT. So there is NO rush.
They all have a label that says what kind of annotation etc it is. This is meant to allow to fix them together, such as you do, and we discussed with the tables.

There will always be tickets, since I process many documents and have longer hours to work. If this is bothering you, then we need to think about a different system. You have to tell me how you want to have it. I could also add another github repository to which you do NOT have access so I can add errors, problems, etc. and report them once a month.

**Comment by myrmoteras** [comment]
please prepare for this

https://docs.google.com/document/d/1A3n_hdRStvYUcEIeGG2aywSIun8jTrvmdZUvAX9DaRY/edit#heading=h.vj9phyenjqix

**Comment by gsautter** [comment]
EVERYTHING, every ticket is urgent, as every ticket screams in my face that whatever I just built is not good enough (despite stating a best effort basis, e.g. for the MCs), it's a failure, it's a testimony of my own very failure, a testimony of the mere fact that I AM A TOTAL FAILURE.

There will always be the one oddjob with which things go awry, the one thing that just tells the world that whatever I do is a failure an thus was in vain. There is no going on, no prospect of success ever, just scarlet letters painted upon me for each and everything that goes south.

For answering to all those tickets, no time getting around to doing interesting things like (for starters) finishing graphics based table detection, or a more comprehensive semantic markup scripting language (to foster that sacred community process that I got slammed in may face right after first presenting GGI), author affiliation handling, non-bibliographic metadata (like licenses), etc.

**Comment by gsautter** [comment]
On a more on-topic note, a link to the IMF or at least PDF would be extremely helpful, as I don't have the option to get the PDF via AMNH.
If you want me t look at something, please make sure I have access at least to the PDF (preferring the IMF).
