### ISSUE TITLE
table: not complete annotation, header FF9FF0466D34CD26F2030B4CF8365668

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#361]
This seems to be an example of a more widespread case, where the header of tables is not detected
![image](https://user-images.githubusercontent.com/4609956/32936479-aeb727c6-cb74-11e7-827f-c57f784bef68.png)

**Comment by myrmoteras** [comment]
a similiar example are the tables in this publication 
![image](https://user-images.githubusercontent.com/4609956/32937136-6ca41706-cb77-11e7-9efe-d029cc671072.png)

FF9EFF97D664FFD4FFC3FC20BD16FFB0

**Comment by gsautter** [comment]
Thanks for this, I'll use that table as a test case right away, namely for calibrating the table detector to (a) recognize a table in the presence of multi-column cells (the top row of headers) and (b) recognize multi-column cells as such and mark columns accordingly.

**Comment by gsautter** [comment]
Solved now, this one comes out pretty much perfect with the new logic.
