### ISSUE TITLE
document metadata: journal volume instead of article 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#366]
in this Zootaxa case, an others, the page number is not discovered

D2424F79FFF8FFC8AE34656F915D6B35

**Comment by gsautter** [comment]
I think you mean pagination? That's most likely a pattern issue, caused by some exotic dash. I'll check.

**Comment by gsautter** [comment]
Fixed ... was indeed a pattern issue, even though the dash wasn't the culprit. Stupid pattern error of mine in the parts accounting for leading zeros that Zootaxa has occasionally been adding to the pagination. Comes with the next build.
