### ISSUE TITLE
font issues: words not separated BTP journal

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#368]
here is a journal for which we would like to make a template

it has two issues upfront:  
* Font and separation of words
* colums are not recoginzed
[BTP_article_13003.pdf](https://github.com/gsautter/goldengate-imagine/files/1513309/BTP_article_13003.pdf)
[BTP_article_14805.pdf](https://github.com/gsautter/goldengate-imagine/files/1513312/BTP_article_14805.pdf)

**Comment by gsautter** [comment]
Thanks. I'm aware of the issue (also occurs with the Zoosystema article we went over together last Sunday). Great to have two more examples to verify that whatever solution I come up with for the Zoosystema also works for other cases.

**Comment by gsautter** [comment]
The word width overruns were actually word spacing overruns (see #369) and are fixed now. See the latter for an explanation of the underlying problem.
