### ISSUE TITLE
Zoosystema: block issues z2017n1a3_0

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#369]
blocks are not split

in this articles the blocks are not split, e.g. page 2
[z2017n1a3_0.pdf](https://github.com/gsautter/goldengate-imagine/files/1524872/z2017n1a3_0.pdf)

**Comment by myrmoteras** [comment]
same using glyphs only

![image](https://user-images.githubusercontent.com/4609956/33526688-167f8506-d845-11e7-97e2-16497beeccff.png)
in this case I can merge and split them

**Comment by gsautter** [comment]
Solved ... was a bit of an obscure one.

Here's what was going on: Whenever rendering the glyphs in a font, the decoder detects if there are glyphs that use the same sequence of rendering commands, and then conflates the respective character codes (which make up the raw text in the PDF) to reduce the size of the font. This also reduces decoding effort if the latter is activated, along with correction effort in "Edit Fonts" in GGI.
Now there is two types of spacing in PDF: character spacing and word spacing, with the latter being inserted after character code 32 (ASCII space), and the former after all other characters. This is independent of the glyph actually rendered, it only depends on the character code proper.
In this PDF now, we have two spaces. Both render the same (an empty sequence of rendering operations), and thus ended up conflated, ending up character codes 31 and 32 the same. This, in turn, resulted in a mixup of the aforementioned two types of spaces, ending up with word spacing just off what it should be ... what a subtle little bugger.

Preventing character code synonymization based on empty rendering command sequences now, so this should no longer be a problem.
