### ISSUE TITLE
missing figures 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#38]
@gsautter in this treatment, the figures do not show up

http://tb.plazi.org/GgServer/html/03A487BF3968FFB6FF7CFAB5FB50FDEE

**Comment by gsautter** [comment]
Looking at http://tb.plazi.org/GgServer/xml/03A487BF3968FFB6FF7CFAB5FB50FDEE , the `figureCitations` don't have any `httpUri` attributes, so nothing to show ...

I just tried to manually trigger upload to Zenodo, and the latter complains about the DOI, which is "0.13102/sociobiology.v63i2.869", where I guess it should be "10.13102/sociobiology.v63i2.869" ... change that, and it should work just fine.
