### ISSUE TITLE
document does not open:  BatraxisLOBL

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#385]
![image](https://user-images.githubusercontent.com/4609956/33760996-e8c40e54-dc07-11e7-8696-4d25098386a4.png)
[BatraxisLOBL.pdf](https://github.com/gsautter/goldengate-imagine/files/1542239/BatraxisLOBL.pdf)

**Comment by gsautter** [comment]
And rightfully so ... this one is _really_ odd, so in that it apparently renders all the text, character by character, as individual vector graphics, as opposed to utilizing the usual PDF text rendering facilities. 

To see what I mean, just open this PDF in Acrobat and try to copy some text ...

There is Preciously little we could do about this one, safe for running it through OCR. From a technical point of view, this whole PDF is just a sequence of vector graphics, no text at all.

Left to wonder who produces such PDFs ...
