### ISSUE TITLE
text stream / regions, blocks not discovered

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#387]
[Kramp_1942d_OCR.pdf](https://github.com/gsautter/goldengate-imagine/files/1557370/Kramp_1942d_OCR.pdf)

if I run this scanned and in ABBYY OCRed article  in GGI using glyphs only, I don't get the text. So what to do?

![image](https://user-images.githubusercontent.com/4609956/33966233-1bd7d748-e05f-11e7-8bb0-8af9f4fa343f.png)

**Comment by gsautter** [comment]
Embedded OCR or not, this is still a scanned PDF ... just load it as such, with the "Embedded OCR" option selected, and it should work fine.

If you load it as born-digital (which is the only way "Render Glyphs Only" is even available), the PDF decoder recognizes an image (the scan) with words inside (the embedded ORC text) and turns that very text into figure labels.
"Render Glyphs Only" makes no sense for OCRed PDFs (embedded text or not), as vector graphics letters (which is the one thing that embedded fonts contribute) only ever make sense if they are visibly rendered, which is not the case for embedded OCR. In the latter case, the rendered part is the scan, and the embedded OCR result is merely an accessibility feature anabling full text search along the way. No weird encoding, no glyphs to render, just plain PDF text (the kind PdfBox and all the other open source PDF libraries can extract).
