### ISSUE TITLE
batch processing parameters

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#390]
what are the batch processing options and its parameters?

FM=
R glyphs
D 

CS=
S

DT= 
B
D born digital

CKDWCA

**Comment by gsautter** [comment]
Simply start the batch with _no_ `DATA=` parameter, and you'll get the full list. The actual command is simply `java -jar GgImagineBatch.jar`

Please note that (a) the latest build has added a `CONF=` parameter to specify a config file, and that many of the other parameters can be taken from that very file.

**Comment by gsautter** [comment]
What does `CKDWDA` mean?

**Comment by myrmoteras** [comment]
CKDWCA

`java -jar GgImagineUploader.jar "DATA=E:\diglib\zootaxa\temp" HOST=http://plazi.cs.umb.edu/GgServer/proxy AUTH=plazi:plabor CKDWCA DEL `

**Comment by myrmoteras** [comment]
please, explain what the parameters or its value mean

what are the batch processing options and its parameters?

FM=
R glyphs
D

CS=
S

DT=
B
D born digital

**Comment by gsautter** [comment]
First of all, there is no batch processing in the _uploader_.

**Comment by gsautter** [comment]
If you simply run `java -jar GgImagineBatch.jar` without any parameters, you get the parameters and possible values printed out, including the sought explanations.

**Comment by myrmoteras** [comment]
D:\GoldenGateImagine20170823>java -jar GgImagineBatch.jar
GoldenGATE Imagine Batch can take the following parameters:

PATH:   the folder to run GoldenGATE Imagine Batch in (defaults to the
        installation folder)
CACHE:  the root folder for all data caching folders (defaults to the path
        folder, useful for directing caching to a RAM disc, etc.)
DATA:   the PDF files to process:
        - set to PDF file path and name to process that file
        - set to folder path and name to process all PDF files in that folder
        - set to TXT file to process all PDF files listed in that file
DT:     the type of the PDF files to process (defaults to 'G' for 'generic'):
        - set to 'D' or 'BD' to indicate born-digital PDF files
        - set to 'S' to indicate scanned PDF files
        - set to 'G' or omit to indicate generic PDF files (expects both
          born-digital and scanned, determining type on a per-file basis)
FM:     the way of handling embedded fonts (relevant only for 'DT=D' and 'DT=G'):
        - set to D to completely decode embedded fonts (the default)
        - set to U to decode un-mapped embedded fonts (ones without a Unicode mapping)
        - set to R to only render embedded fonts, but do not decode glyphs
        - set to Q for quick mode, using Unicode mapping only
CS:     the char set for decoding embedded fonts (relevant only for 'FM=D' and 'FM=U'):
        - set to U to use all of Unicode
        - set to S to use Latin characters and scientific symbols only (the default)
        - set to M to use Latin characters and mathematical symbols only
        - set to F to use Full Latin and derived characters only
        - set to L to use Extended Latin characters only
        - set to B to use Basic Latin characters only
        - set to C for custom, using 'CP' parameter to specify path (file or URL) to load from
CP:     the file or URL to load char set for embedded font decoding from (relevant only for 'CS=C', and required then).
OUT:    the folder to store the produced IMF files in (defaults to the folder
        each individual source PDF file was loaded from)
OT:     the way of storing the produced IMF files (defaults to 'F' for 'file'):
        - set to 'F' or omit to indicate (zipped) single file storage
        - set to 'D' to indicate indicate (non-zipped) folder storage
LOG:    the name for the log files to write respective information to (file
        names are suffixed with '.out.log' and '.err.log', set to 'IDE' or 'NO'
        to log directly to the console, or to DOC to create one log file per
        document, located next to the IMF)
ST:     no value, just add this token to the command to make the batch run on a single core
HELP:   print this help text

The file 'GgImagineBatch.cnfg' specifies what to do to PDF documents after
decoding:
- imageMarkupTools: a space separated list of the Image Markup Tools to run
- configName: the name of the GoldenGATE Imagine configuration to load the
  Image Markup Tools from

D:\GoldenGateImagine20170823>

**Comment by gsautter** [comment]
This help text output looks a bit older ... should be this:

`GoldenGATE Imagine Batch can take the following parameters:

PATH:	the folder to run GoldenGATE Imagine Batch in (defaults to the
	installation folder)
CONF:	the (path and) name of the configuration file to run GoldenGATE
	Imagine Batch with (defaults to 'GgImagineBatch.cnfg' in the folder
	GoldenGATE Imagine Batch is running in)
CACHE:	the root folder for all data caching folders (defaults to the path
	folder, useful for directing caching to a RAM disc, etc.)
DATA:	the PDF files to process:
	- set to PDF file path and name to process that file
	- set to folder path and name to process all PDF files in that folder
	- set to TXT file to process all PDF files listed in that file
DT:	the type of the PDF files to process (defaults to 'G' for 'generic'):
	- set to 'D' or 'BD' to indicate born-digital PDF files
	- set to 'S' to indicate scanned PDF files
	- set to 'G' or omit to indicate generic PDF files (expects both
	  born-digital and scanned, determining type on a per-file basis)
FM:	the way of handling embedded fonts (relevant only for 'DT=D' and 'DT=G'):
	- set to D to completely decode embedded fonts (the default)
	- set to U to decode un-mapped embedded fonts, i.e., ones without a Unicode
	  mapping (the default)
	- set to R to only render embedded fonts, but do not decode glyphs
	- set to Q for quick mode, using Unicode mapping only
CS:	the char set for decoding embedded fonts (relevant only for 'FM=D' and
	'FM=U'):
	- set to U to use all of Unicode
	- set to S to use Latin characters and scientific symbols only (the
	  default)
	- set to M to use Latin characters and mathematical symbols only
	- set to F to use Full Latin and derived characters only
	- set to L to use Extended Latin characters only
	- set to B to use Basic Latin characters only
	- set to C for custom, using 'CP' parameter to specify path (file or URL)
	  to load from, or name of a named charset to load from a provider
CP:	the file or URL to load the charset for embedded font decoding
	from (relevant only for 'CS=C', and required then; implies 'CS=C' if 'CS'
	parameter omitted); can also be the name of a named charset to resolve via
	some provider (prefix with '@' to indicate such a name)
OUT:	the folder to store the produced IMF files in (defaults to the folder
	each individual source PDF file was loaded from)
OT:	the way of storing the produced IMF files (defaults to 'F' for 'file'):
	- set to 'F' or omit to indicate (zipped) single file storage
	- set to 'D' to indicate indicate (non-zipped) folder storage
LOG:	the name for the log files to write respective information to (file
	names are suffixed with '.out.log' and '.err.log', set to 'IDE' or 'NO'
	to log directly to the console, or to DOC to create one log file per
	document, located next to the IMF)
ST:	no value, just add this token to the command to make the batch run on a
	single core (e.g. if resources required for other simultaneous tasks)
HELP:	print this help text

The file configuration file ('GgImagineBatch.cnfg' by default) specifies how
to process PDF documents after decoding, and can also provide environmental and
PDF decoding parameters:
- imageMarkupTools: a space separated list of the Image Markup Tools to run
- configName: the name of the GoldenGATE Imagine configuration to load the
  Image Markup Tools from
- cacheRootFolder: configurable default for 'CACHE' parameter
- fonts.decoding.mode: configurable default for 'FM' parameter
- fonts.decoding.charset: configurable default for 'CS' parameter
- fonts.decoding.charsetPath: configurable default for 'FP' parameter`

**Comment by gsautter** [comment]
If you download the latest build and run the batch without any parameters, you should get the same output.
