### ISSUE TITLE
missing symbols contributions_25_bluemlisalpicola_reduziert

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#391]
I tried all flavors of GGI but non would convert the male/female symbol

![image](https://user-images.githubusercontent.com/4609956/34004535-6e9d2552-e0f8-11e7-91bf-d3fe3d97ba44.png)

copied from the text 
4 􀆃, 4 􀆂 BE

![image](https://user-images.githubusercontent.com/4609956/34004746-02ec9d64-e0f9-11e7-8ddc-c4bc3e45570e.png)
[contributions_25_bluemlisalpicola_reduziert.pdf](https://github.com/gsautter/goldengate-imagine/files/1560123/contributions_25_bluemlisalpicola_reduziert.pdf)

**Comment by gsautter** [comment]
Reproduced. Clearly, the male and female symbols are lacking the Unicode mapping. I'll try and figure out why they don't render (so they could be corrected via "Edit -> Edit Embedded Fonts"). Another one for the train.

**Comment by gsautter** [comment]
Is the same PDF also available in not "reduziert"? I'd like to test that as well.

**Comment by myrmoteras** [comment]
no - only the above version is online accessible

**Comment by gsautter** [comment]
I've figured this one out, was a glitch in handling >255 character codes that lack a Unicode mapping.

Fixed so you can correct the symbols now via "Edit Font". UUID is `911DFFF4FFB1DF68A24FFFFDC87FFFA6`
