### ISSUE TITLE
zootaxa file does not open in GGI zootaxa.4369.3.4.

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#397]
[zootaxa.4369.3.4.pdf](https://github.com/gsautter/goldengate-imagine/files/1606185/zootaxa.4369.3.4.pdf)

I can't open this file in batch mode nor using glyphs only or default
[GgImagine.20180105-0953.out.zip](https://github.com/gsautter/goldengate-imagine/files/1606195/GgImagine.20180105-0953.out.zip)

**Comment by gsautter** [comment]
This is a weird one ... can only reproduce it when running the whole PDF, but not running any individual page, which is the usual setup for investigating problems related to a single page.
It has nothing to do with the fonts, but happens where page content is flipped into its regular horizontal position. Will keep investigating.

**Comment by gsautter** [comment]
Looks like this happens because the bitmap phylogenetic tree in Page 4 is bottom up, but its caption is left-right right below it ...

**Comment by gsautter** [comment]
Fixed, the IMF is on the server with structure detection and metadata done, UUID is `FFEB4D46FFE66357FFC0B3512A36BD63`.

The decoder fix comes with the next build.

**Comment by myrmoteras** [comment]
finished
