### ISSUE TITLE
table wrong, zootaxa.4369.4.2 F8185F028B3DB54A9D7E6269FFF35735 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#399]
![image](https://user-images.githubusercontent.com/4609956/34663374-d8d294d6-f456-11e7-9da9-01af70ad9c31.png)

**Comment by gsautter** [comment]
OK, I see ... looks like a row detection error to me. Will check.

**Comment by gsautter** [comment]
At first glance, this looks like row distinction being set off by the extremely lavish spacing in the header area, which appears to drive up the _average_ row margin so far that the regular rows end up merged. I'll try and find a catch ...

**Comment by gsautter** [comment]
I think the catch might be the average line distance in the document main text ... will try that first.

**Comment by gsautter** [comment]
This one comes out OK now.
