### ISSUE TITLE
markup of names incomplete

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#4]
@gsautter in this article 50% of names are marked up incomplete

![image](https://cloud.githubusercontent.com/assets/4609956/20786654/8bb5108a-b7a7-11e6-88ad-9ea2bd163875.png)
[Atahuachi et al 2016 Bolivian Mimosa Phytotaxa.pdf](https://github.com/gsautter/goldengate-imagine/files/623995/Atahuachi.et.al.2016.Bolivian.Mimosa.Phytotaxa.pdf)

**Comment by gsautter** [comment]
Looks like out-of-catalog species to me, if not all ... CoL does know "Mimosa farinosa", for instance.

Is the IMF on the server? That would enable testing to start right with the XML ...
