### ISSUE TITLE
extraction of exact article publication date

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#40]
@gsautter 
issue: exact publication date for arcticles.

The exact publication date is an important element in taxonomy especially in nomenclature. The date is often published on the front page of an article, such as in Zootaxa
![image](https://cloud.githubusercontent.com/assets/4609956/21809434/018e6346-d748-11e6-89a5-70e9ff35b833.png)

Since we extract the year of the publication, and then set it to the last day of the year in BLR, I would like to suggest that we change this policy wherever we can, especially in those article we extract automatically (Zootaxa, all Pensoft publications).

**Comment by gsautter** [comment]
I'll try and add that to the bibliographic metadata extractor, as well as to the Zootaxa templates.

**Comment by gsautter** [comment]
Done, finally. The MODS side modelling was a bit of a blocker issue, but I solved it now.

Since one of the last builds, all Zootaxa have had their exact publication date added.

The all-out collection update is still to happen, but implementation and deployment are closed on this one.
