### ISSUE TITLE
table not completely detected  zootaxa.4369.4.4.pdf

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#400]
![image](https://user-images.githubusercontent.com/4609956/34663679-300d36a6-f458-11e7-8d4d-e0974c41751d.png)
[zootaxa.4369.4.4.pdf](https://github.com/gsautter/goldengate-imagine/files/1610958/zootaxa.4369.4.4.pdf)

not uploaded to TB/BLR; to be processed

**Comment by gsautter** [comment]
Please add the UUID once this one is up on the server ... no need for double-decoding.

**Comment by gsautter** [comment]
My first take on this one is that over half of the document consisting of the table in question (13 out of 21 pages) influences the word spacing average to such a degree that the relatively narrow column margins end up being perceived more like regular spaces than column margins.

First take here will most likely be to cap off the word spacing average at some quite conservative upper bound that will (a) still make sure not to "find" any tables in normal text, but (b) not be deceived by tables making up the larger portion of the whole document.

I actually considered the influence of large tables on the word spacing average when implementing the current table handling mechanisms, but couldn't think of one single example of _this_ large a table ... guess this oddjob just showed up in time to prove me wrong ...

**Comment by gsautter** [comment]
Solved, works now. As in https://github.com/plazi/EJT-testbed/issues/145 , the problem were the somewhat serrated columns that project quite a few obstructions into the column margins.

Fix comes with the next build.
