### ISSUE TITLE
table extraction failes zootaxa.4374.4.5.pdf

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#408]
in this case, this table has not been found on page552   FFEDFFFEE31144439226F424070BC830

![image](https://user-images.githubusercontent.com/4609956/35223854-34577592-ff83-11e7-8e74-d8afee4f1794.png)

**Comment by gsautter** [comment]
Got it ... in this instance, the table detector was overly cautious to not mark a table across a caption, i.e., some row label put it off. Fixed that now, comes with build tonight.
