### ISSUE TITLE
tables: table header spanning several colums not marked upt zootaxa.4375.2.2 C358FA02FFB45F581B3BFFFAFF8FC74A

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#413]
C358FA02FFB45F581B3BFFFAFF8FC74A

![image](https://user-images.githubusercontent.com/4609956/35321876-8ab6544c-00e8-11e8-9c2a-9012172423af.png)

**Comment by gsautter** [comment]
Fixed ... this was a bit of a weird one, caused by the partially overlapping layout of the multiple lines of column headers. Comes with tonight's build.
