### ISSUE TITLE
font messed up zootaxa.4375.3.5

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#415]
[zootaxa.4375.3.5.pdf](https://github.com/gsautter/goldengate-imagine/files/1663012/zootaxa.4375.3.5.pdf)

in the main body, the font is messed up. the batch run using FM=R

![image](https://user-images.githubusercontent.com/4609956/35377205-92258c36-01ae-11e8-88bb-57eea6902499.png)

tables especially

![image](https://user-images.githubusercontent.com/4609956/35377241-afb00d62-01ae-11e8-9cb3-b76d42b7c763.png)

caption are fine

rerun using FM=D; font ok.

**Comment by gsautter** [comment]
Just another instance of an unfriendly font, i.e., one that comes without a Unicode mapping. You've found the solution already ... `FM=D`. There is preciously little we can do beyond that.

One option you do have is generally using `FM=U`, which is similar to `FM=R` when there is a Unicode mapping, and similar to `FM=D` when there is none. The `U` is literally short for "Decode Unmapped", basically instructing the PDF decoder to generally run "Render Glyphs Only", but resort to all-out graphics based glyph decoding whenever it encounters a character that comes without a Unicode mapping. That should do the trick in the very most cases, i.e., all except those with an intentionally wrong (malicious copy&paste prevention) Unicode mapping.
By the way, `FM=U` is the default for the batch now (and has been for a little), so you can simply omit the `FM` parameter.
