### ISSUE TITLE
new version of GGI: biblRef parser does not work. BUG

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#420]
in todays version of GGI 20180131 downloaded, the bibRef parser does not work, eg ejt-398  41313769FFC96D15061DFFAFFFACFF87 or FF80CC3456770C27533C8513FFDA4805

running bibRef parser stops and bibRef are neither discovered not comes to menu up to check the parsing

the previous version of GGI still works

**Comment by myrmoteras** [comment]
@gsautter hi Guido
can you please look into this issue. This is important because without the ID in bibRefs added to the bibRefCitation Terry cannot finish the taxpub import.
TX

**Comment by gsautter** [comment]
Well, I didn't even touch the _parser_ thus far, i.e., RefParse ... all I ever changed is the reference _tagger_. Will check what's wrong with that in these two cases.

**Comment by gsautter** [comment]
That said, reference tagging seems to work just fine with `ejt-398_atherton_jondelius.pdf.imf` ...

**Comment by gsautter** [comment]
Still investigating `ejt-399_zonstein_kunt.pdf.imf` ... one factor might be that the actual article ends about halfway through the PDF, with the rest being and extensive (outright excessive) appendix.
Testing this IMF, I end up with the appendix captions tagged as references ... _extremely_ weird.

**Comment by gsautter** [comment]
Some going through logs shows me that for some reason the initials immediately following the author names fail to recognize as such. While very weird, this at least gives me an idea as to where to start investigating ...

**Comment by gsautter** [comment]
Until I figure this one out, please use the previous build. Sorry for the inconvenience. I did test the new reference tagger with a good few EJT's, and it appeared to be working like a charm. There must be something about `ejt-399_zonstein_kunt.pdf.imf` ...

**Comment by gsautter** [comment]
Anyway, as EJT 398 did work just as supposed to in my test, and apparently did not in your runs, could you please provide me a log? That most likely vastly simplifies assessing and solving this problem.

**Comment by gsautter** [comment]
Got it ... "Figs" ends up regarded as an institutional author name (like "World Spider Catalog" or "International Commission for Zoological Nomenclature", or just "Reuters", to which there is no difference in terms of a pattern matching any single title case word), and there is just more successive captions in the appendix than there are references in the bibliography. Which is why the appendix captions end up prevailing.

I'll adjust the scoring formula for potential bibliographies to prevent such runaways.

**Comment by gsautter** [comment]
Just, please, provide me with an error log of `ejt-398_atherton_jondelius.pdf.imf` ... I cannot seem to reproduce whatever went wrong with that one, so a log would vastly help me figure out that part.

**Comment by gsautter** [comment]
Finally, got `ejt-399_zonstein_kunt.pdf.imf` to work as well ... factoring in some weighting based on the significance of the pattern match identifying a paragraph as a reference finally succeeded in voting out the "Figs" paragraphs.

**Comment by gsautter** [comment]
The last build should have fixed this.
