### ISSUE TITLE
Treatment not discovered. Zootaxa batch

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#422]
missed treatments in the constellation below is an issue that shows up regularly when running : 

![image](https://user-images.githubusercontent.com/4609956/35731206-17b5ffa4-0815-11e8-95de-34c628470f28.png)

**Comment by gsautter** [comment]
Same as #414 ... "Results" overruled the subsequent paragraph, which happens to be a treatment heading. Changed that now.
