### ISSUE TITLE
article does not open in GGI: Studies in Mycology

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#423]
https://www.sciencedirect.com/science/article/pii/S0166061617300593?via%3Dihub#

This article does not open in GGI.

[GgImagine.20180204-1049.out.zip](https://github.com/gsautter/goldengate-imagine/files/1692652/GgImagine.20180204-1049.out.zip)

**Comment by gsautter** [comment]
Thanks for this one, helped me find and fix a glitch in page content flipping, i.e., in the part of the PDF decoding process that turns bottom-up page content (in this case the table on Pages 4-6) into a horizontal position.

Comes with the build I plan on creating tonight on the train.
