### ISSUE TITLE
TB: figures do not show up

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#43]
@gsautter in this document, the figures do not show up in TB.

http://tb.plazi.org/GgServer/html/5F413427D3797A7CFF615199FC918FDD

http://tb.plazi.org/GgServer/summary/A3784C5FD3787A79FFD25369FFE38E06

it has been marked up before Christmas. some of the figure captions are on the previous page

**Comment by gsautter** [comment]
This is a new case of error ... I just tried and manually triggered the upload, and got an error in response, for a simple reason: The document has a Zenodo DOI "10.5281/zenodo.46306", but is not explicitly linked to the deposition, i.e., does not have an `ID-Zenodo-Dep` attribute.

Set document attribute `ID-Zenodo-Dep` to `46306`, and the figures should go on Zenodo in no time.
