### ISSUE TITLE
not decoding: zootaxa.4383.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#448]
[GgImagine.20180223-0928.out.zip](https://github.com/gsautter/goldengate-imagine/files/1750962/GgImagine.20180223-0928.out.zip)

this is a 54MB  file, you can find it here https://drive.google.com/open?id=1LLJQVzfpGk_TwBw1qxCBUkyfeQYAW_N-

**Comment by gsautter** [comment]
Will check ... last one wins, EJT 404 gets pushed back.

**Comment by gsautter** [comment]
This one opens just fine on my machine ... in fact, the log (thanks for that) shows me that the error failing the decoder is one I've added a catch for maybe a month ago.
While the log tells me that your configuration is up to date, it looks like your base JARs (the ones right in your GGI install folder) are not ... what modification date and size are your `ImageMarkup.jar` and `ImageMarkupPDF.jar`?

**Comment by myrmoteras** [comment]
ImageMarkupPDF.jar? 11/9/2017
ImageMarkup.jar 11/9/2017

**Comment by gsautter** [comment]
This is quite old, small wonder you keep reporting the same old problems ... the latest update is here: http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20180213-2212.zip Just download that into your GGI/Updates folder, and it should install on the next startup. Or simply open it and put the content in your GGI root folder.

**Comment by gsautter** [comment]
These well outdated base JARs most likely even explain the nested taxon name issues, which I could never reproduce, either.

**Comment by myrmoteras** [comment]
ok - updated - and will test right away with the new EJTs.. tx
