### ISSUE TITLE
linking figures to figCit

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#45]
@gsautter in this document I uploaded last night, the figures do not show up in treatments

http://tb.plazi.org/GgServer/summary/FFA7085B97097C08FFE19F343655FFA4
eg 
	
http://treatment.plazi.org/id/039E7023-9707-7C06-FF49-996032FAFC96

**Comment by gsautter** [comment]
Should be there now ... could be the upload failed due to a similar error like we had an hour ago ...
