### ISSUE TITLE
batch processing: interaction during batch processing

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#453]
Why do I get this question 
![image](https://user-images.githubusercontent.com/4609956/36836348-574ea2e0-1d39-11e8-8659-57f84f16c3cf.png)

using the java -jar -Xmx4096m GgImagineBatch.jar "DATA=D:\diglib\zootaxa\temp" DT=BD CACHE=./BatchCache FM=R 
![image](https://user-images.githubusercontent.com/4609956/36837574-0b3c47be-1d3d-11e8-8303-8eaa27c760b7.png)

**Comment by gsautter** [comment]
First of all, my bad ... I exported a build with a debug flag switched on, which should not happen. This dialog will be gone with the next build.

In technical terms, this is not really a question. It's simply a visualization of how verification of glyph to Unicode mapping works inside the PDF font decoder. The glyph from the PDF font is rendered (left) and then compared to the corresponding glyph from comparison fonts (FreeSerif, FreeSans, FreeMono, in the middle) based upon bitmap overlay. The rightmost third visualizes a size adjusted pixel-wise precision/recall comparison, with black pixels being matches, green pixels spurious, and red pixels misses.
Again, this is just a debug helper I for once failed to deactivate before exporting a build. However, it is very possible to extend this into an interactive font decoding mode should we deem that functionality desirable.
