### ISSUE TITLE
image quality deterioration

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#46]
@gsautter why is this phylogenetic tree so bad in our copy? 

original
![image](https://cloud.githubusercontent.com/assets/4609956/21888162/43840522-d8c3-11e6-96c1-9091fe5d137c.png)

BLR copy https://doi.org/10.5281/zenodo.239114
![image](https://cloud.githubusercontent.com/assets/4609956/21888183/5db7ccee-d8c3-11e6-9296-4876c024f802.png)

**Comment by gsautter** [comment]
Need to check ... need to have a go at this very PDF anyway, see #44

**Comment by gsautter** [comment]
This phylogenetic tree is drawn as a vector graphics, including the individual characters of the labels (!!!). The renderer used to draw the outlines of a filled area for emphasis, which adds the obese thickness to the characters here. I've deactivated non-conditional outline-drawing now, and it comes up as supposed to.

However, this PDF is a real piece of work for another bunch of image and graphics related reasons revolving around the column separator lines ...

**Comment by myrmoteras** [comment]
can we fix this image so it shows up properly in BLR?

**Comment by gsautter** [comment]
Probably ... see #47

**Comment by gsautter** [comment]
Just tried to get this one straight again ... the bad image keeps ending up on Zenodo, even though copying or extracting it on my machine (and presumably on yours) produces a perfectly fine image ... has to be a Linux thing, I'm left to guess ...

**Comment by gsautter** [comment]
Guess this one has long been resolved, see also #47 ... laying it to rest.
