### ISSUE TITLE
new version of GGI does not work on batch

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#464]
@gsautter the new version of GGI does not work at all in batch mode

 - de-hyphenating line breaks
 - merging interrupted paragraphs
Error processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.4.pdf': de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
java.lang.NoSuchMethodError: de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider.detectDocumentStructure(DocumentStructureDetectorProvider.java:955)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider$StructureDetector.process(DocumentStructureDetectorProvider.java:281)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:606)
Processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.5.pdf'
 - loaded PDF of 8107053 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical page edge margings
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FFC899137A3EFFF2FFA6FFA85C57FFDE'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 16 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
Error processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.5.pdf': de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
java.lang.NoSuchMethodError: de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider.detectDocumentStructure(DocumentStructureDetectorProvider.java:955)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider$StructureDetector.process(DocumentStructureDetectorProvider.java:281)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:606)
Processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.6.pdf'
 - loaded PDF of 6885431 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical page edge margings
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is '7457FFA8FFD5EB14F15EC535FFED3722'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 10 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
Error processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.6.pdf': de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
java.lang.NoSuchMethodError: de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider.detectDocumentStructure(DocumentStructureDetectorProvider.java:955)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider$StructureDetector.process(DocumentStructureDetectorProvider.java:281)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:606)
Processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.7.pdf'
 - loaded PDF of 1294778 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical page edge margings
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is '6446FFEAFF800E47FFE0FFC1FF897407'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 8 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
Error processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.7.pdf': de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
java.lang.NoSuchMethodError: de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider.detectDocumentStructure(DocumentStructureDetectorProvider.java:955)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider$StructureDetector.process(DocumentStructureDetectorProvider.java:281)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:606)
Processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.8.pdf'
 - loaded PDF of 3248450 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical page edge margings
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is '9C12FFCBF211564F341A4206FFD7990C'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 8 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
Error processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.8.pdf': de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
java.lang.NoSuchMethodError: de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider.detectDocumentStructure(DocumentStructureDetectorProvider.java:955)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider$StructureDetector.process(DocumentStructureDetectorProvider.java:281)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:606)
Processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.9.pdf'
 - loaded PDF of 645909 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical page edge margings
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FFDA685D6937FFDDD529A079FFAD4B50'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 9 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
Error processing document 'E:\diglib\zootaxa\temp\zootaxa.4420.1.9.pdf': de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
java.lang.NoSuchMethodError: de.uka.ipd.idaho.im.analysis.PageAnalysis.areContinuousLayout(Lde/uka/ipd/idaho/im/ImRegion;Lde/uka/ipd/idaho/im/ImRegion;)Z
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider.detectDocumentStructure(DocumentStructureDetectorProvider.java:955)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider$StructureDetector.process(DocumentStructureDetectorProvider.java:281)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:606)

D:\GoldenGateImagine20170823>
[GgImagineBatch.20180515-0651.out.zip](https://github.com/gsautter/goldengate-imagine/files/2003511/GgImagineBatch.20180515-0651.out.zip)

**Comment by myrmoteras** [comment]
see also https://github.com/gsautter/goldengate-imagine/issues/463 of the previous day

**Comment by myrmoteras** [comment]
here are some example files
[zootaxa.4420.1.7.pdf](https://github.com/gsautter/goldengate-imagine/files/2003516/zootaxa.4420.1.7.pdf)
[zootaxa.4420.1.8.pdf](https://github.com/gsautter/goldengate-imagine/files/2003517/zootaxa.4420.1.8.pdf)
[zootaxa.4420.1.9.pdf](https://github.com/gsautter/goldengate-imagine/files/2003518/zootaxa.4420.1.9.pdf)
[zootaxa.4420.1.10.pdf](https://github.com/gsautter/goldengate-imagine/files/2003519/zootaxa.4420.1.10.pdf)

**Comment by gsautter** [comment]
This has nothing to do with individual PDFs ... it's a versioning problem, i.e., some of your JARs got updated while others apparently did not. In this case, it looks like an outdated version of `ImImageMarkup.jar`, and the log you provided in #463 shows you updated the configuration (including document structure detector), but _not_ the base application. I also asked for the exact file size of `ImImageMarkup.jar` in #463 (should be 942121 bytes), and provided you a link to get that latest version from (http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20180514-0720.zip). Did you even look at that, or simply throw me another "does not work" ticket?

**Comment by gsautter** [comment]
Closing this one as a duplicate, it's clearly the same issue.
