### ISSUE TITLE
GG new built: Zootaxa that do not parse

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#465]
Here are a couple of PDF that did not process  at all. This hardly ever happened in the previous built of GGI. see also further down
`java -jar -Xmx10240m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\temp" DT=D CACHE=./BatchCache FM=R`

[zootaxa.4420.2.2.pdf](https://github.com/gsautter/goldengate-imagine/files/2026461/zootaxa.4420.2.2.pdf)
[zootaxa.4420.2.3.pdf](https://github.com/gsautter/goldengate-imagine/files/2026462/zootaxa.4420.2.3.pdf)
[zootaxa.4420.2.9.pdf](https://github.com/gsautter/goldengate-imagine/files/2026463/zootaxa.4420.2.9.pdf)
[zootaxa.4420.3.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2026464/zootaxa.4420.3.1.pdf)
[zootaxa.4420.3.3.pdf](https://github.com/gsautter/goldengate-imagine/files/2026465/zootaxa.4420.3.3.pdf)
[zootaxa.4420.3.4.pdf](https://github.com/gsautter/goldengate-imagine/files/2026466/zootaxa.4420.3.4.pdf)

**Comment by myrmoteras** [comment]
[zootaxa.4420.4.3.pdf](https://github.com/gsautter/goldengate-imagine/files/2026478/zootaxa.4420.4.3.pdf)


Processing document 'E:\diglib\zootaxa\temp0\zootaxa.4420.4.3.pdf'
 - loaded PDF of 2258989 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical watermarks on page margins
Assessing page content
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FFFD47424F0DFFC1FFEC4B73D037FFAD'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 7 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Add Document Meta Data'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Taxonomic Keys'
Error processing document 'E:\diglib\zootaxa\temp0\zootaxa.4420.4.3.pdf': de.uka.ipd.idaho.im.imagine.plugins.basic.RegionActionProvider.restructureBlock(Lde/uka/ipd/idaho/im/ImRegion;[Lde/uka/ipd/idaho/im/ImRegion;[Z[ZZCZ)Z
java.lang.NoSuchMethodError: de.uka.ipd.idaho.im.imagine.plugins.basic.RegionActionProvider.restructureBlock(Lde/uka/ipd/idaho/im/ImRegion;[Lde/uka/ipd/idaho/im/ImRegion;[Z[ZZCZ)Z
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider.markIfIsKey(KeyHandlerProvider.java:588)
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider.markIfIsKey(KeyHandlerProvider.java:379)
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider.markKeys(KeyHandlerProvider.java:350)
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider.markKeys(KeyHandlerProvider.java:141)
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider.access$0(KeyHandlerProvider.java:133)
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.KeyHandlerProvider$KeyHandler.process(KeyHandlerProvider.java:129)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:703)

**Comment by myrmoteras** [comment]
[zootaxa.4422.1.2.pdf](https://github.com/gsautter/goldengate-imagine/files/2026630/zootaxa.4422.1.2.pdf)
[zootaxa.4422.1.4.pdf](https://github.com/gsautter/goldengate-imagine/files/2026631/zootaxa.4422.1.4.pdf)
[zootaxa.4422.1.5.pdf](https://github.com/gsautter/goldengate-imagine/files/2026632/zootaxa.4422.1.5.pdf)
[zootaxa.4422.1.7.pdf](https://github.com/gsautter/goldengate-imagine/files/2026633/zootaxa.4422.1.7.pdf)
[zootaxa.4420.4.2.pdf](https://github.com/gsautter/goldengate-imagine/files/2026634/zootaxa.4420.4.2.pdf)
[zootaxa.4420.4.3.pdf](https://github.com/gsautter/goldengate-imagine/files/2026635/zootaxa.4420.4.3.pdf)
[zootaxa.4420.4.4.pdf](https://github.com/gsautter/goldengate-imagine/files/2026636/zootaxa.4420.4.4.pdf)
[zootaxa.4420.4.6.pdf](https://github.com/gsautter/goldengate-imagine/files/2026637/zootaxa.4420.4.6.pdf)
[zootaxa.4420.4.7.pdf](https://github.com/gsautter/goldengate-imagine/files/2026638/zootaxa.4420.4.7.pdf)
[zootaxa.4420.4.8.pdf](https://github.com/gsautter/goldengate-imagine/files/2026639/zootaxa.4420.4.8.pdf)
[zootaxa.4420.4.9.pdf](https://github.com/gsautter/goldengate-imagine/files/2026640/zootaxa.4420.4.9.pdf)
[zootaxa.4420.4.10.pdf](https://github.com/gsautter/goldengate-imagine/files/2026641/zootaxa.4420.4.10.pdf)

**Comment by myrmoteras** [comment]
@gsautter here the output log file is 112MB, here is the zip of it 

[GgImagineBatch.20180523-0744.out.zip](https://github.com/gsautter/goldengate-imagine/files/2029689/GgImagineBatch.20180523-0744.out.zip)

and here the files that did NOT parse, that is there is NO IMF file available.

[zootaxa.4422.2.10.pdf](https://github.com/gsautter/goldengate-imagine/files/2029690/zootaxa.4422.2.10.pdf)
[zootaxa.4422.2.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2029691/zootaxa.4422.2.1.pdf)
[zootaxa.4422.2.6.pdf](https://github.com/gsautter/goldengate-imagine/files/2029692/zootaxa.4422.2.6.pdf)

**Comment by gsautter** [comment]
This is the very same error that I already assumed in https://github.com/plazi/EJT-testbed/issues/270 , nad fixed with a configuration update.
Sorry this ever happened, definitely my bad. Must have lost sight of some dependencies over my day job ... so looking forward to Plazi being the latter again, you cannot imagine ...

**Comment by gsautter** [comment]
Regarding availability of temporary files, I think I explained before that GGI Batch now (cache) stores every document after each processing step. That by default happens in `<GGI>/BatchCache/TempDocs/<PdfName>`, and these cached intermediate results can be loaded into GGI by means of previously explained and following procedure:
- copy `<GGI>/BatchCache/TempDocs/<PdfName>/entries.txt` to `<GGI>/BatchCache/TempDocs`
- rename `<GGI>/BatchCache/TempDocs/<PdfName>` to `<GGI>/BatchCache/TempDocs/<PdfName>.imdir`
- rename above copy of `<GGI>/BatchCache/TempDocs/<PdfName>/entries.txt` to `<PdfName>.imd`

Afterwards, you can load the document status cached by the batch as an Image Markup Directory.

**Comment by myrmoteras** [comment]
That means I have to fix those files manually? I might be able to do this, but rather have a new built that produces proper conversions..
