### ISSUE TITLE
garbled image

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#47]
@gsautter is there a way to fix this image? Is part of the Swiss 2016 species https://doi.org/10.5281/zenodo.167770

**Comment by gsautter** [comment]
Looks like another bitmap issue, will check.

**Comment by gsautter** [comment]
I decoded this PDF in early December, and got the images out fine. Just need to find a way of getting them on the server, but I think that's doable.

To replace the figures on Zenodo, you only have to remove the `httpUri` attribute from the captions of the affected images, and they will be re-uploaded, with the good PNG this time.

**Comment by myrmoteras** [comment]
ok, please let me know, when this is done. Or I need to do something. It would be be good to have this early next week when they disseminate the list with links to our treatments

**Comment by gsautter** [comment]
Done ... #46 will have to wait a little, until today's Zootaxa are through.
