### ISSUE TITLE
file does not open in GG

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#471]
These two files do not open in GG. Can you please check. This is needed for the disscussion with SIB and building another corpus of literature for Arcadia

[GgImagine.20180606-1135.out.zip](https://github.com/gsautter/goldengate-imagine/files/2075556/GgImagine.20180606-1135.out.zip)

[wellcomeOpenResearch.8f4b6b4d-33d1-4d75-b367-364503c35ac6_10210_-_aravind_venkatesan_v2.pdf](https://github.com/gsautter/goldengate-imagine/files/2075560/wellcomeOpenResearch.8f4b6b4d-33d1-4d75-b367-364503c35ac6_10210_-_aravind_venkatesan_v2.pdf)
[wellcomeOpenResearch.8f4b6b4d-33d1-4d75-b367-364503c35ac6_10210_-_aravind_venkatesan_v2_noReview.pdf](https://github.com/gsautter/goldengate-imagine/files/2075561/wellcomeOpenResearch.8f4b6b4d-33d1-4d75-b367-364503c35ac6_10210_-_aravind_venkatesan_v2_noReview.pdf)

**Comment by gsautter** [comment]
Very same as in https://github.com/plazi/EJT-testbed/issues/275 ... closing as duplicate.
