### ISSUE TITLE
files don't process in batch

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#476]
[GgImagineBatch.20180622-0602.out.zip](https://github.com/gsautter/goldengate-imagine/files/2126277/GgImagineBatch.20180622-0602.out.zip)
[zootaxa.4438.2.5.pdf](https://github.com/gsautter/goldengate-imagine/files/2126283/zootaxa.4438.2.5.pdf)
[zootaxa.4438.2.12.pdf](https://github.com/gsautter/goldengate-imagine/files/2126284/zootaxa.4438.2.12.pdf)

**Comment by gsautter** [comment]
The error with zootaxa.4438.1.12.pdf is the same one as in https://github.com/plazi/EJT-testbed/issues/275 , which should have been fixed with the update I installed on your machine last week. Guess this was running on your laptop?

**Comment by gsautter** [comment]
In zootaxa.4438.2.5.pdf, in turn, it was something completely different ... a weird edge case in bibliography detection that I've added a catch for now.

In the same effort, I also improved the bibliography tagger to become more robust against long main text passages that somewhat resemble bibliographic references on the purely morphological level.

Fix comes with next update.

**Comment by myrmoteras** [comment]
No. All was running on my pc

**Comment by myrmoteras** [comment]
.12 works now

**Comment by gsautter** [comment]
Glad the update finally got through ... closing like half a dozen tickets all at once.

**Comment by gsautter** [comment]
Also, I've uploaded a configuration update this morning that fixes the .5 issue and on top of that adds the "Skip & Next" functionality thought up by Yanell, not only to materials citation parsing, but also for the bibliography.
