### ISSUE TITLE
new version of GGI does not process PDF in many cases

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#478]
The GGI version updated June 26, 2018 seems to cause problems by not processing many of the Zootaxa.

[GgImagineBatch.20180627-0820.out.zip](https://github.com/gsautter/goldengate-imagine/files/2139972/GgImagineBatch.20180627-0820.out.zip)
[zootaxa.4441.2.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2139973/zootaxa.4441.2.1.pdf)
[zootaxa.4441.2.6.pdf](https://github.com/gsautter/goldengate-imagine/files/2139974/zootaxa.4441.2.6.pdf)
[zootaxa.4441.2.7.pdf](https://github.com/gsautter/goldengate-imagine/files/2139975/zootaxa.4441.2.7.pdf)
[zootaxa.4441.2.8.pdf](https://github.com/gsautter/goldengate-imagine/files/2139976/zootaxa.4441.2.8.pdf)
[zootaxa.4441.2.10.pdf](https://github.com/gsautter/goldengate-imagine/files/2139977/zootaxa.4441.2.10.pdf)
[zootaxa.4441.2.12.pdf](https://github.com/gsautter/goldengate-imagine/files/2139978/zootaxa.4441.2.12.pdf)

**Comment by gsautter** [comment]
Judging from the log file, this looks like a glitch in the bibliographic citation tagger ... investigating.
