### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#48]
@gsautter in this article, the images are missing

![image](https://cloud.githubusercontent.com/assets/4609956/21896651/6c4afdb6-d8e7-11e6-9011-0cb84e9cd59a.png)

![image](https://cloud.githubusercontent.com/assets/4609956/21896705/9592fc78-d8e7-11e6-9b8a-a68a016fb81d.png)

[LBB_0048_2_1339-1492.pdf](https://github.com/gsautter/goldengate-imagine/files/702148/LBB_0048_2_1339-1492.pdf)

**Comment by gsautter** [comment]
As it seems, the images simply fail to decode. Their parameters say they are JPG2000, but they don't seem to decode in that format. Might be a hard one to resolve, this ...
