### ISSUE TITLE
file does not open Bibliotheken der Schweiz_ Innovation durch Kooperation

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#484]
This file does not open in GGI: https://drive.google.com/open?id=106ZViPtCmFiNY3D6SvG4oLtaq-jqnxPm 

the source epub file is here: https://www.degruyter.com/view/product/489794?format=EBOK 

the GGI log is 
[GgImagine.20180819-1305.err.zip](https://github.com/gsautter/goldengate-imagine/files/2300272/GgImagine.20180819-1305.err.zip)

**Comment by gsautter** [comment]
Thanks for the logs. Looks like the resurrection of an older problem (https://github.com/plazi/EJT-testbed/issues/297) ... please make sure to use the latest version of `ImageMarkup.jar`. Most likely, you can copy it from your other machine, where it has long been fixed.
