### ISSUE TITLE
images problems

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#49]
@gsautter 
might you have a quick look why the images of these species do not show up? It is sort of relevant, because this species has been announced the species of the year here in Switzerland

http://tb.plazi.org/GgServer/html/03E3DC50FFBFFF85FECBFEFAE30BCE69

![image](https://cloud.githubusercontent.com/assets/4609956/21976445/216baf50-dbd2-11e6-971f-a17d40e16822.png)

**Comment by gsautter** [comment]
The Zenodo DOI in http://tb.plazi.org/GgServer/xml/03E3DC50FFBFFF85FECBFEFAE30BCE69 tells me the PDF already _is_ on Zenodo.

In that case, you have to add the `Zenodo-Dep` ID in "Edit -> Edit Document Metadata" to link the IMF to the already existing deposition.
