### ISSUE TITLE
authors missing in bibRefs submitted to GBIF

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#490]
@gsautter can you please check this issue out? May be it is an issue at GBIF?

From: Mark Costello <m.costello@auckland.ac.nz>
Sent: Sunday, September 2, 2018 11:35:29 AM
To: Donat Agosti
Cc: Tri Arfianti
Subject: Citations on publications in GBIF from Plazi 
 
Dear Donat,
 
I hope you are doing well, wherever you are living these days. 
 
Tri, who is doing her PhD with me, just noticed that when references are cited in GBIF coming from Plazi they seem to serve the last authors name only. Perhaps thiws is a glitch someplace in the process?
 
1.https://www.gbif.org/dataset/1aed0317-9b87-477a-9b2f-6db0381ce85c#citation
 
Original description: https://europepmc.org/abstract/med/27701314
 
2.  https://www.gbif.org/dataset/2cda8cb6-fde6-4cb1-8301-1c91bb3c2889#citation
 
Original description: https://biotaxa.org/Zootaxa/article/view/zootaxa.4306.2.4
 
and many more.
Best wishes
Mark 
<>  ><>  ><>  ><>  ><>  ><>  ><>  ><>  ><> ><>
Dr Mark J. Costello, Institute of Marine Science,

**Comment by gsautter** [comment]
Resolved via DwC-A re-export, archive was outdated and hadn't incorporated above update yet.
