### ISSUE TITLE
pages scrambled

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#491]
in the example OCRed by Abbyy (Isabel , https://drive.google.com/open?id=1x0pJrPD7RL7VbRlxFTjnZY6GubL-EuI4 ) pages with the scrambling show up

![image](https://user-images.githubusercontent.com/4609956/45428015-9aa00100-b6a0-11e8-9e87-03d0de5fb0c9.png)

others look like this

![image](https://user-images.githubusercontent.com/4609956/45428043-abe90d80-b6a0-11e8-964c-77e2d8c0d77c.png)

I just run GGI using glyphs only, and document structure discovery.
We might look at this when you are here Thursday night?

**Comment by gsautter** [comment]
If this is a scanned document, most likely "Render Glyphs Only" is not the way to go ... all the more because it applies to born-digital PDFs.

Please try using "PDF Documents (scanned)" and option "Use Embedded OCR".
Apart from that, it looks as though the word boundaries given in the OCR output do not align all too well with the actual words on the scan. However, this might also be an effect of opening the PDF in the wrong mode.

**Comment by myrmoteras** [comment]
we need to check this document - it takes incredibly long running it in the way you explained

**Comment by gsautter** [comment]
If the scans are good (clean and upright), you can un-tick the "Enhance Scans" option, which should considerably speed up matters.
Scan enhancement works on pixels and thus the higher the scan resolution, the longer it takes. I can well imagine that ii takes a good while on 400 DPI scans.

**Comment by myrmoteras** [comment]
but now I get this result by running detect document structure

![image](https://user-images.githubusercontent.com/4609956/45432100-4f3e2080-b6a9-11e8-9dc2-14de5b8a5b4d.png)
[GgImagine.20180912-1359.out.zip](https://github.com/gsautter/goldengate-imagine/files/2375681/GgImagine.20180912-1359.out.zip)

**Comment by gsautter** [comment]
I'm rather sure that loading the PDF as a scan doesn't have all too much to do with this exception, which appears to happen during the block analysis step of structure detection, for what it seems on the very first page.

Unfortunately, the log doesn't include a full stack trace (for whatever reason, I'll check), so I cannot right away pinpoint the problem.

Would it be possible to send me just a part of the IMF (I figure 433 pages might be quite a lot)? You can truncate an IMF like this:
- un-zip the IMF to some temporary folder
- delete all the page images from, say, `page0010.png` onward
- delete all the scans from the same page onward
- if it's too big, delete `source.pdf` as well (decoding proper appears to have worked just fine)
- re-zip the temporary folder under a different name (you don't want to overwrite the complete IMF ...)
- send me the that latter ZIP
I'll then adjust the CSV files so it opens again and start analyzing the problem.

**Comment by myrmoteras** [comment]
Let's look at this tomorrow

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gsautter** [comment]
Resolved, was lacking plug-in update.
