### ISSUE TITLE
garbeled text in input

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#492]
this latest nature paper does not convert properly using render glyphs only

![image](https://user-images.githubusercontent.com/4609956/45665340-b4ae6900-bb10-11e8-82f2-8e0312ed63dd.png)

[s41559-018-0667-3.pdf](https://github.com/gsautter/goldengate-imagine/files/2391231/s41559-018-0667-3.pdf)

do not decode works better
![image](https://user-images.githubusercontent.com/4609956/45665411-0fe05b80-bb11-11e8-845c-9d55ca5ae2a5.png)

**Comment by gsautter** [comment]
Solved ... was a glitch in glyph synonymization, i.e., the merge-up of characters whose glyph renders with the exact same sequence of commands.

Fix comes with next build.
