### ISSUE TITLE
bibRef: doi excluded from bibRef zootaxa.4482.3.2

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#495]
![image](https://user-images.githubusercontent.com/4609956/45797853-daba4180-bca7-11e8-8e45-74172402dbd1.png)

The doi is still not in the bibRef, that is being included in a separate bibRef

**Comment by gsautter** [comment]
Looks like something has been tinkered with in this one ... specifically, in the top two paragraphs the DOIs do start a new `bibRef`, but do _not_ start a new paragraph, whereas the tagger marks `bibRef`s only along paragraph boundaries. Cannot wait to get my hands on this IMF.

**Comment by gsautter** [comment]
In my test, the `bibRef`s were tagged perfectly fine, i.e., including the DOIs, so something strange must have happened, maybe due to some annotations left behind on startover after some failure.

**Comment by gsautter** [comment]
A problem I've found, though, is that only the top part of the bibliography is detected (up to including "Naruse, T. (2010)") ... the reason for this is the many references to "Ng", the only last name known to me that comes without a vowel or at least a "y".
This is not a problem with one or two references thanks to bridging, but the 10 "Ng" references in this one are just too much for the bridging mechanisms - such a large bridge-out would only wreck havoc in most cases.

I'll see to it that the reference tagger accepts "Ng" for a last name ...

**Comment by gsautter** [comment]
Added "Ng" as well as "Krk" (mainly a Croatian island, but might also occur as last name) to last names dictionary, the only two proper names known around that come without a vowel.

**Comment by gsautter** [comment]
Comes with next update.

Please make sure to remove all reference-related annotations before re-running "Parse Bibliography". "Edit -> List Annotations" can help a great deal in that effort.
