### ISSUE TITLE
image extration problems

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#50]
here is another articles/journals that causes problems with images that are nor turned, paragraphs that do not show up (between nomenclature, descriptions ss)

http://tb.plazi.org/GgServer/summary/4F26FFAFFFD17F27FFCFFFD4FFC8FFD5

**Comment by gsautter** [comment]
Well, the figures _do_ show up, see http://tb.plazi.org/GgServer/html/B31F87D7FFD27F21FFB6FC09FE5EFB2F ... what exactly is missing?

If some text comes up yellow, it has been mistaken for in-figure labels for some reason. You can easily salvage main text gone missing this way by splicing it into the main text stream. "Click Successor" is the function for that kind of task. It's available if you have the text streams showing and click on a single word. Said word should be the one _after_ which you intend to re-insert the missing text.

**Comment by myrmoteras** [comment]
fig 2a does not show up.
![image](https://cloud.githubusercontent.com/assets/4609956/21987172/ac5a362e-dc02-11e6-81f1-284367441090.png)

and in the imf it die not rotate properly, and with that caused an overlap with the caption.

The paragraphs between nomenclature and the following subsubsection does not show up in TB

**Comment by gsautter** [comment]
I just checked all of this again, and it seems absolutely fine. Added a key treatment as well.
