### ISSUE TITLE
collection Code: remove DNA as collection

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#500]
please remove DNA as a collection. It looks akward to have DNA in the text listed as collection, Or at most restrict this to DNA in materialsCiation subSubSection.
thanks 
![image](https://user-images.githubusercontent.com/4609956/46195509-d247b380-c304-11e8-989a-10b604557172.png)

**Comment by gsautter** [comment]
Turns out "DNA" actually is a valid institution code ... my GrBio dump lists it as "Department of Natural Resources, Environment, The Arts and Sport", an Australian herbarium.

Anyway, I've added a filter that excludes "DNA" just like it already did with "USA".
