### ISSUE TITLE
java bug report

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#503]
This is the latest report I have never seen. It might have to do that I run out of disc space?!
d

java.lang.NullPointerException
        at de.uka.ipd.idaho.im.util.ImDocumentIO.getPageImageAttributes(ImDocumentIO.java:1467)
        at de.uka.ipd.idaho.im.util.ImDocumentIO.storeDocument(ImDocumentIO.java:1262)
        at de.uka.ipd.idaho.im.util.ImDocumentIO.storeDocument(ImDocumentIO.java:1014)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:691)
Running Image Markup Tool 'Check Annotation Nesting'
Indexing Annotations by Text Stream
Checking Annotations
Storing document to 'E:\diglib\zootaxa\temp21\zootaxa.4482.1.2.pdf.imf'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Error processing document 'E:\diglib\zootaxa\temp21\zootaxa.4482.1.2.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.im.util.ImDocumentIO.getPageImageAttributes(ImDocumentIO.java:1467)
        at de.uka.ipd.idaho.im.util.ImDocumentIO.storeDocument(ImDocumentIO.java:1262)
        at de.uka.ipd.idaho.im.util.ImDocumentIO.storeDocument(ImDocumentIO.java:1049)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:748)
Processing document 'E:\diglib\zootaxa\temp21\zootaxa.4482.1.3.pdf'
 - loaded PDF of 17715153 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical watermarks on page margins
Assessing page content
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'BA192D21825C7658FF85DC1CFFB7C426'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 20 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Add Document Meta Data'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Taxonomic Keys'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 23 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 1 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 59 taxon names
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Clean Table Annotations'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Remove Duplicate Annotations'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Check Annotation Nesting'
Indexing Annotations by Text Stream
Checking Annotations
Storing document to 'E:\diglib\zootaxa\temp21\zootaxa.4482.1.3.pdf.imf'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Error processing document 'E:\diglib\zootaxa\temp21\zootaxa.4482.1.3.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.im.util.ImDocumentIO.getPageImageAttributes(ImDocumentIO.java:1467)
        at de.uka.ipd.idaho.im.util.ImDocumentIO.storeDocument(ImDocumentIO.java:1262)
        at de.uka.ipd.idaho.im.util.ImDocumentIO.storeDocument(ImDocumentIO.java:1049)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:748)
Processing document 'E:\diglib\zootaxa\temp21\zootaxa.4482.1.4.pdf'
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (opto/loopnode.hpp:612), pid=8080, tid=0x0000000000004f54
#  guarantee(n != NULL) failed: No Node.
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode windows-amd64 compressed oops)
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\GoldenGateImagine20170823\hs_err_pid8080.log
#
# Compiler replay data is saved as:
# D:\GoldenGateImagine20170823\replay_pid8080.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

D:\GoldenGateImagine20170823>

**Comment by gsautter** [comment]
That's a case of Java proper crashing, yes ... could be it has to do with a lack of disk space, but it's kind of hard to tell.
In general such Java crashes are notoriously hard to reproduce, let alone debug. I'm afraid that starting over and seeing whether or not it occurs again is the best option going about this.
