### ISSUE TITLE
mc abort

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#504]
@gsautter here something new that is a show stopper
[zootaxa.4464.1.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2433939/zootaxa.4464.1.1.pdf)

No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting

D:\GoldenGateImagine20170823>java -jar -Xmx10240m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\temp22" CACHE=./BatchCache FM=U
Loading parameters
GoldenGATE Imagine core created, configuration is Default.imagine
Image Markup Tool 'StructureDetector' loaded
Image Markup Tool 'MetaDataAdder' loaded
Image Markup Tool 'KeyHandler' loaded
Image Markup Tool 'ParseBibliography.imTool' loaded
Image Markup Tool 'MarkBibRefCitations.imTool' loaded
Image Markup Tool 'MarkTaxonNames.imTool' loaded
Image Markup Tool 'TableAnnotCleaner' loaded
Image Markup Tool 'RemoveDuplicateAnnots' loaded
Image Markup Tool 'TreatmentTaggerStyled.imTool' loaded
Image Markup Tool 'ExtractMaterialsCitations.imTool' loaded
Image Markup Tool 'CheckAnnotNesting' loaded
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.1.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.10.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.11.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.2.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.3.pdf' processed before, skipping
Processing document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.4.pdf'
 - document restored from previous batch run
 - assigned document style 'zootaxa.2013.journal_article'
Skipping previously-run Image Markup Tool 'Detect Document Structure'
Skipping previously-run Image Markup Tool 'Add Document Meta Data'
Skipping previously-run Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Error processing document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.4.pdf': Annotation size out of bounds: 0
java.lang.RuntimeException: Annotation size out of bounds: 0
        at de.uka.ipd.idaho.gamta.Gamta.newAnnotation(Gamta.java:415)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.trimUrlOrDoi(RefParse.java:2404)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getBrokenURLsAndDOIs(RefParse.java:2334)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getBaseDetails(RefParse.java:2215)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:973)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:944)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:41)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:36)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseAnalyzer.process(RefParseAnalyzer.java:59)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$AnalyzerDocumentProcessor.process(AnalyzerManager.java:207)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:329)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:549)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:703)
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.5.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.6.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.7.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.8.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.1.9.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.1.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.10.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.11.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.3.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.4.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.5.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.6.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.7.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.8.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.2.9.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.1.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.10.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.2.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.3.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.4.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.5.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.6.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.7.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.8.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.3.9.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.1.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.10.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.11.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.2.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.3.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.4.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.5.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.6.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.7.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.8.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4462.4.9.pdf' processed before, skipping
Document 'E:\diglib\zootaxa\temp22\zootaxa.4463.1.1.pdf' processed before, skipping
Processing document 'E:\diglib\zootaxa\temp22\zootaxa.4464.1.1.pdf'
 - document restored from previous batch run
 - assigned document style 'zootaxa.2013.monograph'
Skipping previously-run Image Markup Tool 'Detect Document Structure'
Skipping previously-run Image Markup Tool 'Add Document Meta Data'
Skipping previously-run Image Markup Tool 'Mark Taxonomic Keys'
Skipping previously-run Image Markup Tool 'Parse Bibliography'
Skipping previously-run Image Markup Tool 'Mark Bibliographic Citations'
Skipping previously-run Image Markup Tool 'Mark Taxon Names'
Skipping previously-run Image Markup Tool 'Clean Table Annotations'
Skipping previously-run Image Markup Tool 'Remove Duplicate Annotations'
Skipping previously-run Image Markup Tool 'Mark Treatments (Headings Only)'
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting
Detecting materials citation paragraphs
No indicator annotations found at all, aborting

**Comment by gsautter** [comment]
Got it ... I ran into the same thing today working on #501 . It's already fixed, comes with the next update.
