### ISSUE TITLE
batch problems: show stopper zootaxa.4450.2.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#505]
this runs to materialCitation and then hangs

[zootaxa.4450.2.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2441802/zootaxa.4450.2.1.pdf)

**Comment by gsautter** [comment]
At first glance, this looks like a combinatoric runaway just like the one I already fixed for the reference author lists (in #501).

I'll include this PDF in the batch trouble issue #501 , closing here.
