### ISSUE TITLE
decoding: this file has only yellow text

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#51]
![image](https://cloud.githubusercontent.com/assets/4609956/21984690/67a4e14c-dbf7-11e6-8049-e656ec399fde.png)
[entomologischeBlätterColeoptera.112.1.203.pdf](https://github.com/gsautter/goldengate-imagine/files/708460/entomologischeBlatterColeoptera.112.1.203.pdf)

**Comment by gsautter** [comment]
I'll have to investigate why the whole page gets mistaken for in-figure labeling. In any case, you can change such things via "Set Text Stream Type", which is available if you have the text streams showing and click on any single word in the text in question.

**Comment by gsautter** [comment]
The reason this one comes up as all-graphics is the cut markers on the page edges, which are rendered as a single graphics object and thus span the entire page ... is this PDF a pre-print proof or something?

Apart from this, I'll try and add a filter for such cases, or split up the graphics object. Have to check which one works better.

**Comment by myrmoteras** [comment]
when I change text stream to main text, all changes, but not boxes and paragraphs show up!?

**Comment by gsautter** [comment]
Right ... If you drag a box around a text block and use "Mark Region -> block", the paragraphs, etc. will be added automatically.

Not ideal, I know, Will try and fix the graphics thing, which is the root cause of all this havoc.

**Comment by myrmoteras** [comment]
here it is  - a bit an unusal way to get this done. 

http://tb.plazi.org/GgServer/summary/702A2F63821E5D72FFF0FFEE741DA81D

**Comment by gsautter** [comment]
Yeah, right ... the standard way is coming up in the next build.
