### ISSUE TITLE
caption: PLATE does not work as start signal for caption zootaxa.4482.1.1.pdf

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#510]
![image](https://user-images.githubusercontent.com/4609956/46736195-af1feb00-cc98-11e8-91a3-4e1a119d24ad.png)

caption that begin with PLATE are not marked up as caption
FigureCitation with Plate X are not found 

possible to make this happen?

zootaxa.4482.1.1.pdf

**Comment by gsautter** [comment]
Thanks for another example, plates are high on my list anyway.

**Comment by gsautter** [comment]
This one works now, including the citations of the in-line figure numbers given inside the plate captions.

Comes with next build.
