### ISSUE TITLE
bibRef: split bibRefs zootaxa.4457.1.12

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#512]
DOI and handles are treated as individual bibRefs FF8E2D7FFFCBFFE278374E08E625FFDA  

![image](https://user-images.githubusercontent.com/4609956/46814403-ed8cd700-cd78-11e8-91a0-61dc792da40c.png)
[zootaxa.4457.1.12.pdf](https://github.com/gsautter/goldengate-imagine/files/2469511/zootaxa.4457.1.12.pdf)

![image](https://user-images.githubusercontent.com/4609956/46814604-65f39800-cd79-11e8-9240-ca28cc4ab4d4.png)

https://zenodo.org/record/1458151

**Comment by gsautter** [comment]
Got it ... this doesn't go wrong in "Parse Bibliography", but downstream in "Check Annotation Nesting" ... small wonder I could never reproduce this in isolation ...
"Check Annotation Nesting" is but the last part of the batch, and apparently messed up the references. I fixed this now, comes with next update.
