### ISSUE TITLE
processing time: identifying candidates paragraph

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#516]
@gsautter how long should I let the program run when it is doing the "identifying candidates paragraph" in a document of 176MB? 331 pages?

**Comment by gsautter** [comment]
Is this "Parse Bibliography" or the materials citations? Anyway, this might take a little while. Especially with the bibliography, it has to start somewhere mid-document the latest in case there is an excessive appendix, so this is a good few paragraphs to investigate.
