### ISSUE TITLE
decoding failure

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#52]
@gsautter in this articles, the male sympol cannot be decoded, and the line art are inverse

http://tb.plazi.org/GgServer/summary/FF9BFFA15853FFACFF89FFEBFFE7FFA2

**Comment by gsautter** [comment]
What kind of a PDF is this, exactly? Take a look at https://zenodo.org/record/46298 or 	http://dx.doi.org/10.5281/zenodo.46298 , please ... little I could test with that, I|m afraid.

Apart from that, can't you fix the male symbol via "Edit -> Edit Embedded Fonts"?

**Comment by myrmoteras** [comment]
Just get it from the IMF, this was an error when the final pdf has been uploaded.

**Comment by gsautter** [comment]
Apparently, this is another case of high-range encoded characters (>255) losing the connection to the underlying font. Has been fixed a while ago, so now this one decodes (and corrects) as supposed to.
