### ISSUE TITLE
taxonomy time series ejt-464

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#523]
@gsautter can you have a look why we get this odd timeseries
![image](https://user-images.githubusercontent.com/4609956/47360516-fdd57800-d6cf-11e8-9b19-faf01543fd64.png)

from this  http://treatment.plazi.org/GgServer/html/03C6575CFFE3FFE5C1BBE619FED4FCCB

**Comment by myrmoteras** [comment]
part of the problem I could solve, is that it included TWO treatments (properly identification of treatment is an issue, see previous https://github.com/plazi/EJT-testbed/issues/332 

the other see

**Comment by gsautter** [comment]
Got it ... I'll have to check the document as to why the second treatment (heading) failed to recognize as such, as in the PDF it looks pretty much standard and should recognize like the others.

**Comment by gsautter** [comment]
As to the timeline, for what it looks like the culprit is the nesting of `bibRefCitation` annotations (author and year) inside `treatmentCitation` annotations (author, year, and page).
This is perfectly fine from the markup point of view and pretty much what it should be. I suspect the problem in the XSLT creating the timeline, will investigate.

**Comment by myrmoteras** [comment]
Many of the treatments are not discovered and need to edited manually, not just in this article, but in the last couple I did over the last few days

**Comment by gsautter** [comment]
In that case, could be I have to adjust the template parameters for treatment headings. Will check using this document. But first the timeline, simply because it's public facing.

**Comment by myrmoteras** [comment]
I added the year and author into the treatmentCitation annotation and it solves the issue.

**Comment by gsautter** [comment]
Done, the XSLT falls back to the plain treatment citation string now if the attributes are absent. Since the treatment splitting issue has its own ticket (https://github.com/plazi/EJT-testbed/issues/332), this one's done.
