### ISSUE TITLE
bibRef: doi in separate paragraphs and bibRef zootaxa.4504.2.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#525]
![image](https://user-images.githubusercontent.com/4609956/47465452-60706600-d7ed-11e8-8787-642589c7b3a3.png)

**Comment by gsautter** [comment]
Again, this is absolutely correct, as paragraphs detect solely based upon text flow and word wrapping characteristics. See https://github.com/plazi/EJT-testbed/issues/308
