### ISSUE TITLE
figure citation / word boundaries

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#528]
can you help to set this figure citations right? 
![image](https://user-images.githubusercontent.com/4609956/47606629-2df58180-da16-11e8-9472-b98b87602512.png)
FFD2FF9D1015FFF28C64FF9ACE650454

**Comment by gsautter** [comment]
The word boundaries are a bit off, admittedly, but they are taken one-to-one from the embedded OCR. On top of that, it shouldn't do any harm that they are a little bit off, if most likely as a result of a proportional split between the digits and the dashes.
Just looks a bit odd when you zoom in in GGI, but shouldn't do any harm to the XML.

**Comment by gsautter** [comment]
As to the figure citations, I'll check.

**Comment by gsautter** [comment]
The problem with the figure citations lay in the words, namely in numbers joined over a comma like in "27,28" being connected in a single word ...
Using "Split Word" gets that right, and afterwards you can use "Annotate Figure Citation" to correct the latter.
