### ISSUE TITLE
font issue: cannot change font male

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#529]
FF8AFFEEE8465848FFC2A86AFF98FFA1

how can I fixt this c = male issue?
![image](https://user-images.githubusercontent.com/4609956/47609808-57c69c80-da46-11e8-8912-ec3959c6fde4.png)

**Comment by gsautter** [comment]
A look at the source PDF in acrobat might help ... it clearly shows these "C"s are exactly what they are supposed to ... please also note that there are both male and female symbols in this very paragraph:
![image](https://user-images.githubusercontent.com/5789714/47612148-9e32f000-da74-11e8-87ce-2b04a0e37a19.png)

**Comment by gsautter** [comment]
As to the empty font in general, I've fixed this last night already ... was an issue with substitute glyph names in TrueType fonts.
