### ISSUE TITLE
decoding error

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#53]
@gsautter this file does not decode at all, it stalls after very intense calculating before opening up

[Lysipomia mitsyae_Taxon.pdf](https://github.com/gsautter/goldengate-imagine/files/708652/Lysipomia.mitsyae_Taxon.pdf)

this is the last of the Swiss species 2016 project

**Comment by gsautter** [comment]
This PDF is an outright font mayhem ... not sure what all those fonts are used for, but what does strike the eye is that even Acrobat takes a good while to open this one. Just an extremely complex case.

The stall you observe might well be a memory issue. At least individual pages come up fine in my tests, if after hustling around the fonts for quite a while.

**Comment by gsautter** [comment]
It is indeed a memory error. Those 10 pages don't decode with 2GB. Just too many fonts, too many glyphs, too much cross referencing, too many streams.

As mentioned above, even Acrobat takes some 10 seconds on my machine to show the first page.

**Comment by myrmoteras** [comment]
Can we solve this?

**Comment by gsautter** [comment]
If 8GB of RAM on the batch decoder don't cut it, I'm not sure what else we might try ... this doesn't necessarily mean the IMF will be enormously large, it's just that the internal structure of this PDF is extremely complex.
