### ISSUE TITLE
treatments do not show up

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#530]
@gsautter I just uploaded an article that shows up in BLR but the treatments do not show up in TB
https://zenodo.org/record/1486150#.W-sLNdpKjAT

**Comment by gsautter** [comment]
Not sure what happened, but after triggering a re-sync via the server console, it shows now: http://treatment.plazi.org/GgServer/summary/FFC99A7C23786053D626FFFAFFC7A545
