### ISSUE TITLE
missing images - images not uploaded to BLR

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#54]
@gsautter in this case https://zenodo.org/record/238712#.WIT5X7YrK0o / http://tb.plazi.org/GgServer/summary/FFA7085B97097C08FFE19F343655FFA4

Figures 2 - 10 are not uploded to BLR and thus are not linked to.

This is part of the Swiss taxa 2016 project. http://www.naturalsciences.ch/organisations/swiss-systematics/new_species_switzerland

**Comment by gsautter** [comment]
Also in this one, the figures were not assigned to captions, so the Zenodo uploader couldn't handle them (see #24)
