### ISSUE TITLE
taxonomicNames: false positive, missing, incomplete phytoxa.319.3.2

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#541]
here is a phytotaxa article which has several taxonomic name issues. Run the file using 
`java -jar -Xmx10240m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\temp" CACHE=./BatchCache FM=U`

![image](https://user-images.githubusercontent.com/4609956/50044263-46cafc80-0081-11e9-8a09-91b9f127115d.png)

http://d2ouvy59p0dg6k.cloudfront.net/downloads/065_2017_thismia_nigricoronata_phytotaxa__1__1.pdf

**Comment by myrmoteras** [comment]
missing names
https://doi.org/10.1046/j.1439-0469.2001.00155.x 

j.zool.syst.evol.res.j.1439-0469.2001.00155.x

![image](https://user-images.githubusercontent.com/4609956/50096125-449aa680-0217-11e9-9125-b4e263ee0370.png)

**Comment by gsautter** [comment]
The second example looks like a really hard one ... the taxon names are not in italics, and I don't see any sub specific ranks (with a distinctive label like "subsp." in front of it), either.
The only thing FAT has left to go at is the families (the "idae" suffix is sufficiently distinctive), hit CoL with those to get the child genera, and then recurse with the genera present in the document, hitting CoL for their child the species. If the catalogs are incomplete, that necessarily results in misses in such cases. The cost of precision.

**Comment by gsautter** [comment]
The first one is interesting, though, for two reasons:
- The subgenera come labeled as "subg.", but not in parentheses, which is a syntax I've never seen before. Will have to adjust the patterns to handle that.
- The names come with subgenus _and_ section, which I've never seen an example for, either. This is apparently so rare than we falsely assumed there could only be a maximum of one below-genus epithet in any one name. Will have to adjust the patterns to handle this one as well.

**Comment by gsautter** [comment]
Apart from that, I'm amazed how you got the batch to even process that Phytotaxa article ... usually it quits when it doesn't find a template, and I don't think we have one for Phytotaxa, or do we?

**Comment by myrmoteras** [comment]
I don't think we have one. But the format is similar to Zootaxa. I had of course to add metadata etc. by hand

**Comment by gsautter** [comment]
This is a _really_ strange false positive, yes :-D ... sounds like a case for the stopword list. On the other hand, I cannot seem to forget about that Lepidoptera genus by the name of "Data" ...
I'll check how this gets in. Fortunately, the `_evidence` and `_step` attributes are pretty helpful in this regard.

**Comment by myrmoteras** [comment]
https://zenodo.org/record/2522190

FFB9FFD5FFE8FFE9FF9F2B32FFEAB472 

This needs many of the names fixed, I just made sure that the new species is correct and I could upload it

**Comment by gsautter** [comment]
Thanks.

A hint for such cases: If you remove the metadata (or just break it, e.g. remove the title and year of publication), you can safely put the IMF on the server, as without valid metadata it won't go anywhere, neither Zenodo nor the XML stages (TB, GBIF, RefBank, etc.).
To remove (or break) the metadata, you need to go via "Edit -> Edit Document Attributes" and remove all the attributes starting with `mods:`.

I'm aware this is a little bit of a hack, but for sharing an IMF via our own infrastructure, it's a safe way of preventing propagation.

**Comment by gsautter** [comment]
I got FAT to process the Phytotaxa quite nicely now, looks like the botany extension works as supposed to.

The authorities come out nicely as well, at least the ones with author, year, and page (including basionym authors). The micro citations with journal and volume on top of that are another step.
