### ISSUE TITLE
docAuthor not detected jPalaeogeography.s42501-018-0014-2

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#543]
![image](https://user-images.githubusercontent.com/4609956/50044762-cf00d000-0088-11e9-9c00-6a9ecbf92b83.png)

**Comment by gsautter** [comment]
Looks like this little "ID" pictogram gets in the way ...

On top of that, how exactly are the authors detected? I don't think we have a template for Journal of Palaeogeography, do we?

**Comment by gsautter** [comment]
If you extracted the authors from inside the metadata dialog, they will be annotated in the next build. That was one of the fixes I mentioned yesterday.
