### ISSUE TITLE
treatment display error  FFA6FFD6FD73FFC3874EFFD8FFE56E14

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#546]
this Checklist article does not work. I just uploaded it and is in Zenodo () but in Treatmentbank I only get this

![image](https://user-images.githubusercontent.com/4609956/50376624-b0ae4d80-060f-11e9-9630-f2cc445df585.png)

and for treatements

![image](https://user-images.githubusercontent.com/4609956/50376628-c9b6fe80-060f-11e9-9614-18aad8717a6f.png)

**Comment by gsautter** [comment]
This is a pure backlog issue ... I fixed the XML element nesting yesterday (the TaxPub conversion problems Terry reported), and consequentially had to initiate an all-out update. It's simply that this document hasn't made it through the queue just yet.

**Comment by myrmoteras** [comment]
Super – tx
d

**Comment by gsautter** [comment]
I just found out why the queue is clogged ... the worker (background job that works off the queue) is hung on some ZooBank lookup, and has been for hours. I'll kick it back to life.

**Comment by gsautter** [comment]
After making sure the ZooBank lookups have a timeout (most system have this internally, but ZooBank simply hangs indefinitely for some reason), update events are back to processing now.

The treatments are there, even though the taxon names don't show in the summary page yet. The latter is an index matter, it will resolve after the update load goes down.
