### ISSUE TITLE
figures do now show up science.362.6417.897.supp

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#552]
![image](https://user-images.githubusercontent.com/4609956/50755736-3bbb5480-125a-11e9-9c11-22f8dafe69c0.png)
[science.362.6417.897.supp.pdf](https://github.com/gsautter/goldengate-imagine/files/2731844/science.362.6417.897.supp.pdf)

**Comment by gsautter** [comment]
These phylogenetic analyses are PDF native vector graphics rather than images, the bitmap images proper are fine. Looking into the graphics now.

**Comment by gsautter** [comment]
The graphics (lines) as well as their labels (the taxa) appear to render outside the page, far up and right. I'll try and figure out why.

**Comment by gsautter** [comment]
Got it ... PDF form objects (essentially autonomously packaged bags of content, not necessarily with input fields, that can be rendered in one or more places) can come with a scaling matrix according to the specification.
And this PDF finally is one that uses such a transformation matrix ... another rare-ish corner case to finally tick off, now that we finally have a test case.

**Comment by gsautter** [comment]
Implemented, comes with next build.
