### ISSUE TITLE
upload to BLR issue: missing alternate identifier

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#56]
@gsautter please have a look at the issue of uploading articles to BLR which have an ISBN / ISSN number. It might be, that in the upload the alternate identifier might not be defined.

We discovered this because sometimes edits of articles cannot be saved in BLR. The issue is in this case, that the ISBN number has been entered to the doc metadata and appears in BLR, but without a definition.

![image](https://cloud.githubusercontent.com/assets/4609956/22325112/02cec450-e3ad-11e6-9f46-73d627721c15.png)

This is the original email

Dear Krzysztof and Lars 
Sorry to bother you again about editing. 
In this submission, I would like to change Access rights from closed access to open access. 
https://zenodo.org/deposit/259616
I can change it, but then I can not save nor publish it. When I hover over the save button, a red forbidden signal comes up.
Any ideas how to solve this?

this the response 

Dear Donat,

It appears that this record has an alternate identifier (the last one in the list), without a type selected for it (eg. "is part of this upload", "references this upload", etc). Selecting a type will make the upload "Save"-able. The missing visual error indicator is probably a UI issue we'll have to look into, thank you for contacting us about this.

Best regards,
Alex Ioannidis

**Comment by gsautter** [comment]
The way this is implemented right now, the Zenodod uploader add all identifiers present in a document proper (DOI, Plazi UUID (wrapped as LSID), ISBN, etc.) as **alternative identifiers** for the PDF. The relationship is the same for all these identifiers, and the Zenodo API would refuse the upload if the relationship was invalid (i.e., not on the list of pre-defined identifier relationships). Not sure how that relationship could possibly get lost.

Also, the relationship is listed just fine in the JSON returned by the API, see https://zenodo.org/api/deposit/depositions/259616

So to me this looks like the Zenodo web UI doesn't properly display the data, which in itself is correct (judging by what the API returns, see the above link).

**Comment by gsautter** [comment]
Has to be resolved on the Zenodo end ... if our upload data wasn't valid, their API wouldn't accept it at all.
