### ISSUE TITLE
document decoding strategy: bulletinMuseumNationalHistoireNaturelle 1974

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#562]
@gsautter how can we process them? I can't find a way to get them into GGI in a meaningful way

[BMZOO_S003_1974_T216_N144.415-418.pdf](https://github.com/gsautter/goldengate-imagine/files/2759390/BMZOO_S003_1974_T216_N144.415-418.pdf)

**Comment by gsautter** [comment]
These options worked for me:
![image](https://user-images.githubusercontent.com/5789714/51259246-088c6a00-19ac-11e9-996b-0d17d8c70e95.png)

The word boundaries are slightly off in some places, especially for words in italics, but otherwise it comes up fine.

**Comment by myrmoteras** [comment]
this is what I get with this config

![image](https://user-images.githubusercontent.com/4609956/51302992-492fc600-1a34-11e9-83f8-ee7fb4789c5d.png)

**Comment by myrmoteras** [comment]
might this have to do to that somewhere a copy of the page images is in the system that needs to be removed first?

**Comment by gsautter** [comment]
There might be a few broken images left in <GGI>/PageImages/, yes, and removing them surely won't do any harm.

However, the images in this one are double-encoded (two compression algorithms after one another), and that feature I only implemented on Christmas, so it's not out just yet.

I've put it on the server for you: FFF36117FF86C54BFFF3FA53C9351833
