### ISSUE TITLE
GGI new build

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#564]
@gsautter might it be possible to get a new build of GGI in the next couple of days so I can process the first batch of 2019 EJT and we can make use of the new MC engine taking into consideration there changes layout. We need to process them pretty close to when new issues appear. We also need to reprocess some of the 2018 issues, not to speak of the backlog

**Comment by gsautter** [comment]
Done, new build is out, with the following additions:
- FAT handles botany now
- the document style manager has a more user friendly UI now, including visual aids for template editing
- the new 2018 EJT style is included
- materials citation handling can use style parameters now, and runaways are prevented
- the PDF decoder can now handle chained decoding filters on bitmap images
- some additions and refinements in treatment structure detection

**Comment by gsautter** [comment]
I'm aware both FAT and the improvements to the document style manager would have justified a new build each ... guess the family issues did get to me after all ...

**Comment by myrmoteras** [comment]
@gsautter it does not work
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Donat>d:

D:\>cd GoldenGateImagine20170823

D:\GoldenGateImagine20170823>
D:\GoldenGateImagine20170823>java -jar -Xmx10240m GgImagineBatch.jar "DATA=E:\diglib\europeanJournalOfTaxonomy\temp4" CACHE=./BatchCache FM=U
Loading parameters
GoldenGATE Imagine core created, configuration is Default.imagine
Image Markup Tool 'StructureDetector' not found,
check entry 'imageMarkupTools' in GgImagineBatch.cnfg

D:\GoldenGateImagine20170823>


[GgImagine.20190128-1058.out.zip](https://github.com/gsautter/goldengate-imagine/files/2802428/GgImagine.20190128-1058.out.zip)
