### ISSUE TITLE
font broken

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#567]
in this Candollea, run with todays version of GGI, i got the following

![image](https://user-images.githubusercontent.com/4609956/52377368-f363a200-2a64-11e9-8ad5-e67699a4463a.png)

[candollea.c2018v732a11.pdf](https://github.com/gsautter/goldengate-imagine/files/2838486/candollea.c2018v732a11.pdf)

**Comment by gsautter** [comment]
Looks like a threading issue ... running single-thread, it works perfectly fine ...

**Comment by gsautter** [comment]
IMF is on the server: FFC67E38E72BFFC69F59FFC5FFA4FE18

**Comment by gsautter** [comment]
Switching GGI to single threaded fixes this one. Looking into what to synchronize ...

**Comment by gsautter** [comment]
Apparently the third-party library the PDF facilities use for representing the basic file structure are the culprit, not even any Java (JRE) native libraries or graphics widgets ... anyway, synchronizing a single small (and actually rather fast) passage if the PDF decoding routine finally fixed this epic conundrum.

**Comment by myrmoteras** [comment]
ok - I run another Candollea and it works now. https://zenodo.org/record/2561038#.XGBCL7tKjAQ  but does not show up in TB http://tb.plazi.org/GgServer/summary/FFF0F779D245FFEAFFBCFFD5D472AB11

**Comment by gsautter** [comment]
The document is on the Frankfurt server, see #574
