### ISSUE TITLE
graphics orientation wrong

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#568]
this phylogeny seems to mislead GGI

![image](https://user-images.githubusercontent.com/4609956/52378343-b4831b80-2a67-11e9-8aec-b56bb3730747.png)

![image](https://user-images.githubusercontent.com/4609956/52378367-c369ce00-2a67-11e9-8c14-328ff6a90bc3.png)
[candollea.c2018v732a11.pdf](https://github.com/gsautter/goldengate-imagine/files/2838544/candollea.c2018v732a11.pdf)

**Comment by gsautter** [comment]
Not a bug, this is a feature ... in pursuit of getting the text to the most readable orientation, i.e., left to right ...
