### ISSUE TITLE
columns not split, Candollea

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#569]
![image](https://user-images.githubusercontent.com/4609956/52378587-602c6b80-2a68-11e9-8260-5caa755e13db.png)
[candollea.c2018v732a11.pdf](https://github.com/gsautter/goldengate-imagine/files/2838555/candollea.c2018v732a11.pdf)

**Comment by gsautter** [comment]
Here my test ...

![image](https://user-images.githubusercontent.com/5789714/52398682-2e43f500-2aba-11e9-91ce-1dea72d06aca.png)

**Comment by gsautter** [comment]
As opposed to #567 , this doesn't seem to be a threading issue. Even running single threaded, it still messes up. Looking into even more subtle reasons ...

**Comment by gsautter** [comment]
A stray template draft got in the way, one that we started making once ...
