### ISSUE TITLE
images with text on it: how to deal with it

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#570]
how do I have to markup the image?

![image](https://user-images.githubusercontent.com/4609956/52378878-2b6ce400-2a69-11e9-96a4-7f536d77b157.png)

[candollea.c2018v732a11.pdf](https://github.com/gsautter/goldengate-imagine/files/2838575/candollea.c2018v732a11.pdf)

**Comment by gsautter** [comment]
Nothing special to do here ... it's a figure made up of multiple tiles, and will go to Zenodo with all the text and graphics in the area.
