### ISSUE TITLE
Treatments and article summary do now show up in TB

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#574]
No treatments nor the article summary is shown in TB.
http://tb.plazi.org/GgServer/summary/FFF0F779D245FFEAFFBCFFD5D472AB11
The article has been processed and is in BLR https://zenodo.org/record/2561038#.XGBCTLtKjAS

**Comment by myrmoteras** [comment]
I hope I can upload the latest EJT articles tonight (Feb 10) so I can show them tomorrow at lunch time at EJT.

**Comment by gsautter** [comment]
You uploaded it to Frankfurt ... here it is: http://plazi.de/GgServer/summary/FFF0F779D245FFEAFFBCFFD5D472AB11

You can upload it to Boston as well without incurring any duplication issues. Just pick the right server on logging in.
