### ISSUE TITLE
SubSection types feature request

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#576]
might it be possible to enhance the subSection tagger with additional languages for the tagging:
in the case of spanish articles, the referencias =references, resultados = results, materiales = materials, resumen = abstract, palabras clave = keywords?

**Comment by gsautter** [comment]
Sure, I'll add these keywords to the rules.

Just out of curiosity: how many documents in Spanish are we expecting? Might have to extend quite a few lexicons for that purpose if there are many more to come ...

**Comment by gsautter** [comment]
Done, comes with next update.

**Comment by myrmoteras** [comment]
Right now there is a focus on English, but we need to expand at some point.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gsautter** [comment]
There might come the time to redo document segmenting ... right now this is based on simple match rules, first implemented in 2007 and occasionally adjusted, extended, and refined ever since.
