### ISSUE TITLE
bibRef: author not properly tagged

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#577]
here are the bibRef authors not properly tagged

120CFFA6FFF172788E67FFBCFFC21003

![image](https://user-images.githubusercontent.com/4609956/52536545-3de26880-2d5c-11e9-997f-f395e80ed1d5.png)

![image](https://user-images.githubusercontent.com/4609956/52536547-4a66c100-2d5c-11e9-8568-5cbbc8f20846.png)

![image](https://user-images.githubusercontent.com/4609956/52536555-5e122780-2d5c-11e9-9772-f0d9d0acf823.png)

![image](https://user-images.githubusercontent.com/4609956/52536559-6cf8da00-2d5c-11e9-9082-eb7ec4e5b4bd.png)

**Comment by gsautter** [comment]
Another case of a name part order flip gone bad. I'll look into it this week. Good to have one more test case beside #542 .

**Comment by gsautter** [comment]
Done ... was quite a hard one to get working alongside the mechanisms intended to catch single-word author names alongside broken ones.
