### ISSUE TITLE
document metadata: can not add metadata

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#579]
I can't add metadata.

![image](https://user-images.githubusercontent.com/4609956/52790622-4d68f680-3067-11e9-8777-800d5484a0bb.png)

[candollea.c2018v732a5.pdf](https://github.com/gsautter/goldengate-imagine/files/2865222/candollea.c2018v732a5.pdf)
[GgImagine.20190214-1435.out.zip](https://github.com/gsautter/goldengate-imagine/files/2865227/GgImagine.20190214-1435.out.zip)

**Comment by gsautter** [comment]
Fixed with the new build created after #582
