### ISSUE TITLE
broken images / graphics

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#58]
@gsautter 
in this image, the cladogram/phylogenetic tree got lost

![image](https://cloud.githubusercontent.com/assets/4609956/22471899/2dce765c-e7d4-11e6-9a19-95bc80833e08.png)
https://zenodo.org/record/265393#.WJCv2BkrLAQ

would it be better to mark such thinks as image rather than graphic?

**Comment by gsautter** [comment]
I cannot seem to reproduce this ... the line graphics decodes and renders just fine here, and it also exports to bitmap perfectly normal. I'll check the export renderer on the server when it comes back up, as that's the only place left where it might go wrong.

**Comment by gsautter** [comment]
Finally resolved ... repaired the whole thing just to make sure to get the graphics right, stored it on the server, reloaded it, removed the HTTP URI, and finally got the correct phylogentic tree up on Zenodo ... see https://zenodo.org/record/344618
