### ISSUE TITLE
GGI batch processing

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#581]
[zootaxa.4555.4.6.pdf](https://github.com/gsautter/goldengate-imagine/files/2874266/zootaxa.4555.4.6.pdf)
does not process

Processing document 'E:\diglib\zootaxa\2019\temp\zootaxa.4555.4.6.pdf'
 - loaded PDF of 8929215 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical watermarks on page margins
Assessing page graphics
Assessing page content
Handling flipped page content
Storing figures and graphics
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is '126CFF969535FFDEFFFCFFB7C21F131F'
Storing conversion result to temporary folder
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 13 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - identifying table notes
 - indexing paragraph end words
 - indexing document words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings, emphases, and super- and subscripts
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Add Document Meta Data'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Taxonomic Keys'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Identifying candidate paragraphs
Building candidate bibliographies
Assessing reference style
Style-filtering candidate bibliographies
Marking bibliography
Parsing references
Extracting basic details
Assessing basic details
Selecting number detail blocks
Filtering number details
Classifying part designators
Getting author lists
Filtering author lists
Collecting reference structures
Selecting reference structures
Filling in author list gaps
Determining primary detail separator
Extracting volume references
Parsing volume references
Extracting basic details
Assessing basic details
Selecting number detail blocks
Filtering number details
Classifying part designators
Getting author lists
Filtering author lists
Collecting reference structures
Selecting reference structures
Filling in author list gaps
Collecting title and journal/publisher blocks
Determining title terminator
Selecting titles and journals/publishers
Position-filtering number details
Cleaning up volume references
Classifying references
Annotating details
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
 ==> TreeFAT instance is ICZN
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 8 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 1 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets below genus
Indexing labeled epithets and potential epithets below species
Indexing taxonomic status labels
Indexing status labeled epithets
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 17 taxon names
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Clean Table Annotations'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Remove Duplicate Annotations'
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Extracting countries
Emphasis-filtering countries
Extracting regions
Filtering regions
Storing document data
Storing page data
Storing word data
Storing region data
Storing annotation data
Storing font data
Storing page images
Storing page image data
Storing supplement data
Storing supplements
Document stored to temporary folder
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Extracting countries
Emphasis-filtering countries
Extracting regions
Filtering regions
Getting document person names
Detecting materials citation paragraphs
Marking materials citations
Setting materials citation attributes
Error processing document 'E:\diglib\zootaxa\2019\temp\zootaxa.4555.4.6.pdf': null
java.lang.NullPointerException
        at java.lang.String$CaseInsensitiveComparator.compare(Unknown Source)
        at java.lang.String$CaseInsensitiveComparator.compare(Unknown Source)
        at java.util.TreeMap.getEntryUsingComparator(Unknown Source)
        at java.util.TreeMap.getEntry(Unknown Source)
        at java.util.TreeMap.containsKey(Unknown Source)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.addMaterialsCitationAttributes(MaterialsCitationHandler.java:10198)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.processTreatment(MaterialsCitationHandler.java:763)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.process(MaterialsCitationHandler.java:569)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$MonitorableAnalyzerDocumentProcessor.process(AnalyzerManager.java:228)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:333)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:296)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:549)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:709)

**Comment by gsautter** [comment]
I just ran this one, and it went through all the way. Maybe an update that's not yet online, I did fix something in back reference resolution last week for https://github.com/plazi/EJT-testbed/issues/396

**Comment by myrmoteras** [comment]
when you write you should ran it and went through: Did you upload it?

**Comment by gsautter** [comment]
Not yet ... one thing after the other. But I'll make sure to upload all five IMFs soon as I'm done fixing.
