### ISSUE TITLE
figure does not show up

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#59]
@gsautter in this new Nature article, the figures do now show up

http://tb.plazi.org/GgServer/summary/1D24282A9B47FFE5F56CFFEE5841FFA4

the first three seem so far not to be in BLR.
https://zenodo.org/record/265124#.WJBTrhkrLAQ

There has been a problem with linking the images to the captions. I could fix this., but seem not yet to help
A problem might be, because the caption is across two colums, and thus the captions do not who up completely in the BLR record https://zenodo.org/record/265126#.WJBU4RkrLAQ

**Comment by gsautter** [comment]
The solution for those captions is to mark the columns individually and then merge them, i.e., connect the text streams via "Set Successor" and then merge the `caption` annotations.

**Comment by gsautter** [comment]
Guess this worked ...
