### ISSUE TITLE
specimenCode: range

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#592]
here is another way to list a series of specimens

![image](https://user-images.githubusercontent.com/4609956/53691993-a6839a80-3d88-11e9-8c7f-cf3268653e68.png)

3F5A2711FFCC9800FFB2FFF8FFA6FFCD

**Comment by gsautter** [comment]
During extraction, such sequences are actually already treated as specimen code ranges, if only in absence of the letter block prefix on the second number. I'll include the latter option.

**Comment by gsautter** [comment]
Done, comes with next build.

**Comment by gsautter** [comment]
You meant C3635F69FFCA980AFDA0F9A6FB76F90B, right?
