### ISSUE TITLE
collectingRegion: remove from bibRefs

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#594]
can the collectingRegion annotation in bibRefs in the subSubSection type=reference_group be omitted?

![image](https://user-images.githubusercontent.com/4609956/53692392-6d9af400-3d8f-11e9-801c-b4076622be82.png)

**Comment by gsautter** [comment]
Sure, that's an easy filter to add.

**Comment by gsautter** [comment]
Done, for `bibRef`s in general.
