### ISSUE TITLE
batch processing issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#595]
[GgImagineBatch.20190312-0514.out.zip](https://github.com/gsautter/goldengate-imagine/files/2955218/GgImagineBatch.20190312-0514.out.zip)

this file die not process zootaxa.4565.4.1 on https://drive.google.com/open?id=0B_yrQwn4yBySTlBxMnhWd3o1Zkk (30MB)

 batch

**Comment by gsautter** [comment]
Reproduced and fixed, comes with next build.
