### ISSUE TITLE
new species not tagged in upload

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#596]
these new species are not tagged

http://tb.plazi.org/GgServer/summary/77272D76FF88C810FF902344FFD27511

**Comment by gsautter** [comment]
Looks rather like an error with treatment boundary detection, the underlying cause being a failure to identify the treatment headings as such.

**Comment by myrmoteras** [comment]
further new species not tagged in the
http://tb.plazi.org/GgServer/static/newToday.html 

http://tb.plazi.org/GgServer/html/03EE87F77A6BFF95FF4CF8D0ED63FA86

**Comment by gsautter** [comment]
Trust that one was processed before yesterday's FAT rank glitch fix? Fixed that rank now, and it shows.

**Comment by myrmoteras** [comment]
Is there a new built?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gsautter** [comment]
Yes ... the one including the updated QC tool, see https://github.com/plazi/arcadia-project/issues/32 ... out since early yesterday afternoon.
