### ISSUE TITLE
batch processing: failure because of MC zootaxa.4568.2.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#598]
[zootaxa.4568.2.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2986727/zootaxa.4568.2.1.pdf)
[GgImagineBatch.20190320-0635.out.zip](https://github.com/gsautter/goldengate-imagine/files/2986729/GgImagineBatch.20190320-0635.out.zip)

**Comment by gsautter** [comment]
Got it ... the MCs don't crash, but they stall. A tiny data error in `17°48'01"N 71°26'80"W` ends up everything afterwards regarded as a quoted label, conflating dozens of MCs in one, which then ends up stalling in detail detection.
The error being the 80 seconds of arch in the longitude, which throws off the coordinate tagger. As a consequence, the double quote (here actually indicating seconds of arch) are regarded as the start of a label quote, conflating everything from there onward right up to the next country "HAITI".

**Comment by gsautter** [comment]
I'll have to try and find a way of catching such trouble makers to prevent minor data errors from wrecking major havoc. Maybe tag such faulty coordinates no matter what and mark them as errors further downstream ... little we could do about them, however, as we have no way of knowing what the correct value would be.

**Comment by myrmoteras** [comment]
for us, it means to tag them as geo-coordinates but not to annotate them with the digital degrees. At some points we could flag them as faulty so GBIF would now.

**Comment by gsautter** [comment]
OK, will change it that way.

However, it also highlights the general need to add some sanity checking to the marking of label quotes, so to catch similar cases in a generic kind of way ... there might be other sources of stray double quotes out there.

**Comment by gsautter** [comment]
Coordinate Tagger is adjusted, now tagging erroneous coordinates with minutes or seconds of arc 60 and above, if under indication of an error in the annotation attributes.
