### ISSUE TITLE
batch processing: files do not process: zootaxa.4568.2

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#599]
[zootaxa.4568.2.8.pdf](https://github.com/gsautter/goldengate-imagine/files/2986828/zootaxa.4568.2.8.pdf)
[zootaxa.4568.2.9.pdf](https://github.com/gsautter/goldengate-imagine/files/2986829/zootaxa.4568.2.9.pdf)
[zootaxa.4568.2.2.pdf](https://github.com/gsautter/goldengate-imagine/files/2986835/zootaxa.4568.2.2.pdf)
[GgImagineBatch.20190320-0712.err.zip](https://github.com/gsautter/goldengate-imagine/files/2986840/GgImagineBatch.20190320-0712.err.zip)

**Comment by gsautter** [comment]
First thing I see in the log is that you must be using an old `GgImagineBatch.cnfg` ... it does not load (or execute) the error checker. I added that in the latest build.
You can also add it to the existing file if you change the value of `imageMarkupTools` to `StructureDetector MetaDataAdder KeyHandler ParseBibliography.imTool MarkBibRefCitations.imTool MarkTaxonNames.imTool TableAnnotCleaner RemoveDuplicateAnnots TreatmentTaggerStyled.imTool ExtractMaterialsCitations.imTool CheckAnnotNesting CheckDocumentErrors` (plus the surrounding quotes) in `GgImagineBatch.cnfg`.

**Comment by gsautter** [comment]
As to the individual files:
- `zootaxa.4568.2.2.pdf` appears to have a problem early on in structure detection, will investigate
- `zootaxa.4568.2.8.pdf` stops right in the middle of font decoding (at least in the lag you linked above), no error there
- `zootaxa.4568.2.9.pdf` I cannot even seem to find in the log, looks like you stopped the batch before it got there

**Comment by gsautter** [comment]
Fixed `zootaxa.4568.2.2.pdf` ... there is an empty 5x5 figure in the edge of Page 18 (for whatever reason ...) that evaporated un-caught in page structure detection, catching that now. Comes with next build.
