### ISSUE TITLE
merging blocks not possible

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#6]
@gsautter why can't I merge blocks here? I just opened the doc and tried to detect structure which provided wrong blocks

![image](https://cloud.githubusercontent.com/assets/4609956/20791720/ad13875e-b7be-11e6-89c1-4229c7d17170.png)
[Klopfstein_2016_Revision-Dimophora.pdf](https://github.com/gsautter/goldengate-imagine/files/624341/Klopfstein_2016_Revision-Dimophora.pdf)

Journal: Austral Entomology

**Comment by gsautter** [comment]
Make sure both "block" and "paragraph" regions are showing, as well as text streams ... that tells GGI that you are working on page structure and text flow, and that you might thus be interested in respective options.

One of the downsides of trying not to clutter the context menu all too heavily ...
