### ISSUE TITLE
fonts issue: Mixing up fonts

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#60]
in this document there is a mixup of fonts

![image](https://cloud.githubusercontent.com/assets/4609956/22550338/d7e318ba-e94f-11e6-8697-45fd7dd6cbde.png)

@millerjeremya  can provide the link of a copy of the document?

**Comment by myrmoteras** [comment]
[Esyunin_&_Kazantsev_2008_Art_16_245_250.pdf](https://github.com/gsautter/goldengate-imagine/files/747800/Esyunin_._Kazantsev_2008_Art_16_245_250.pdf)
[Fu_Zhang_&_Zhu_2009_Art_17_169_173.pdf](https://github.com/gsautter/goldengate-imagine/files/747801/Fu_Zhang_._Zhu_2009_Art_17_169_173.pdf)

**Comment by gsautter** [comment]
Mixed script documents are always a bit tricky ... will check.

**Comment by gsautter** [comment]
The fonts in these two PDFs provide no Unicode mapping at all, and glyphs are in a pretty wild order, numbered sequentially. They require full OCR decoding for each and every character, with no real hints whatsoever. That's where errors can happen. You'll have to correct this via "Edit -> Edit Embedded Fonts".

As a test, you can easily copy and paste a snippet of text from Acrobat to Notepad++, ad if what comes up is binary gibberish, fonts are a nightmare.

**Comment by gsautter** [comment]
Little we could do about this issue ... especially with Latin and Cyrillic script used alongside one another. That's where a pair of human eyeballs is just the only viable means of getting it perfectly right.
