### ISSUE TITLE
upload to serv1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#601]
what are the data to enter to upload to srv1

![image](https://user-images.githubusercontent.com/4609956/54668297-db188580-4aee-11e9-82f9-dbf12b6de0c1.png)

@gsautter can you please include this option into the next built, and may be remove the CS und plazi.de option?

**Comment by gsautter** [comment]
Same as you've always used, the accounts have migrated.

However, the host is `https://srv1.plazi.org/GgServer/proxy` (you're missing the last part), and you need to add port number 443.
