### ISSUE TITLE
file does not batch process: hangs at importing page words zootaxa.4521.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#609]
[zootaxa.4521.1.1.pdf](https://github.com/gsautter/goldengate-imagine/files/3007433/zootaxa.4521.1.1.pdf)

**Comment by gsautter** [comment]
Processes just as fine as #610 (I started wit the smaller file). Also here, do you have any log file that might shed some light as to what went wrong in your processing attempt?
