### ISSUE TITLE
rank wrong; need be checked

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#615]
it seems that there is a problem with the right rank. Donald mentioned this earlier, and now we have at least one other example ,where a species rank is set as rank=genus

http://treatment.plazi.org/GgServer/xml/03FBE152FFDDFFFCFDE3FD57FE7206C5
in FFC2992AFFCEFFE8FF8DFFCCFFD9010B

I haven't modified taxonomicName in this EJT

I will check the other EJT I processed today

**Comment by gsautter** [comment]
There are a god few ranks wrong ... see https://github.com/plazi/Plazi-Communications/issues/809 .
I'm all over the latter, and will run some server side repair scripts soon as I figure out the source of the problem.

**Comment by myrmoteras** [comment]
ejt-507 is at the species level

**Comment by gsautter** [comment]
I think it's only one very specific rule (out of FAT's over a dozen) that incurs this problem, figuring out the exact reasons as I type this.

**Comment by myrmoteras** [comment]
I fixed 507. only few names have the wrong rank, unfortunately those which are new species or which have a treatment. Often the names in the reference_group are ok

**Comment by gsautter** [comment]
Indeed only very few names were ever affected, (a) because it was only one rule out of over a dozen that incurred the error and (b) because even that happened only under specific circumstances

Anyway, fixed it now, comes with next update.

**Comment by gsautter** [comment]
Planning scripted server side repair now.

**Comment by gsautter** [comment]
Server side update script is running, should be done by morning.
