### ISSUE TITLE
figures do not show up in Zenodo journal.pone.0213314 Mini mum

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#617]
FFC1FF8EFF930A48FF9E0658DC6D6955

in this case the file is uploaded, and even in GBIF which is great

**Comment by gsautter** [comment]
Sorry about this ... had a few background updates running on the server because of https://github.com/plazi/Plazi-Communications/issues/809 and associates. The IMF in question was simply waiting in line ...
