### ISSUE TITLE
bibRef parsing does not work: jBritishTarantualaSociety.34.1.19-34

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#619]
![image](https://user-images.githubusercontent.com/4609956/55626315-7b3b0380-57ab-11e9-9f36-750976151649.png)

the document is uploaded to TB:  jBritishTarantualaSociety.34.1.19-34

**Comment by gsautter** [comment]
Solved, see https://github.com/gsautter/goldengate-imagine/issues/621
