### ISSUE TITLE
bibRef does not work: zjls.182.1.76-106

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#621]
the bibRef is not working. The article is uploaded to TB. 

![image](https://user-images.githubusercontent.com/4609956/55709353-69926f80-59e8-11e9-86cd-5bd1c8dae75d.png)

**Comment by myrmoteras** [comment]
the file is now uploaded to TB
[GgImagine.20190408-1153.out.zip](https://github.com/gsautter/goldengate-imagine/files/3053859/GgImagine.20190408-1153.out.zip)

**Comment by gsautter** [comment]
Are you sure that log belongs to this document? I do see the error from the prompt, but cannot seem to find the logged reference strings document ...

**Comment by gsautter** [comment]
OK, got the document ... the root problem is that the bibliography is detected in the wrong place, namely the paragraphs nicely and sequentially numbered 1-128 in the appendix right _after_ the actual bibliography.
Will have to add content checks (most likely presence of author names and years) in bibliography detection to get this type of problem right ...

**Comment by gsautter** [comment]
Added scoring for presence of years and multi-word author names to bibliography tagging now, works like a charm.
Also added catch for inconclusive author list style vote to volume reference extraction (root cause of originally reported problem).
Both to come with next build.
