### ISSUE TITLE
figureCitation does not work: zjls.182.1.76-106 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#622]
in this journal, the figureCitation do not work in all cases
![image](https://user-images.githubusercontent.com/4609956/55709481-afe7ce80-59e8-11e9-90d3-1457e1b8f45e.png)

the file is uploded to TB.

**Comment by gsautter** [comment]
The problem here might be that "FIGS" is actually made up of two words ("F" in font size 10, "IGS" in font size 8) to emulate small-caps ... I'll look into it.

**Comment by gsautter** [comment]
Looks like automated citation detection wasn't fully prepared to handle multi-part words yet ... fixed that now, comes with next build.
