### ISSUE TITLE
new built: missing frankfurt server

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#623]
in the new built, the Frankfurt server is not included.

In order to include it, does the http check box to be ticked?
for the details see: https://github.com/plazi/Plazi-Communications/wiki/GoldenGATE-Imagine#batch-processing-zootaxa upload

**Comment by gsautter** [comment]
I realized that already, will be corrected in the very next build.

**Comment by gsautter** [comment]
Added now.
