### ISSUE TITLE
file does not decode properly: missing images Nature nature.s41586-019-1067-9

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#629]
![image](https://user-images.githubusercontent.com/4609956/55976721-61a72980-5c8d-11e9-8d48-a15719e20037.png)

https://drive.google.com/open?id=1gpb2jYcE0N_5FoOLaExs9779tGu9MFt0

also, if you process this, can you look into the two bibliographic reference sections in the paper?

This is a paper about a new homo species in the headlines right now - would be good to get it up in the not too far future

**Comment by myrmoteras** [comment]
I think these are all captions on the other side....

**Comment by myrmoteras** [comment]
@gsautter this is a challenge to you.
1. Fig 6 and 7 do not decode, that is they are not here
2. Captions are in two columns, sometimes in three parts. Not entirely sure how to mark them up.

Let me know how to proceeed. 
I did some work on this - but since the two figures are not here, we might have to start from scratch?

**Comment by gsautter** [comment]
Indeed, the placement of the captions is confusing, got me even when looking at it in Acrobat.

Figures 6 and 7 are something like 4,000 by 5,000 pixels, i.e., 20 MegaPixels, which is pretty much gigantic. I'll try and get them to decode.

**Comment by gsautter** [comment]
You can mark surely mark figures around the vector graphics and export them, the context menu should provide respective options if `image` regions are showing.

**Comment by gsautter** [comment]
The best way of marking the captions might be marking the parts individually, then using "Make Successor" to connect them, and "Extend caption" to make one annotation span them all.

**Comment by myrmoteras** [comment]
@gsautter can you get this article converted so all images show up I then finish it. Would like to see this species in TB and GBIF

**Comment by gsautter** [comment]
Document is on server (UUID `4968D603841AF705FFDD316CFFB0CA16`), done up to bibliography and citations. That said, the images should already be on Zenodo.

**Comment by gsautter** [comment]
Done.
