### ISSUE TITLE
upload of files from GGServer does not work

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#63]
@gsautter updating local cache in the download menu from GGI, once a filter has been used, does not work

![image](https://cloud.githubusercontent.com/assets/4609956/22685049/1d9c1c08-ed1f-11e6-97b3-11fdb6053d31.png)

may be linked to the same problem as in issue regarding GGE?

**Comment by gsautter** [comment]
Nope, most definitely not ... just could be something was busy in the background. The filters only apply to the document _list_ in the lower half of the dialog and have no effect _at all_ on loading a document proper. They just help you find some document, that's all. Loading works entirely by document ID, and document ID alone.

Also, if some filter behaves strange, try clicking the "Filter" button and see if anything changes.
