### ISSUE TITLE
taxonomicName parsing does not work zoosystema2019v41a8

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#631]
this name is only partially marked up:
![image](https://user-images.githubusercontent.com/4609956/56090926-a2c75580-5ea8-11e9-8936-4f05a90a55f8.png)

I extend to include the entire name, parse the name and only get the data from the genus before
![image](https://user-images.githubusercontent.com/4609956/56090999-74964580-5ea9-11e9-90be-3862b016b1f7.png)
,

**Comment by gsautter** [comment]
Looks like a downstream problem of #631 / #633 to me ... extending the annotation to include species epithet and authority does not automatically correct the attributes. For the latter, use "Parse Taxon Name" from the context menu.

**Comment by myrmoteras** [comment]
parse taxon name does in such cases often nor work

**Comment by gsautter** [comment]
Well, I cannot seem to reproduce that, either ...

What "Parse Taxon Name" does under the hood is run FAT and the use the match that spans the whole of the existing annotation, so the two problems are more than related.
