### ISSUE TITLE
zootaxa upload java heap space zootaxa.4582.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#637]
[GgImagine.20190415-1537.out.zip](https://github.com/gsautter/goldengate-imagine/files/3080383/GgImagine.20190415-1537.out.zip)
![image](https://user-images.githubusercontent.com/4609956/56137385-03cc5780-5f95-11e9-8f31-71dab47b3b3f.png)

zootaxa.4582.1.1

**Comment by myrmoteras** [comment]
i will keep this file for tomorrow?!

**Comment by gsautter** [comment]
Sounds like an idea ... preciously little I can do from here.

I'll have to pend some quality time with your installation anyway ... we have close to a dozen issues I cannot seem to reproduce at all.
