### ISSUE TITLE
treatmentCitation not found zootaxa.4586.1.5

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#638]
![image](https://user-images.githubusercontent.com/4609956/56220402-b02b3e00-6068-11e9-8a95-8f3df924ef58.png)

in this case, the treatmentCitation has not been found

zootaxa.4586.1.5

**Comment by gsautter** [comment]
Please ask me such things directly, at least when I'm sitting right behind you.
