### ISSUE TITLE
specimenCode & trait mixup

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#639]
In this case, there is a mix up of specimen code and part of the trait

![image](https://user-images.githubusercontent.com/4609956/56220792-55dead00-6069-11e9-8b37-90d7d3236977.png)

in fishes, they add a body length (SL) to the MC

zootaxa.4586.1.5

**Comment by gsautter** [comment]
Already noted, and in the works, just interrupting to write this reply.
