### ISSUE TITLE
loading documenList can't be stoped without killing GGI(GGE

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#64]
@gsautter if the loading Document List From GoldenGate DIO does not work, this can't be stopped or aborted without having to kill the entire GGE/GGI and restart it.

![image](https://cloud.githubusercontent.com/assets/4609956/22685290/09f39ac2-ed20-11e6-9713-9a8197df53df.png)

**Comment by gsautter** [comment]
After the data for all the documents has been loaded, Java needs to _display_ it. Such a list with some 20,000 entries just takes a little to render and negotiate displaying with your graphics adapter.

Apart from that, if _loading_ the list fails for some reason (Network interruption, server error, ...,, you name it), there will be an exception at some point. No way of preventing that on an HTTP backed channel, even if I tried to do so, as HTTP involves timeouts of its own.

**Comment by myrmoteras** [comment]
now it works fast, as I have been expecting over the last years
