### ISSUE TITLE
miscoded images on BLR

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#65]
20170209

https://zenodo.org/record/288198#.WJzO-HsrLAQ

https://zenodo.org/record/288195#.WJzPXXsrLAQ

https://zenodo.org/record/288189#.WJzPeXsrLAQ

https://zenodo.org/record/288188#.WJzPhnsrLAQ

https://zenodo.org/record/288229#.WJzPs3srLAQ

https://zenodo.org/record/288292#.WJzR63srLAQ

https://zenodo.org/record/288291#.WJzR-nsrLAQ

https://zenodo.org/record/288310#.WJzSJXsrLAQ

https://zenodo.org/record/288308#.WJzSOnsrLAQ

https://zenodo.org/record/288314#.WJzSTXsrLAQ

this is the article for the last errors above https://zenodo.org/record/288290#.WJzScXsrLAQ

**Comment by myrmoteras** [comment]
20170210
https://zenodo.org/record/290100#.WJ04insrK0o
https://zenodo.org/record/290101#.WJ045HsrK0o
in  https://zenodo.org/record/290096#.WJ05D3srK0o 

https://zenodo.org/record/290074#.WJ05eXsrK0o
https://zenodo.org/record/290071#.WJ05jXsrK0o
https://zenodo.org/record/290067#.WJ05snsrK0o
in https://zenodo.org/record/290058#.WJ058XsrK0o

**Comment by gsautter** [comment]
The first one was a single call to Figure Repair ... all fixed.

**Comment by gsautter** [comment]
Please refrain from reporting each and every broken figure, as then I have to figure out the document respective UUID before being able to even turn loose Figure Repair on the respective PDFs.

An ideal error report would contain either the Zenodo record URL of the PDF proper, or the very document UUID. The latter is what I need to schedule repair ...

**Comment by myrmoteras** [comment]
ok - doc uuid shall be it in the future

**Comment by gsautter** [comment]
The other two (Zootaxa from the 0210 comment) have also run through repair by now, so they should be OK.

**Comment by gsautter** [comment]
And thanks for the document UUIDs ... those directly translate to a "repairDoc" command in the server console ("PFR.repairDoc <UUID>", with "PFR" short for "PDF Figure Repair"), which takes me about 10 seconds per document to  issue.

If there are multiple Zenodo record URLs, on the other hand, the first thing I have to figure out is how many actual articles / PDFs are affected, on top of the respective UUIDs. And you tend to already know that when posting a comment, so it's just duplicate effort if I have to figure it out again.

**Comment by gsautter** [comment]
Hint: on every figure, thee is a "Part Of" link like "urn:lsid:plazi.org:pub:<ArticleUUID>" ... that's enough to have the server fix it.

**Comment by myrmoteras** [comment]
with this nice view https://zenodo.org/record/344609#.WLYSiZorLAR which is part of urn:lsid:plazi.org:pub:803DFFFAFFC4A2610F6000553139FFAB that does not have to be fixed, I wish you a pleasant night
