### ISSUE TITLE
taxonomicName, FAT

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#653]
taxonomicNames that include two tokens are not recognized by FAT.

![image](https://user-images.githubusercontent.com/4609956/56792302-92e53500-6809-11e9-837c-e6deb6c48960.png)

zoosystema2019v41a10_1

**Comment by myrmoteras** [comment]
extending and parsing then discover the right elements

![image](https://user-images.githubusercontent.com/4609956/56792488-05561500-680a-11e9-8d9b-2591888d6bfd.png)

**Comment by gsautter** [comment]
Could be the fact that the "F." is tailing in "Smith F." (as opposed to "F. Smith") gets in the way.

The weird part is that "Parse Taxon Name" does nothing but run FAT on that annotation, selecting and using the longest name it finds. Will check.

**Comment by gsautter** [comment]
Turns out this one is a bit more subtle ... "Smith" is in fact an official region name in Bermuda, which occurs in the document, resulting in "Smith" getting filtered out as a potential authority due to its local role as a location name. Will see what I can do about that.

**Comment by gsautter** [comment]
Salvaging such names based upon catalog lookup results now.
