### ISSUE TITLE
subSubSection type: making use of capital letters

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#654]
when the inline headers of subSubSection are written in upper case, the treatment structure tagger does now recognize them

![image](https://user-images.githubusercontent.com/4609956/56793896-561b3d00-680d-11e9-8b5f-de391d8bf92a.png)

this seems to be a low hanging fruit, but one that helps a lot in saving time in the markup
zoosystema2019v41a10_1

**Comment by gsautter** [comment]
Weird ... we actually have a rule in place that picks up "Distribution", also in all-caps.

Which document is this? Hard to reproduce without that.

**Comment by gsautter** [comment]
OK, I overlooked the document name ... anyway, fixed now. "DISTRIBUTION" was in the rule set for style template based treatment structuring, but not in the other.
