### ISSUE TITLE
images: dealing with scanned images in text

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#66]
@gsautter here is once more the issue of images that are in scanned text that need to be cut and added  to BLR.

http://tb.plazi.org/GgServer/summary/FF93FFD9FFC5FFF3FFDEFFD8FF93FFEE

[iom5-2mantodea_OCR.pdf](https://github.com/gsautter/goldengate-imagine/files/770517/iom5-2mantodea_OCR.pdf)

There is one image. 
It is marked up as image in the article
captions are marked
figureCitation is marked, but I cannot link it the the caption/image

**Comment by gsautter** [comment]
Same small-caps font size problem as in #68 and #87 ... because the caption starts "F IGURE", the citation cannot be matched to it. Once you merge up "F" and "IGURE", you can use "Mark Figure Citation" just like supposed to. I've updated the document on the server.

**Comment by gsautter** [comment]
discussed in most detailed in #89
