### ISSUE TITLE
file does not open: Cretaceous Research

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#662]
[GgImagine.20190506-1155.out.zip](https://github.com/gsautter/goldengate-imagine/files/3147484/GgImagine.20190506-1155.out.zip)
[createceousResearch.99.30-40.pdf](https://github.com/gsautter/goldengate-imagine/files/3147488/createceousResearch.99.30-40.pdf)

**Comment by gsautter** [comment]
This is a strange one ... the error occurs in decoding some color for PDF rendering, not sure what exactly is off there, have to test this.

**Comment by gsautter** [comment]
Got it ... some number rendering argument sticking right to the preceding command, without the usual space in between, for the first time in 30,000 PDFs ... catching that now, but looks like a really rare one.
