### ISSUE TITLE
geoCoordinates materialsCitation: not discovered zootaxa.4599.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#663]
is there a way, such geocoordinates could also be discovered, and the error margin be kept?
![image](https://user-images.githubusercontent.com/4609956/57235744-dc146080-7023-11e9-8e49-be89a3e1b128.png)

http://treatment.plazi.org/id/5B56E872FF9B4A50FF328AD8FD44E95C

A76F900AFF804A4BFFA58B6FFFF4EF5B

**Comment by gsautter** [comment]
Done, looks like the pair based approach should do the trick pretty precisely.
