### ISSUE TITLE
image: can't mark Systematic Parasitology

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#664]
can't mark image region

![image](https://user-images.githubusercontent.com/4609956/57236562-abcdc180-7025-11e9-95d0-6f5464e7a194.png)
[systematicParasitology.96.279-297.pdf](https://github.com/gsautter/goldengate-imagine/files/3148692/systematicParasitology.96.279-297.pdf)

**Comment by gsautter** [comment]
Please let me know when the IMF is on the server, so I can take a look and get this corrected.

**Comment by myrmoteras** [comment]
Ok. I can upload, or you better just run it from scratch?!

**Comment by gsautter** [comment]
Depends how large this one is ... better just upload, and I'll take it from there. Re-decoding on my end should really only be a last resort, and I'll have to figure out what was going on with the same data you got the funny behavior with.

**Comment by myrmoteras** [comment]
ok. i processed the entire file, but removed the areas with those figures so that no figures are uploaded to BLR.

9978FFCB0875FF82FFF7FF9A38354A33

systematicParasitology.96.279-297

**Comment by gsautter** [comment]
Looks like the reason you could not mark an `image` is that all these drawings are vectorized, coming up as `graphics`. "Mark Graphics" works just fine, to the desired result.

If "Mark Image" is not available, but "Mark Graphics" is, the effect is pretty much the same, but whatever drawing is selected is not painted from a bitmap, but rather via PDF native 2D drawing commands.
