### ISSUE TITLE
bibRef messed up: can not be marked up properly

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#666]
in this case, most of the bibRefs are not marked up.
I then marked them all up individually, and run pars bib ref again. only ca 70 got parsed, the rest lost their bibRef tag.

The doc is here FFAAFFD1FF95FFDE996BFFE07A2B763F

can you fix this? 

I would like to have it because it is a review of a group of ants in which I published substantially, but this review does not include one single article! revisionists...

**Comment by gsautter** [comment]
Done ... the original problem was deeper down, however: Almost all the numbers (including the years) in the references were split up into single-digit words, adding spaces between the digits (will have to check why the PDF decoded that way), which ended up interfering with pattern matching for the years.
After fixing all the numbers, RefParse did a terrific job: I had to make manual corrections in as many as 1 out of 148 references :-).

**Comment by myrmoteras** [comment]
Thanks. I had this suspicion, but not the time to look into this
