### ISSUE TITLE
taxonomicName in parasitic literature

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#668]
9978FFCB0875FF82FFF7FF9A38354A33

here is a new taxonomic name that is not discovered (genus) and causes problems. not least because it has other taxa that are its host.

![image](https://user-images.githubusercontent.com/4609956/57276180-1112c880-70a1-11e9-9ee3-6aeab8f607c2.png)

**Comment by gsautter** [comment]
Well ... CoL doesn't know that genus (small wonder, it' new, see http://webservice.catalogueoflife.org/col/webservice?name=Citrilolepis), and FAT did not recognize "g. n." as a "new genus" label just yet. I've added the latter now, should come out as desired with that.
