### ISSUE TITLE
upload issues

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#67]
@gsautter 
this file seems not to upload to BLR
http://tb.plazi.org/GgServer/summary/FF93FFD9FFC5FFF3FFDEFFD8FF93FFEE

thanks for looking into this
donat

**Comment by gsautter** [comment]
Well, then, looks like it actually does ... only case could be you created this ticket before page scan cut-outs were going on Zenodo as figures. The latter has been fixed a while ago, however.
