### ISSUE TITLE
font issue rbent.61.02.192-202

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#672]
![image](https://user-images.githubusercontent.com/4609956/57433179-18b8a580-7238-11e9-9eae-0cb78251c6e1.png)

I can't change this font to what it ought to be: 
![image](https://user-images.githubusercontent.com/4609956/57433279-5b7a7d80-7238-11e9-8c75-416f67cd704d.png)

**Comment by myrmoteras** [comment]
E16FA41DFF81FA4B2460FFEEFFA9642D

**Comment by gsautter** [comment]
For what it looks like, this is not a font issue, but rather a decoding issue ... the `fontCharCodes` attribute of all the coordinate directions is wrong, stating it to be `''` rather than `S` or `W`. Will check.

**Comment by gsautter** [comment]
Cannot seem to reproduce this ... I'll try and figure out a way to fix the IMF.

**Comment by gsautter** [comment]
Repaired the IMF now, tagged the coordinates, and updated the materials citations ... should be OK now.
