### ISSUE TITLE
file did not batch process zootaxa.4604.2.7

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#673]
[zootaxa.4604.2.7.pdf](https://github.com/gsautter/goldengate-imagine/files/3176110/zootaxa.4604.2.7.pdf)

**Comment by gsautter** [comment]
Processed and uploaded, UUID is `7A28E516FFD7FFD3FFDF377CFFA6D442`. Must have been an issue that was fixed in the meantime.
