### ISSUE TITLE
GGI new version: hot to handle cached content menu

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#676]
in the new version of GGI, a menu opens that asks what to do with cached content.

![image](https://user-images.githubusercontent.com/4609956/57979783-96439900-7a22-11e9-9745-d3751f0edac7.png)

@gsautter can you please explain briefly what this means? 
What is the difference between move along and copy?
What should be the standard procedure?

**Comment by gsautter** [comment]
Well, I had hoped for this to be rather intuitive ... anyway:
- "Copy Over" is the original behavior, i.e, copy any cached data from the old version to to the new version of the configuration, which you rightfully complained unnecessarily eats up your disk space over time
- "Ignore Altogether" means to leave any cached data in the old version untouched (so you can get back to it), but to _not_ copy it to the new version of the configuration (you start fresh in terms of cached data, but have the old cached data still available, just in case)
- "Clean Up" means to simply scrub (delete) any cached data in the old version (to free up disk space), without copying it to the new version of the configuration (you start completely fresh in terms of cached data)
- "Move Along" means to _move_ any cached data in the old version to the new version of the configuration (you keep your cached data with you, but without duplicating its disk space consumption)

Ultimately, this is a matrix of where any cached data is available after the update:
- "Copy Over": old and new version (at the expense of twice the disk space)
- "Ignore Altogether": old version only
- "Move Along": new version only
- "Clean Up": neither version (helps starting fresh space, e.g. for things like our FAT discrepancies that disappeared after cleaning out the caches, and also frees up disk space)
