### ISSUE TITLE
font/word issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#68]
@gsautter here is problem about words that are separated

![image](https://cloud.githubusercontent.com/assets/4609956/22920415/41374522-f295-11e6-8b59-c4ba55ffe793.png)

[iom5-2mantodea_OCR.pdf](https://github.com/gsautter/goldengate-imagine/files/773449/iom5-2mantodea_OCR.pdf)

**Comment by gsautter** [comment]
very same issue as #87

**Comment by gsautter** [comment]
discussed in most detailed in #89
