### ISSUE TITLE
file does not batch process zootaxa.4608.3.10

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#680]
[zootaxa.4608.3.10.pdf](https://github.com/gsautter/goldengate-imagine/files/3200960/zootaxa.4608.3.10.pdf)
[GgImagineBatch.20190521-0752.out.zip](https://github.com/gsautter/goldengate-imagine/files/3200962/GgImagineBatch.20190521-0752.out.zip)

**Comment by gsautter** [comment]
Done, UUID is `973F473AFFF6FFDA4859532F2C2FFFCA`.

Another materials citation thing, this time almost a whole "type material" paragraph contained in quotes, with only type status, country, specimen count and collection code outside. Too bad all these nice details are locked in quotes (even though we do extract the secure ones now).
