### ISSUE TITLE
document checked out 10.5252/zoosystema2018v40a25

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#684]
@gsautter can you please check, why this document is checked out by another user? and why the figures do not show up in the TB and GBIF, ie are not assigned?

![image](https://user-images.githubusercontent.com/4609956/58614048-97dd4e80-82b7-11e9-9cc1-a8b71138cc00.png)

FFE2FF9AFF995F66FFFBFFE9FF85FFB2

**Comment by gsautter** [comment]
Jeremy locked this one some two weeks ago ... hard to telly why he didn't release it thus far. I unlocked it now.
