### ISSUE TITLE
bibRef author not complete; eLife format

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#685]
this is yet another format to tackle
![image](https://user-images.githubusercontent.com/4609956/58688018-924d3a80-8383-11e9-90f4-912b4d738545.png)

the file is uploaded. let me know, when you found a solution so I can finish parsing

CD63694BB36BFF81510A066BFFE8FFB4

**Comment by gsautter** [comment]
This format is indeed special, and, more importantly, inconsistent with regard to styling of initials: in the author names, they are without dots and en bloc, in the editors they are with dots, safe for the last one, which comes without a dot.

Apart from that, this was mainly a font issue, as the comma had been mis-decoded to a cedilla, and therefore both author and editor lists were causing problems. After fixing the fonts, parsing did fairly well, apart from a few corrections necessitated by the inconsistent punctuation of author and editor initials.

Another issue I recognized with this one is that the bibliography is not justified, and line wrapping is a bit inconsistent, so there were a few broken paragraphs in the bibliography that I had to fix. Hard to tell what to do about that, though, as any kind of automation requires consistency of some sort to go at.
