### ISSUE TITLE
files do not process zootaxa.4616.1.1 zootaxa.4617.1.1 zootaxa.4618.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#690]
[GgImagineBatch.20190617-0622.out.zip](https://github.com/gsautter/goldengate-imagine/files/3295530/GgImagineBatch.20190617-0622.out.zip)

https://drive.google.com/open?id=1v2r3P1pewA4DyOBjeY_WzQ45dZvnUy_X

**Comment by gsautter** [comment]
This has been fixed lately, it's just that the update isn't out yet. I'll let you know.

**Comment by gsautter** [comment]
That fix was actually already in the update I put online on May 31st ... anyway, I made another build now, which (naturally) also includes this fix.
