### ISSUE TITLE
figures do not show up in TB

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#7]
@gsautter in this article, the figures do not show up

http://tb.plazi.org/GgServer/summary/4D68FF82FFAC6D78FFFEFF9A212AB963

**Comment by myrmoteras** [comment]
also, figures 1, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18,  are not in BLR. These are all photographs

**Comment by gsautter** [comment]
They are now ... assignment of images to captions was broken, so the Zenodo uploader was unable to find the images to go with the captions. Any manual editing and annotating done in that area?

**Comment by gsautter** [comment]
Any manual editing and annotating done in the caption department? If so, please drag a box and use "Mark Caption", which does all the assignment to images behind the scenes, and even automatically marks figure citations. If not, I'll have to investigate further.
