### ISSUE TITLE
bibliographic reference tagger missing XXXXb

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#702]
it seems that the bibliographic reference tagger is missing references that are suffixed with a a, b, c,

![image](https://user-images.githubusercontent.com/4609956/61293886-f6fa1280-a7d4-11e9-8d6a-65565e3a6a3e.png)

see ejt-535

**Comment by gsautter** [comment]
Our whole reference and citation handling is well aware of such _index letter_ (that's what we chose to call them in RefParse back when we built that), so these should not be a problem at all ... I'll will check it out.

PS: this is the _citation_ tagger, just to avoid misunderstandings.

**Comment by gsautter** [comment]
Just tested this, and I cannot seem to reproduce this blank. Actually, the citation tagger uses the index letters for disambiguation, just like supposed to.
