### ISSUE TITLE
no taxonomic name discovered: zootaxa.463

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#703]
In this article, NO taxonomic name has been discovered:

FFADFFB7FFDAFFEA6D689D480E30FF8F

**Comment by gsautter** [comment]
Got it ... turns out this is not an FAT problem, though, but rather a reference issue. In particular, this nicely numbered and sorted list of 543 taxon names gets mistaken for the bibliography, with the genera becoming the authors. And FAT filters author names before the CoL/GBIF lookup ...

**Comment by gsautter** [comment]
I re-did the bibliography, this time the actual one, and after that the taxon names mark just like supposed to. Now trying to figure out how the bibliography tagger could go this wrong ...

**Comment by gsautter** [comment]
Turns out a list of 543 numbered strings occurring in perfectly sorted order is too much for any generic scoring approach to ignore in favor of  some 34 actual references ...

I'll add a template parameter indicating whether or not references are numbered.

**Comment by gsautter** [comment]
Turns out we did already have a template parameter for the reference number ... now augmented by the option to explicitly state "no reference numbers" by setting the pattern to `NONE`.
