### ISSUE TITLE
MC wrong lat long: 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#705]
some lat long are wrong, taiwanese specimens showing up in the Sahara

http://tb.plazi.org/GgServer/summary/EB44FFFEFFDA907F522EFFD27267682E

**Comment by gsautter** [comment]
This is more of a splitting problem ... and a false positive coordinate `E-3, 1999` (actually the number of some trap a specimen was caught with), which overrides the correct one ... pretty pathological.

**Comment by gsautter** [comment]
In general, this article has a problem with MC splitting, and in my effort to correct the coordinates I also found why: There are many quoted specimen labels, and the quotes get inverted because they include most of the safe details, and as a consequence, the splitting points end up "in quotes" ...

**Comment by gsautter** [comment]
In general, the MCs in this one mostly consist of quoted labels, and as a consequence do not exhibit the regularity required to automatically infer a good chunking ... fixed them manually, so now Taiwan is back from the Sahara.
