### ISSUE TITLE
file does not batch process zootaxa.4638.4.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#706]
[zootaxa.4638.4.1.pdf](https://github.com/gsautter/goldengate-imagine/files/3405274/zootaxa.4638.4.1.pdf)
[GgImagineBatch.20190718-0928.err.zip](https://github.com/gsautter/goldengate-imagine/files/3405278/GgImagineBatch.20190718-0928.err.zip)

**Comment by gsautter** [comment]
Yikes ... stupid missed edge case. Fixed it, update is online. Your batch will start over right with the materials citations after an update.
