### ISSUE TITLE
new name lable

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#71]
can we add "sect. nov." as a new taxonomicNameLable?

![image](https://cloud.githubusercontent.com/assets/4609956/23155846/91a78f24-f814-11e6-8f81-99d2ed014e06.png)

[405-2048-1-PB.pdf](https://github.com/gsautter/goldengate-imagine/files/789419/405-2048-1-PB.pdf)

**Comment by gsautter** [comment]
Botany, isn't it? Thus far, and quite successfully so, the latest FAT version has been focusing on zoology ...

**Comment by gsautter** [comment]
Adding sections and sub sections, as well as all the other ranks not used in zoology (and not part of ICZN, either) will likely be quite some effort. In particular, I'll have to extent all the FAT patterns to go beyond the `genus subGenus? species subSpecies? variety?` scheme we so successfully apply in zoological articles. Maybe make some BotFAT clone?

**Comment by gsautter** [comment]
Moved to #89 (wish list), closed for now.
