### ISSUE TITLE
bibRef: not discovered kewBulletin.74.28

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#713]
Here is a rare case where the bibRef tagger has not found the begin of the bibRefs
It only started to tag from Deroin.

and when I do it manually, then I am getting this - 
![image](https://user-images.githubusercontent.com/4609956/61590364-559a0480-abb8-11e9-9d07-b2caaf72810c.png)

I did not  fix it so you might have a look at it yourself.

**Comment by gsautter** [comment]
Looks like what got in the way here is the very same in-word spacing behavior as in #715 ...

**Comment by gsautter** [comment]
The problem with bibliography _detection_ appears to be that "Couvreur" is repeatet a total of 9 times by means of "____", which is too much to bridge over for the tagger. Also, the latter currently only regards sequences of dashes as "same author(s) as above", but not underscores. I'll change that and see if it fixes the problem.

**Comment by gsautter** [comment]
Turns out recognizing "____" as a marker for "same authors s above" alongside "----" does fix this.
