### ISSUE TITLE
token split

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#715]
in this case, there is an issue of spaced letters that ought to be tokens

![image](https://user-images.githubusercontent.com/4609956/61590566-ac550d80-abbb-11e9-90e7-2489b88f2e66.png)

kewBulletin.74.28

**Comment by gsautter** [comment]
Hard one ... here the corresponding excerpt from the original PDF:
![image](https://user-images.githubusercontent.com/5789714/61595901-2b1e6a80-abfd-11e9-8494-09e4b9361cd9.png)
Apparently, text justification ended up adding space _inside_ words in this particular line (red frame), whereas it didn't do so in a similarly stretched line further down the same paragraph (green frame).

Hard to tell why this happened, but "Join Words" should fix it easily enough.

**Comment by myrmoteras** [comment]
i guess we can do manually, but prevention is better, since we can't deal in a one to one base if we want to batcvh process entire journals?!

**Comment by gsautter** [comment]
I can surely devise some automated means to do this, yes, most likely based upon average space width throughout the line and then some tokenization checking. We just didn't need anything like this thus far ...

**Comment by gsautter** [comment]
Implemented as part of page structure detection, using per-line word lengths and word distance distribution. Comes with next build.
