### ISSUE TITLE
file does not batch process: MC issue zootaxa.4643.1.1.

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#718]
[GgImagineBatch.20190722-0826.out.zip](https://github.com/gsautter/goldengate-imagine/files/3416087/GgImagineBatch.20190722-0826.out.zip)

zootaxa.4643.1.1.pdf is here https://drive.google.com/open?id=0B_yrQwn4yBySTlBxMnhWd3o1Zkk

**Comment by gsautter** [comment]
Closing as duplicate of #755 ...
