### ISSUE TITLE
file did not batch process: hangup on MC

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#721]
FFA6526DFFE1FF9EFFF0ED42D718C94A

I processed the file manually, but did not the MC
this file did not batch process. Can you please check the MC and get the holotypes at least marked up?

**Comment by gsautter** [comment]
One thing that immediately jumps my eye in the very first treatment (Andrena labrosa Eversmann, 1852) is that cited specimen labels are not quoted at all ... hard to tell where the label starts and end, which causes a good bit of attribute duplication, and throws off the tagger.

**Comment by gsautter** [comment]
In Dufourea akmolensis Pesenko, 1998, there is a holotype and a few paratypes, with the latter starting "the same label as lectotype" ... hard to automatically resolve this ...

**Comment by gsautter** [comment]
Done, marked all the holo- and lectorypes, one neotype, and as many paratypes and paralectotypes as possible. I must say, the MC handler didn't hang on either of the `subSubSection`s (I did them individually), so har to tell what cause the hangup in the batch.
