### ISSUE TITLE
text conversion wrong 902B4D6CFFB4FF8DFFC3FFD3D51EFFB8

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#728]
in this article - an image just showed up on Zenodo - something is completely broken...

![image](https://user-images.githubusercontent.com/4609956/63358826-f91f3600-c36b-11e9-88f4-5236f8c65480.png)

![image](https://user-images.githubusercontent.com/4609956/63358914-194ef500-c36c-11e9-8562-e468260c5b29.png)
I added the caption

**Comment by gsautter** [comment]
Just tested it, and the two captions in question decode just fine ... I'll repair the IMF and update it on the server.

**Comment by gsautter** [comment]
Hard to tell what went wrong here ... anyway, I fixed the IMF, and all the figures are on Zenodo now, with the correct captions.
