### ISSUE TITLE
taxon concept annotation: add automatically authorityYear when inferred

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#73]
Would it make sense to add the "authorityYear" value automatically to the taxonomicName annotation for new species, taxa?

![image](https://cloud.githubusercontent.com/assets/4609956/23155971/4c2747cc-f815-11e6-8770-f85914b70212.png)

**Comment by gsautter** [comment]
Makes some sense, definitely ... even though newly described taxa (and new combinations, for that matter) automatically inherit author(s) and year from the bibliographic data of the treatment.

That means that even though the `authorityYear` attribute is not there explicitly, it should be inferred by our export XSLTs.

**Comment by gsautter** [comment]
Anyway, what does this very taxon name say? For what I see here, it's a standard genus-species binomial (with authors corresponding to those of the article proper) followed by an epithet in between genus and species.
Most likely, this includes designating a new section and declaring the new species "Begonia elachista" the type species of that very section ...

**Comment by gsautter** [comment]
FAT expects taxonomic names with epithets in strictly descending rank order, meaning genus epithet before section epithet before species epithet in this instance (if it did observer section at all, but that doesn't matter in general terms of epithet ordering) ...

Anything else would just incur another ton of complexity for what has been working on zoology so well for quite a while now ... without any guarantee of it to keep on working as reliably if we introduce the option of having rank order mixed up,

**Comment by gsautter** [comment]
Why do botanists denote it this was, anyway?

**Comment by gsautter** [comment]
I guess this one has lingered for all too long for such a peculiar case still to be relevant ... laying it to rest.
