### ISSUE TITLE
can't detect structure: Rauhut2003BasalTheropod_ocr

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#730]
this document has been OCRed via ABBYY and has text under the images
[GgImagine.20190824-2215.out.zip](https://github.com/gsautter/goldengate-imagine/files/3537558/GgImagine.20190824-2215.out.zip)

the imf is here: 

https://drive.google.com/open?id=1V_igzPYGwoKI37yYsi11l9a3f9qu2HhB   Rauhut2003BasalTheropod_ocr

**Comment by gsautter** [comment]
see #729, closing this one as duplicate.
