### ISSUE TITLE
could not process: hang up on MC zootaxa.4660.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#731]
this file hung up on MC processing.  lost error log, because GGI had to be aborted due to loading the IMD via drag and drop into the GGI window. I have recovered the file and tried to fix and failed in the import. When importing via open as it works.

Here is the file. I added the holotypes, @gsautter can you please fix the MC for the document?

**Comment by myrmoteras** [comment]
FF8AFF9E325C1034FFA9FFD5D8493D28

**Comment by gsautter** [comment]
MCs are done. I'll have a good bit of something to think about from this one:
- automatically getting stuff like "four juvenile females" right is pretty much possible, but a good bit of effort
- those specimen codes are cumbersome, so I'll get back to the morphological pattern detector I was working on a little while back to improve this
- we need a more comprehensive list of collecting methods ... any idea where we might get something like that, apart from our own data?

**Comment by gsautter** [comment]
The hangup, on the other hand, might well be the result of a font error `Sao Paolo` comes out as `S"o Paolo` ("a" with tilde above comes up as double quote), unbalancing quotation marks. Will investigate.

**Comment by gsautter** [comment]
I repaired the fonts and page images now, as well as the words. Now going for the MC handler ...

**Comment by gsautter** [comment]
A hangup safeguard was added to the materials citation handler with the update of Dec 13th, 2019, so that will not happen again.
