### ISSUE TITLE
MC: black list of names

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#732]
can you please add "Not" to the black list of location names?
![image](https://user-images.githubusercontent.com/4609956/63674359-a66bd100-c7e6-11e9-8ee2-ba968e890b3e.png)

**Comment by myrmoteras** [comment]
dito for "examined"

**Comment by gsautter** [comment]
Done, comes with next update.

In general, I have to harmonize detail extraction logic between the fully automated tagger/parser and the interactive one ... as opposed to other parsers, these two are completely separate because they work the same problem from totally different angles.
