### ISSUE TITLE
table not detected zootaxa.4660.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#734]
![image](https://user-images.githubusercontent.com/4609956/63674707-66591e00-c7e7-11e9-858f-f0a5a1c87884.png)

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/63675228-a1a81c80-c7e8-11e9-84ea-8da0815292f2.png)

**Comment by gsautter** [comment]
These look perfectly normal to me ... hard to tell why they failed to detect, will check ...

**Comment by gsautter** [comment]
Turns out the continuations of both Table 4 and Table 5 are lacking any grid lines ... hard to detect them in that case, especially since the template says tables have grid lines, which they usually do in Zootaxa.

**Comment by gsautter** [comment]
Looks like the grid lines are lost in the process of flipping the pages to horizontal ... will investigate.

**Comment by gsautter** [comment]
It's not the content flip ... more of a rounding issue with the clip bounds, which makes these lines appear to be invisible and consequentially have them filtered ... I'll add some tolerance to this filter.

**Comment by gsautter** [comment]
Done ... preventing empty bounding boxes altogether now.
