### ISSUE TITLE
upload of images: slow??

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#739]
why does it take 1min 19 sec to store 
![image](https://user-images.githubusercontent.com/4609956/63688437-a92aee00-c807-11e9-9029-8c2209bf3d06.png) 
 a  
26MB file
![image](https://user-images.githubusercontent.com/4609956/63688452-be078180-c807-11e9-9732-f4bcf61d8240.png)
?

I have an upload speed of  >200Mps
![image](https://user-images.githubusercontent.com/4609956/63688552-00c95980-c808-11e9-9582-5d47060d7305.png)

ejt-541  FF8ED00DFFAAFF94FF85967AFFB5FF9F

**Comment by gsautter** [comment]
Well, all the figures are hashed to generate a checksum to prevent re-upload if you open a document from the server, and then zipped, together into a single stream of document entries, so there is a bit of computation involved. Apart from that, it's hard to tell from the outside ... keep in mind that connection speed is measured in _bits_ per second, not bytes, so you have some 35MB/sec there, and those figures are quite large.
