### ISSUE TITLE
EJT: degree

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#74]
The degree symbol is not recognized by the materials citation parser
http://tb.plazi.org/GgServer/html/770C87B4FFDBFF9AFE05FAA18B44FA37

http://tb.plazi.org/GgServer/html/770C87B4FFDBFF9AFE05FAA18B44FA37

**Comment by gsautter** [comment]
What exactly is missing? Just look at http://tb.plazi.org/GgServer/xml/770C87B4FFDBFF9AFE05FAA18B44FA37 ... the coordinates _are_ annotated (and normalized and everything ...), so I tend to think the GeoCoordinate Tagger and subsequently the Materials Citation Handler (my term for a combination of Tagger and Parser) looks like having got it right ...
