### ISSUE TITLE
can't process file ejt-545

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#741]
[ejt-545_sun_li_sheng.pdf](https://github.com/gsautter/goldengate-imagine/files/3542062/ejt-545_sun_li_sheng.pdf)

this file does not process, neither in batch 
[GgImagineBatch.20190826-1852.out.zip](https://github.com/gsautter/goldengate-imagine/files/3542064/GgImagineBatch.20190826-1852.out.zip)

nor does the documenStucture work in GGI
[GgImagine.20190826-0937.out.zip](https://github.com/gsautter/goldengate-imagine/files/3542066/GgImagine.20190826-0937.out.zip)

**Comment by gsautter** [comment]
Same as #729 ... closing as duplicate.

**Comment by myrmoteras** [comment]
[MONTE-1941-Leptobyrsa_steini_ocr.pdf](https://github.com/gsautter/goldengate-imagine/files/3551818/MONTE-1941-Leptobyrsa_steini_ocr.pdf)

one more to test whehther it works - looking forwards to get the new build
