### ISSUE TITLE
caption different: why do they look different? Wirth 2013

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#747]
![image](https://user-images.githubusercontent.com/4609956/64030615-38593e00-cb47-11e9-8963-fec1384e4511.png)

**Comment by gsautter** [comment]
I guess you used "Mark Caption" on the left, and manually annotated a caption on the right ... the former is a macro that also changes the text stream type to "caption", while the later merely adds an annotation. If you drag a box around the right instance and use "Mark Caption" there, it should become what you already have on the left.
