### ISSUE TITLE
EJT: wrong male / fi/fl  symbol

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#75]
the male symbol is mismatched
![image](https://cloud.githubusercontent.com/assets/4609956/23157588/259291dc-f81c-11e6-9def-b44c197e3cb5.png)

[404-2033-1-SM.pdf](https://github.com/gsautter/goldengate-imagine/files/789548/404-2033-1-SM.pdf)

![image](https://cloud.githubusercontent.com/assets/4609956/23157647/55acfa1a-f81c-11e6-91b0-93a633e45d98.png)

**Comment by myrmoteras** [comment]
In this article, the male and degree symbols are confused

![image](https://cloud.githubusercontent.com/assets/4609956/23158088/123557bc-f81e-11e6-8bcf-13c30b5bcd7e.png)

[404-2033-1-SM.pdf](https://github.com/gsautter/goldengate-imagine/files/789607/404-2033-1-SM.pdf)

**Comment by gsautter** [comment]
This one should be resolved with the latest online update, which, of course, will also be included in the next build.

There was an issue of words losing the binding to their fonts (and thank you for reporting it), but tha ha's been resolved several online updates ago.
