### ISSUE TITLE
strange pages B147.6

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#752]
![image](https://user-images.githubusercontent.com/4609956/64060953-22458f00-cbd4-11e9-8ecc-080ceb815fef.png)

**Comment by gsautter** [comment]
This does look very strange, indeed ... question is if the word boundaries are like this in the embedded OCR. If so, the document is just badly done. However, "Edit Page Image & Words" should provide you the tools to clean this up.

**Comment by gsautter** [comment]
I looked at the embedded OCR, and it looks pretty much like this ... GGI loads it faithfully, but the source PDF is crap.

Anyway, you _can_ clean this up in GGI (remove the odd words), which I did.
