### ISSUE TITLE
subSubSection recognition issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#757]
here is another example where subSubection have either not been found or wrongly labeled: 
zootaxa.4664.2.6

**Comment by myrmoteras** [comment]
zootaxa.4664.2.7 also missing subsubsections
![image](https://user-images.githubusercontent.com/4609956/64235457-b24b4780-cef8-11e9-97c6-38d830880883.png)

**Comment by myrmoteras** [comment]
same issue zootaxa.4664.2.9

not sure whether they changed editorial rules?!

**Comment by myrmoteras** [comment]
but we need to keep an eye on this, and if possible fix as soon as possible

**Comment by myrmoteras** [comment]
@gsautter I think we need to adjust the template because Zootaxa might have changed its outline, with subSubSection title indented.

![image](https://user-images.githubusercontent.com/4609956/64249252-9012f300-cf13-11e9-9be5-79d0f86821a5.png)

**Comment by gsautter** [comment]
I guess you mean "inlined" ... but yes. Might require some change to the heading tagger as well, as these are no longer separate lines (let alone paragraphs), but line starts.

**Comment by gsautter** [comment]
Let's make sure that this isn't some "personal" style of some specific author, first, though.

**Comment by gsautter** [comment]
Got it ... doesn't have anything to do with layout changes ... with the introduction of in-line headings and a respective tagger (intended to make `subSubSection` typing _more_ accurate), the rules became a bit trigger happy, which means the first in line (happens to be on for `materials_examined`) fires way too often. Now down to figuring out why ...

**Comment by gsautter** [comment]
Turns out the rules proper were perfectly fine, but the engine mishandled my latest rule extensions ... problem is fixed, update and new build are out.
