### ISSUE TITLE
taxonomic name lables: combined labels gen et sp. nov

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#76]
how to deal with combined labels?

![image](https://cloud.githubusercontent.com/assets/4609956/23157810/eb8cc79a-f81c-11e6-8ba3-6c4a2b407a94.png)
[404-2033-1-SM.pdf](https://github.com/gsautter/goldengate-imagine/files/789566/404-2033-1-SM.pdf)

In this case, the label is "wrong" since it does only include the  treatment of a new species. The genus is described above

EJT

**Comment by gsautter** [comment]
I used the Friday train ride to add this feature to FAT. It does recognize such double-rank status labels now, and assigns the lower rank ("species" in this case). Comes out with the next build.
