### ISSUE TITLE
file does not process nature s41467-019-11690-z

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#763]
[GgImagine.20190911-1556.out.zip](https://github.com/gsautter/goldengate-imagine/files/3601225/GgImagine.20190911-1556.out.zip)
[s41467-019-11690-z.pdf](https://github.com/gsautter/goldengate-imagine/files/3601227/s41467-019-11690-z.pdf)

**Comment by gsautter** [comment]
Bad news: I cannot seem to reproduce the error.
Good news: Done up to (including) parsing the bibliography, and on the server as `700E5964FFABFFF7F77AE241C367FFE1`

**Comment by gsautter** [comment]
Figure 4 had a duplicate caption ... fixed that now. Hard to tell about figure 5, as that caption is just fine.
