### ISSUE TITLE
export XML

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#764]
it seems there is no option to export XML anymore. Before we could export, including identifiers etc. This isi all not possible anymore.
Can you get this functionality back as we need this as input format for the further processing of the EJT articles.

**Comment by gsautter** [comment]
It's still there, only as a simple "Export -> Export XML", with all the options to the right of the file selector view. As options became more and more, I did not want to have an "Export" menu item for each possible combination ... would have become too many.
![image](https://user-images.githubusercontent.com/5789714/64949074-ace6e900-d878-11e9-940b-97fc32967b08.png)
![image](https://user-images.githubusercontent.com/5789714/64949123-cab44e00-d878-11e9-84d6-46f44f1c9e6b.png)

**Comment by myrmoteras** [comment]
sorry, this doesn't answer. Which combination do I have to use?

![image](https://user-images.githubusercontent.com/4609956/65818233-f0920900-e20f-11e9-9775-f883ba01aa96.png)

Which one does include identifiers, so I get this sort of output we have here for Terry to continue to work? 
https://github.com/plazi/EJT-testbed/blob/master/gg_samples/ejt-486_constant_xml_raw_id.xml

**Comment by myrmoteras** [comment]
is this ok?

![image](https://user-images.githubusercontent.com/4609956/65818357-25eb2680-e211-11e9-90c7-ba49c7b90b30.png)

**Comment by gsautter** [comment]
The selected checkboxes are fine ("Normalize Characters" only if desired, without that you get the diacritics as they are, which we might want - "Export Annotation IDs" activates exactly that).
As the "Document Normalization Level", you should use "Paragraphs (logical paragraphs kept together)", which pretty much corresponds to what we used to call "GG1"; "Raw (words strictly in layout order)" corresponds to our legacy "GG0", even retaining hyphenation.

**Comment by myrmoteras** [comment]
this is the format Terry needs

![image](https://user-images.githubusercontent.com/4609956/65819861-d9f4ad80-e221-11e9-8db2-fcc70001c972.png)

**Comment by gsautter** [comment]
Thought you want to include the annotation IDs (tick off "Export Annotation IDs") and get rid of the diacritics (tick off "Normalize Characters")?
