### ISSUE TITLE
missing figures in the upload of 094DFFDDFF9DFF86FFD0FF87616FEA24

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#768]
in this article, the figures are missing on BLR

https://doi.org/10.5281/zenodo.3417134

the files is a scanned pdf we OCRed with ABBYY

[MONTE-1946-Leptocysta_ocr.pdf](https://github.com/gsautter/goldengate-imagine/files/3617084/MONTE-1946-Leptocysta_ocr.pdf)

**Comment by gsautter** [comment]
Should be up there now. There was a problem with the GBIF dataset IDs getting included in the metadata after circling back together with the figure IDs, incurring an "invalid identifier" error. Filtering the GBIF dataset ID for now until we decide how to include it (see https://github.com/plazi/Plazi-Communications/issues/930).
