### ISSUE TITLE
Back reference confusing, not previous but the holotype

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#77]
How to deal with a back reference that is to the holotype, and not the previous MC?
![image](https://cloud.githubusercontent.com/assets/4609956/23158227/acf1de92-f81e-11e6-8bf8-8a213bf24cf1.png)

[404-2033-1-SM.pdf](https://github.com/gsautter/goldengate-imagine/files/789622/404-2033-1-SM.pdf)

**Comment by gsautter** [comment]
Back references in the Materials Citation Parser are always first matched up against any type status term (including "holotype") and resolved against respective preceding materials citations inside the same treatment before simply falling back on the immediate preceding materials citation ... and it's been like this for several years now ... so what's the question here? The type status match-up not working?
