### ISSUE TITLE
file does not process: MC issue zootaxa.4683.3.6

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#778]
[zootaxa.4683.3.6.pdf](https://github.com/gsautter/goldengate-imagine/files/3705630/zootaxa.4683.3.6.pdf)
[GgImagineBatch.20191009-0703.out.zip](https://github.com/gsautter/goldengate-imagine/files/3705639/GgImagineBatch.20191009-0703.out.zip)

**Comment by gsautter** [comment]
The log looks normal ... stops somewhere in the middle. Could be the crucial part wasn't written before the whole thing closed.
However, I could reproduce it, hangs at the very same last line in the log. I'll dig in an see where it gets stuck.

**Comment by myrmoteras** [comment]
I killed the batch because it would not close by itself.

**Comment by gsautter** [comment]
Getting the same effect ... digging in.

**Comment by gsautter** [comment]
Getting closer ... a pattern for specimen code enumerations gets stuck somewhere.

**Comment by gsautter** [comment]
Got it ... a tiny part of a pattern intended to find collection codes followed by one or more specimen codes or specimen code ranges caused the runaway. In particular, that tiny part is intended to bridge any punctuation marks that might exist between the collection code proper and the first specimen code (range). And that "match any punctuation marks" part went on a rampage over the sequence of dots in a key lead paragraph ... restricted it now to match only shorter punctuation sequences, and it works fine. Comes with next build.

**Comment by gsautter** [comment]
I also finished the document and uploaded it, UUID is `FF8DFF8DFFAA9637FFF3A215CB45A336`.
