### ISSUE TITLE
discussion section

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#78]
How to deal with the discussion section that often follows after the treatment(s) and include the entire genus. In a sense, it should be part of the higher level treatment, not the last treatment that happened to be prior.

http://tb.plazi.org/GgServer/html/DE1D181FFF96B423481190E03F954B55

**Comment by gsautter** [comment]
I guess that's a subject for a wide discussion ... in our current definition, such a summary discussion about the (taxonomic) findings of the article as a whole doesn't qualify as a treatment in the sense that Willi argued out of copyright, as it is more of a quite educated and elaborate opinion than a plain description of nature. Or not ?!?

We could start exposing such discussions under the lowest primary rank taxon common to all treatments in an article, but I would like
- some legal expertise first ...
- ... as well as an analysis of how correct the "lowest common taxonomic denominator" approach would really end up being in the general case

PS: We already extract keys to species of a subject genus as genus level treatments.

PPS: While maybe containing prose voicing opinions about the species in some genus, there tends to be little hard fact data in such discussion sections ... so are they really worth the effort?

**Comment by gsautter** [comment]
PPPS: This issue hardly has anything to do with GGI ... any reason it is in this very tracker? Please put this one in a general Plazi discussion issue list.
