### ISSUE TITLE
upload of different files with the same name: What to do

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#780]
@gsautter I just uploaded a batch of file zootaxa.4638.4.1 - 8, which in fact should be zootaxa.4683.4.1 - 8.

What to do? 

I deleted zootaxa.4638.4.1, 2, 3, 6, 7, 8, but I don't know what to do with 4 and 5 which are already handled b "ExternalLinkService"

**Comment by gsautter** [comment]
Simply load them back from the server, go "Edit > Edit Document Attributes", and change attribute `docName`. In fact, that's what I've done last night to clean up a few legacy file name typos.

Ultimately, when you upload a document, the only thing that really counts is the MD5 hash of the source PDF, which becomes the document UUID, nothing more. You can change the file name all you want after the upload.

**Comment by myrmoteras** [comment]
ok - what about the files I deleted? I just re-upload them now again?

**Comment by gsautter** [comment]
"ExternalLinkService", by the way, is what writes back the GBIF dataset IDs to the source documents (conceived it when you asked for that), and also the Zenodo deposition numbers, also for treatments, and also the HTTP URIs (and DOIs if the treatment is on Zenodo, and LSIDs if the treatment is on ZooBank) to treatment citations (I added that yesterday).

**Comment by gsautter** [comment]
Yes, simply re-upload them. Annotation IDs are stable and well-defined and reproducible in IMF.

**Comment by gsautter** [comment]
The server doesn't care about file names at all, all it ever cares about is source PDF hashes. The file names show in the stats, etc., but only as an attribute of the document like any other, the hash based UUID is the only thing that counts.

**Comment by myrmoteras** [comment]
ok - this is done,, tx
