### ISSUE TITLE
can't donwload data from frankfurt

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#782]
@gsautter i ma getting an error 
![image](https://user-images.githubusercontent.com/4609956/67195251-e91de400-f3f8-11e9-9ffe-4d4eea078eef.png)

when attempting to download files from Frankfurt using the proibioshere GG

**Comment by gsautter** [comment]
Gimme a sec, I'll check the log.

**Comment by gsautter** [comment]
Looks like your version is out of date ... when did you last update it?

**Comment by myrmoteras** [comment]
or else, can you please run the MC parser on this zookeys: 3D35B64F5EFC52D4A6D044AD461A7339 which is displayed here and in a sense

**Comment by myrmoteras** [comment]
not sure - not today but I will

**Comment by myrmoteras** [comment]
I am getting a latest version - let's see

**Comment by gsautter** [comment]
I unified the way document lists are handled in IMS and DIO when creating the QC tool a while back, kept up support for older client versions for almost two months to give the updates a chance to spread, and then, after the the logs suggested the old ones were not used any longer, made the second round of changes ...

**Comment by gsautter** [comment]
If problems remain, I'll run the MC parser for you.

**Comment by myrmoteras** [comment]
what is I need to enter here. 

![image](https://user-images.githubusercontent.com/4609956/67196121-7c0b4e00-f3fa-11e9-8397-4b5618ac74cf.png)

none of the current settings work
![image](https://user-images.githubusercontent.com/4609956/67195912-22a31f00-f3fa-11e9-9b94-5c3e02c7e062.png)

**Comment by gsautter** [comment]
Will check.

**Comment by gsautter** [comment]
Works just fine ... one thing I can imagine is that you don't have `http://tb.plazi.org/GgServer/Updates` in your `UpdateHosts.cnfg` file yet, so there is core application updates missing.

**Comment by myrmoteras** [comment]
ok . whilist I am trying to fix this. could you process the MC in the article above - tx

**Comment by gsautter** [comment]
Done ... all I had to collect manually is the specimen codes ... the patterns most likely stumbled of the the parentheses in `IOZ(E)` ... but all the rest worked out great.
