### ISSUE TITLE
broken treatment? 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#783]
http://tb.plazi.org/GgServer/summary/FBEFFD0FFA54F3DFFF0FFC5FFF1FFC5

![image](https://user-images.githubusercontent.com/4609956/67291584-0aa6ca80-f4e2-11e9-9414-ad5a60a58cbb.png)

**Comment by gsautter** [comment]
Looks like this article does not exist on the server, indeed ... where did you get this UUID / URL from?

**Comment by gsautter** [comment]
Did you mean `http://tb.plazi.org/GgServer/summary/FFBEFFD0FFA54F3DFFF0FFC5FFF1FFC5` (mind the _two_ `F`s after the last slash)?

**Comment by myrmoteras** [comment]
http://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.name+doc.uploadDate&groupingFields=doc.articleUuid+doc.name+doc.uploadDate&FP-doc.uploadDate=%222019-10-22%22&format=HTML

**Comment by gsautter** [comment]
Mind the two leading `F`s at the start of this UUID ...
![image](https://user-images.githubusercontent.com/5789714/67297083-b30c5d00-f4e9-11e9-9e45-525a6d980cfd.png)
