### ISSUE TITLE
page header blue colored

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#785]
why is the page header blue, unlike the rest of the text?

https://user-images.githubusercontent.com/44419136/68423820-8dd24c80-0181-11ea-97c1-b04a7fca30be.png

**Comment by gsautter** [comment]
Because it's a page header (text stream type "pageTitle") ... those have always been blue. The article header is cut away just like the headers at the top and bottom of every other page, simply because they are not part of the actual article text, but rather front matter or whatever.
