### ISSUE TITLE
figure broken

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#793]
https://user-images.githubusercontent.com/57402751/68500878-87081000-023b-11ea-838f-49d6b8e14a51.png

http://tb.plazi.org/GgServer/summary/FFA74D256428FFA38F0BFF91FFEEFF9A

**Comment by gsautter** [comment]
Fixed via figure repair service ... not sure how this one could have slipped the general repair over two years ago, however ... maybe someone held the lock.
