### ISSUE TITLE
wrong treatments

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#8]
@gsautter in this http://tb.plazi.org/GgServer/summary/593BFF8BFFEDFFE3FF99FF86FFE5FFA6 article, the treatment boundaries are wrong. They are at genus not at species level.

Is there a way to fix this automatically, or do we need to fix this manually? if so, let me know

**Comment by gsautter** [comment]
What ultimately happens is that structure detection fails to recognize the actual treatment headings, which are the numbered ones, as they are too close to the text below them. Consequentially, the genus level headings become the treatment headings, bundling up all the species level treatments grouped below them. While this is not even outright wrong (having genus level treatments listing species, just like a checklist), I very well understand it's not really correct, either.

It's hard to fully automate this one ... However, it is very possible to use patters to tag the actual treatment headings, then remove the `treatment` and `subSubSection` annotations and re-run "Tools -> Mark Treatments (Headings Only)". That should be the most efficient approach by far. I might also try and integrate this in the server side batch.

**Comment by gsautter** [comment]
Repaired. I finally found out why the numbered treatment headings (as in this monograph) didn't support treatment detection as supposed to, and managed to fix it.

The server batch is updated, and a new build is out.
