### ISSUE TITLE
BLR upload: missing value in related identifier

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#80]
The automatic upload of new articles often does not complete the last related identifier

![image](https://cloud.githubusercontent.com/assets/4609956/23159185/1b8f368a-f822-11e6-9a97-9a0e63e3edfc.png)

https://zenodo.org/deposit/321255

This then has the consequence, that after editing the recod cannot be saved anymore.

**Comment by gsautter** [comment]
That looks like a Zenodo issue to me ... Their API doesn't even accept a related identifier without a proper type, so this cannot come from invalid date we upload.

**Comment by myrmoteras** [comment]
@gsautter created an issue at Zenodo that includes some more unfixed examples. It is also only happening to articles, not images.

https://github.com/zenodo/zenodo/issues/970

The automatic upload of new articles often does not complete the last related identifier. According to our input, the attribut eg "is part of this upload"

![image](https://cloud.githubusercontent.com/assets/4609956/23259521/c2fe839c-f9cd-11e6-83e0-ffc655297ca6.png)

https://zenodo.org/deposit/321255

This then has the consequence, that after editing the record cannot be saved anymore.

other unfixed examples are 
https://zenodo.org/deposit/321799
https://zenodo.org/deposit/321798
https://zenodo.org/deposit/321790

**Comment by gsautter** [comment]
As stated before, this looks a lot like a Zenodo UI issue ... invalid data on our part cannot be the cause, simply as the Zenodo API would squarely refuse it, so nothing we could do from our end ...
