### ISSUE TITLE
accessionCode MB... to be removed

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#809]
MB is for Mycobank, We do not right now know how we can link this - I will check this out.

MB 81298

So please remove make sure, the MB... is not linked to NBCI Genbank

example has been http://treatment.plazi.org/GgServer/html/344A4E03FFE3FFE3FF66F97F8E54FB38

**Comment by gsautter** [comment]
Added a filter to the tagger script to exclude "MB" accession numbers from linking.
