### ISSUE TITLE
BLR upload: licence specification according to the source article

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#81]
When an article is uploaded to BLR, then it becomes automatically a closed access article. Is there a possibilty that this could be changed so that OA articles stay OA? may be by adding a field in the metdata that allows simply OA / Closed access, or more refined using the licence if there is one?

For example, the EJT articles are all OA, but in BLR they are closed.

**Comment by gsautter** [comment]
There is a filter deciding between "open" and "closed" ... it's just that this filter is pretty conservative, for obvious reasons. If you tell me to make EJT generally "open", no problem there.

Added EJT now, filtering based on the DOI.

**Comment by gsautter** [comment]
PS: This issue hardly has anything to do with GGI ... any reason it is in this very tracker?
