### ISSUE TITLE
materialsCitation: backReference, 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#811]
`loc. cit.` an additional sign  for the automated markup of `backReference`
![image](https://user-images.githubusercontent.com/4609956/69564930-37a03e80-0fb4-11ea-9fe2-f408ccfce8ef.png)

**Comment by gsautter** [comment]
Just checked the code ... "loc. cit." is already on the list. Do you have a document UUID for me, so I could test this?

**Comment by myrmoteras** [comment]
FFAA2C467A5D4A74FFF8FFC0DA23FFE3

**Comment by gsautter** [comment]
Turns out the new materials citation logic does handle "loc. cit." just fine (in "Extract Materials Citations"), only the older logic still in use in "Parse Materials Citations" does not ... will be solved once I get around to the latter using the new logic (see that list compiled earlier).
