### ISSUE TITLE
taxonomicName authority and authorityName different

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#813]
![image](https://user-images.githubusercontent.com/4609956/69567476-bf3c7c00-0fb9-11ea-8f5b-2ad91069cc2c.png)

C873367BFFE0FFE5FFEEFFC78C42FF84

this happened also in  FFAA2C467A5D4A74FFF8FFC0DA23FFE3

**Comment by gsautter** [comment]
Fixed ... was an issue in the authority augmenter (the gizmo importing authorities from GBIF, etc.), which forcefully set the document authors even if there are author names on the taxon name proper ... comes with next build.
