### ISSUE TITLE
dashbboard: missing figure 13

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#82]
@gsautter 
your help needed: IN this chart, figure 13 and 19 do not show up. Can you help?

![image](https://cloud.githubusercontent.com/assets/4609956/23164811/53fc7214-f839-11e6-9cf1-aa5a5d198641.png)

[346-1786-1-PB.zip](https://github.com/gsautter/goldengate-imagine/files/790065/346-1786-1-PB.zip)

163-941-1-PB: Bosselaers J. & Jocqué R. 2013. Studies in Liocranidae (Araneae): a new afrotropical genus featuring a synapomorphy
for the Cybaeodinae. European Journal of Taxonomy 40: 1-49. http://dx.doi.org/10.5852/ejt.2013.40
SRS doc.articleUuid=9641FFF01026FF93FFC1CF4E123CD00A

**Comment by gsautter** [comment]
I just tested this, and it works perfectly fine, both in Firefox and in Chrome ... have you tried refreshing the page or something similar? Do the browser developer tools show any errors?

If you manage to reproduce this, please save the HTML page, zip it up together with the associated files, and send me that ZIP. It's impossible to tell what was/is going wrong from a mere screenshot, as it just works as supposed to on my machine - with the same build you have.
