### ISSUE TITLE
what  values to enter in the GGI config window at launch of GGI?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#821]
What are the values to enter here? 
![image](https://user-images.githubusercontent.com/4609956/69940232-0fe43580-14e2-11ea-9760-aa56bf814ac5.png)
 
For 1 and 2: et the "initial JVM Memory" to he standard value (128(MB)) but the "Maximum JVM Memory to 50% or 80% of the RAM of the machine. For a 16GB RAM I would set it to 1000, or the closest of a multiple of 128. This helps to optimize processing, especially if you deal with large files.

Is this correct: 
1. 3 https://tb.plazi.org/GgServer/proxy 
2. 4 443
3. 5 the users ID
4. 6 the users PWD

For what purpose is this?

When I later want to download an file from the server, I need to enter the ID and PWD again.

**Comment by gsautter** [comment]
Fields 1 and 2 are from the days when then default memory for a JVM was 64MB, which simply ran out all too quickly with all the processing logic. You can use them now to limit the resource usage of GGI, e.g. by setting the maximum to 4096, you'd limit it to 4GB. If I remember correctly, you normally run the batch with `-Xmx10240m` or something, which corresponds to 10GB, so you might want to the Field 2 to something like 10240. Field 1 is for the amount of memory the JVM gets on startup, which is mostly obsolete nowadays.

Fields 3-6 are not intended for authenticating against a GG Server back-end, but for a proxy that you might need to access the web from you local machine, like one you'd have to configure in a browser. This used to be an issue some 15 years back, but is mostly obsolete nowadays, so you can simply leave these fields empty.
