### ISSUE TITLE
BLR: linking from image to the upload of the source pdf on BLR

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#83]
Might it be possible to add one more link into the images, that is a link from the image to the source document that is in BLR, and from where there are links to its parts.

From this image https://zenodo.org/record/321260#.WKw1lKgrLAQ , it is not possible to get back to the source doc on BLR https://zenodo.org/record/321255#.WKwLWagrLAQ , whilst if is possible to get via the link from the latter to the former.

This is a bit akward, because in most cases one ends up in the DOI of the closed document, whilst it would be interesting to get to the record in BLR where all the other links allow to find related images.

**Comment by gsautter** [comment]
Partially a piece of cake, and already happening, partially a hard one:
- if the PDF gets a Zenodo issued DOI, each and every figure is has that very DOI as a related ID of type "isPartOf" (so not an issue at all in these cases)
- if the PDF has a DOI from a different source, we can hardly add the (implicit) Zenodo issued DOI along the way ... or maybe we could?

We might surely include the Zenodo record URL the DOIs resolve to, which is not all too hard at all. However, who would that benefit? The PDFs proper are mostly closed access, and for a reason so, so in the very most cases only very few people (us ...) could even follow such a link without crashing into a login wall ... do you want to give our users this experience?

**Comment by myrmoteras** [comment]
I do not know what will be tomorrow, whether this we can open up or not BLR.
What I do know now is that it is a pain to get to the PDF from an image, whilst it would be simple to click and get to the upload. I am rather for it.

**Comment by gsautter** [comment]
So add the deposition URL as an alternative identifier if there already is a non-Zenodo DOI? Piece of cake in the technical department, just say the word.

The one thing I'm not so sure about is how to impose this rule on already existing depositions ... but that might be quite possible to sort out, if at the cost of some more effort.

**Comment by gsautter** [comment]
Has long been in place, and collection update executed.
