### ISSUE TITLE
bibRefCitation not marked up FFB36B7BFF9FFFE1FF8E6C2BB719AE7B

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#838]
In this example, the bibRefCitation did not mark up using our tool

![image](https://user-images.githubusercontent.com/4609956/71959373-e4481f80-31f2-11ea-906d-4ab94d4e6a67.png)
FFB36B7BFF9FFFE1FF8E6C2BB719AE7B

**Comment by gsautter** [comment]
Got it ... we have another "first" here: references are numbered (1-39 in this case), but citation still works by author and year. Normally, numbered references are cited by number (and the citation tagger handles that), and non-numbered references are cited by author and year (which also works fine), but this mixed style is something new.
I can try and add a catch that switches to author+year citations even in the presence of numbered references if too few number-based citations are found or too few references end up cited, but that is necessarily fuzzy ... will give it a shot.

**Comment by gsautter** [comment]
Fixed ... added a check for the number of references actually cited via numbers (only kicking in if there are no bibliographic citations marked in document yet), and a switch-over to author+year if that check counts fewer than half of the references. Comes with next build.

**Comment by gsautter** [comment]
Fixed the IMF as well, though I have to say that this bibliography is quite sloppy ... "Jukna" has two references out of both 2009 and 2010, and they are cited as "2009a", "2009b", "2010a", and "2010b", resepectively, but without the "a" and "b" qualifiers reflected in the bibliography, which turns following the citations into a bit of a guessing game even for a human reader ... not the best of styles, I must say.
