### ISSUE TITLE
Zenodo Upload Authentication Problem - HTTP 403 Forbidden

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#84]
* works for EJT
* tried out this article http://tb.plazi.org/GgServer/summary/FFC31D3A0A72FFBFFFE14838E143C20A which includes images that need to be cut out. 
![image](https://cloud.githubusercontent.com/assets/4609956/23168170/7b0e2f74-f847-11e6-8c97-bfd1c66ac911.png)

Not sure, whether the cutting of images works. It might not work because it is not owned by us?

**Comment by gsautter** [comment]
You can simply mark the caption via "Mark Caption", and then mark the image as a whole via "Mark Image". The caption will _not_ be affected by this anymore.

**Comment by gsautter** [comment]
As I see, you've already fixed this one ... 

The only problem I find remaining is Figure 7, which spans two pages ... not sure how to handle this, to be honest, as it's a case we've never seen before. How frequent are such double-page figures? Considering that this is the first case in 20,000+ PDFs, I'd tend to assume so rare that we should not invest all too much effort in handling this special case ... or should we?

**Comment by gsautter** [comment]
Another interesting question is who uploaded this document to Zenodo ... must have happened with another account that the one owning BLR, as the server gets an HTTP 403 "Forbidden" response when attempting to put the deposition in "edit" mode in order to add the figures.

**Comment by myrmoteras** [comment]
it has been uploaded by the editor of Neilrichia, this journal who then asked to include it into the the biodiv community. 

Right now, I think, Zenodo cannot do too much about it, since there is only one account per community... We might have to raise this question for further editing in the future

**Comment by gsautter** [comment]
closely related to #70, I guess ... until the Zenodo guys get in place what's discussed there, we have no chance of making this happen.

On top of that, this is another extremely pathological case that has been lingering for very long ... laying it to rest for now.
