### ISSUE TITLE
[Template] Advice on multiple matCitations separator

### ISSUE THREAD

**Issue by mguidoti** [gsautter/goldengate-imagine#845]
Hi Guido,

As we start to work with more and more journals, we're realizing that most of them doesn't have a fixed separator for material citation info. This means that some papers within the same journal might use semicolon while other will use column or anything else. 

I think you probably have some intelligent gizmo behind this to overcome this issue already, but I'm curious anyways to know what trick you've implemented, or, what you suggest us to do in these cases?

Thanks

**Comment by gsautter** [comment]
If there is no fixed separator, just don't specify one ... the materials citation gizmo will then try and figure out the separator by itself, individually for each paragraph in each article, as in the absence of a strict guideline, we know that separator does vary even between treatments in the same article. It always was like that with Zootaxa, so no worries about the absence of a style-defined materials citation separator. While it does help increase both accuracy and performance (separator inference is a good bit of effort), the gizmo can definitely do without.
