### ISSUE TITLE
DOI issues by Zenodo in metadata of treatments?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#847]
in this case, the DOI has been issued by Zenodo, but it does not show up in the metadata

![image](https://user-images.githubusercontent.com/4609956/72432785-2d224a00-3798-11ea-8892-f97b1d99d4e6.png)

FFCCFFDFFF9B8F1FFFD2714DFFBCFFEA

**Comment by gsautter** [comment]
The DOI does show now ... this is the same delayed-write-back issue as #848

**Comment by myrmoteras** [comment]
ok - patience asked- we'll try to learn...
