### ISSUE TITLE
TaxonName: Error applying 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#85]
![image](https://cloud.githubusercontent.com/assets/4609956/23168594/01c3e2f6-f849-11e6-822a-8466914eba25.png)

this is the file name kirkbridge_1993_OCR.pdf . The IMF is uploaded to SRS.

The article UUID is D96FFFB3FF9C936DFB21412FFFDEFFB9

**Comment by gsautter** [comment]
A log would help ... logs usually record the full stack trace of errors, so I know where to start looking.

**Comment by gsautter** [comment]
Too late tonight to try it out ... will give it a shot tomorrow.

**Comment by gsautter** [comment]
Found it ... utterly messed up text stream sequence over the boundary of pages 17 and 18. After repairing that, FAT works as supposed to.

Did you fiddle around with the word sequence there? The way this is broken looks like it could hardly originate from decoding ... I still have to figure out how this could cause an error, as it's not supposed to, but the text stream was definitely messed up in a way that the usual word chaining routine is very unlikely to produce: backwards across a page boundary ... what did you do?

**Comment by gsautter** [comment]
The fixed document is on the server, so you can continue with the markup.

That broken text stream pointed _backwards_ across page boundaries, which confused the XML wrapper into the reported error. However, such a backward link doesn't happen on PDF decoding, which always keeps text streams forward-flowing. Must have been messed around with, this one ...
