### ISSUE TITLE
[Template] Logger sometimes doesn't work properly?

### ISSUE THREAD

**Issue by mguidoti** [gsautter/goldengate-imagine#851]
Hi Guido,

This is something that I noticed before but couldn't figure out exactly what causes it. 

Sometimes the logger simply stop updating, and closing/openning GGI again sometimes fix it.

Any clue why this might happen or tips on how to deal with this, as we need the logger to deal with RegEx and so on?

**Comment by gsautter** [comment]
Yes ... it's called buffering ... GGI buffers log output internally and writes it to the files only in batches of 4KB or so. The main reason for doing this is that every file write operation involves a permissions check with the OS, which renders byte-for-byte writing excruciatingly slow on some systems. When closing GGI, of course whatever log output remains in the buffer is written to the log file.
However, what can also cause the effect you observe (file size indicated in explorer remains the same over longer periods of time) is that your OS gets lazy on updating the size of continuously growing files after a while, most likely for efficiency reasons. Hitting F5 in the file system explorer window will refresh the file sizes.
