### ISSUE TITLE
[Template] Zoobank

### ISSUE THREAD

**Issue by mguidoti** [gsautter/goldengate-imagine#853]
Hi Guido,

Just to make sure: sometimes article provide zoobank links for the nomenclatural acts, not for the article per se.

Should we worry about these as well, or just the ones that refers to the articles?

Thanks,

**Comment by gsautter** [comment]
In the templates, you only need to worry about the ZooBank UUID of the article proper. The ZooBank issued treatment UUIDs are taken care of by TreatmentBank.
