### ISSUE TITLE
authors not detected

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#857]
here as case where the author is not properly matched
![image](https://user-images.githubusercontent.com/4609956/72625610-60f0a180-3949-11ea-8c6d-761d06266623.png)

**Comment by gsautter** [comment]
Thanks ... as many name infixes ("von", "van", "de", "della", etc.) as there already are in the respective dictionary, I guess it will never be 100% complete ... "van't" is an infix I never saw before, in fact, not even on a respective list on Wikipedia that I imported into aforementioned dictionary. Added it now, comes with the next build.
