### ISSUE TITLE
GGI: failure with large file?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#86]
Trying this file leads to a very fast end of the conversion process

```
Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Feb 21, 2017 4:56:13 PM org.icepdf.core.pobjects.Catalog <clinit>
INFO: ICEsoft ICEpdf Core 4.2.0 
Exception in thread "LoaderThread" java.lang.NullPointerException
	at de.uka.ipd.idaho.im.pdf.PdfParser.getPageFonts(PdfParser.java:2180)
	at de.uka.ipd.idaho.im.pdf.PdfParser.runPageContent(PdfParser.java:2281)
	at de.uka.ipd.idaho.im.pdf.PdfParser.runPageContent(PdfParser.java:2271)
	at de.uka.ipd.idaho.im.pdf.PdfParser.getPageWordChars(PdfParser.java:1972)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$2.doFor(PdfExtractor.java:698)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)

```
I have my config set to 10240MB

https://doi.org/10.5281/zenodo.293766 either of the OCRed files does not work

**Comment by gsautter** [comment]
That's the part that loads the embedded fonts ... looks like there's something strange about the fonts, this has nothing to do with the file size.

**Comment by gsautter** [comment]
Got it ... pages are linked to fonts in a strange way in this one, namely with one layer of indirection _less_ than usual ... which incurs an error in a status message, so not even in code that really does anything.

Fix comes with the next build, or as an update ahead of that.

**Comment by myrmoteras** [comment]
I am looking into how much this has to do with a switch from ABBYY 12 to 14. It seems, But there is also an isssue with certain scanned PDFS.

**Comment by gsautter** [comment]
Doesn't matter what this comes from ... it's an unusual way of arranging the PDF's inner data object relationships (which is why we never faced it before), but perfectly inside the scope of the spec.

I fixed it already, and the fix comes with the next build.

**Comment by myrmoteras** [comment]
the first large PDF worked, but then had problems with detectiing the three columns. I will wait until I get the new built to comment.

**Comment by gsautter** [comment]
No new build required here, just an update, which is out now and should install automatically when you start GGI with web access.

**Comment by myrmoteras** [comment]
no new upload available

**Comment by gsautter** [comment]
How about this one: http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20170228-2345.zip

Could be the auto-updater has trouble finding the updates due to the turbulence around URL `plazi.cs.umb.edu` ...

Put the following in your `UpdateHosts.cnfg`: `http://tb.plazi.org/GgServer/Updates` and the updates should work again.

**Comment by myrmoteras** [comment]
The new uploade site still does not work. No automatic upload.
