### ISSUE TITLE
Headings are selected even when the parameters are not add.

### ISSUE THREAD

**Issue by valdenar** [gsautter/goldengate-imagine#862]
Hi Guido,
When working on "Headings", when I turn on "Start Patterns" some things are selected, even when I didn't add any parameter. Is this a issue?
Additionally, when the tool "Paragraph Alignment" is marked as "centered" the paragraphs that are "justified" are also being selected (second image).
![image](https://user-images.githubusercontent.com/57402751/72732273-17d06580-3b74-11ea-8cad-ee4f786f24ae.png)
![image](https://user-images.githubusercontent.com/57402751/72732436-7b5a9300-3b74-11ea-8f3e-7a163c9295da.png)

**Comment by valdenar** [comment]
Links to issue example 
IMF:
https://drive.google.com/open?id=19SgId38qv2otsbQxEbediPsThhOpGNtv
Template
https://drive.google.com/open?id=1kprU1w81yqEZAQ1WrMdf-wSNseko3QZT

**Comment by gsautter** [comment]
Regarding "centered" vs. "justified": these two are impossible to tell apart for individual lines, as "centered" basically means the distance between left block edge and first word is equal to the distance between the end of the last word and the right block edge (with a little bit of tolerance), and for justified text, both distances are 0 and thus equal. After all, a centered line could just by accident run the full width of the block it lies in ... however, this odd-ish behavior only affects the visualization facilities of the template editor, not the behavior of the gizmo using the template to tag the headings later on, so no worries.

**Comment by gsautter** [comment]
Regarding the start patterns: These guys are strictly for filtering, so if you add an empty pattern, this basically matches everything, as the empty string is a prefix of every string ... I think behavior will change soon as you enter an actual pattern. What adding patterns by ticking on the respective checkbox also does is add the empty pattern to the template, so the respective group of parameters isn't empty and thus generates visualizations using the never empty alignment ... also a little bit odd, admittedly, but also only affecting the template editor, not actual markup behavior.

**Comment by valdenar** [comment]
Ok Guido, thanks for the replies.

**Comment by gsautter** [comment]
Added `centered_strict` alignment in the latest build I just put online, which lets you explicitly exclude justified lines now.
