### ISSUE TITLE
Question about Affixes rationale 

### ISSUE THREAD

**Issue by truschel** [gsautter/goldengate-imagine#863]
Hi Guido

Still about the Insecta Mundi template, more specifically the "Author Names in Bibliographic References". This issue is more to confirm that we are indeed doing the right thing.
I was in doubt, but talking to my colleagues here I believe we found a solution. 

In the References, I need to insert the parameter for "Location of Affixes", but this journal has differences in the order of the authors' first name, changing from the first author to the rest, as you can see in these examples:

**Weems, H. V., Jr.**, J. B. Heppner, and T. R. Fasulo. 2001. Melon fly, Bactrocera cucurbitae Coquillett (Insecta: Diptera: Tephritidae). EENY–199. University of Florida, Institute of Food and Agriculture Sciences; Gainesville, Florida. 5 p. (Available at ~ http://edis.ifas.ufl.edu/pdffiles/IN/IN35600.pdf. Last accessed June 2016.)

Nelson, G. H., **G. C. Walters, Jr.**, R. D. Haines, and C. L. Bellamy. 2008. A catalog and bibliography of the Buprestoidea of America north of Mexico. The Coleopterists Society, Special Publication
No. 4: 1–274.

In my understanding, in this particular situation, it makes no difference for GGI, as it reads "whole name"+"Jr.", with the position of the first name not mattering because the author's name is a block, and we need only to determine if "Jr." is in the middle or at the end of the name.

Is the rationale correct?

**Comment by gsautter** [comment]
Well, first of all, you do not _need_ to fill in any parameters, as they are only a help for the markup gizmos, with a default of "figure it out for yourself". Any actual value you put into a template merely helps increase accuracy.
Apart from that, your rationale is pretty much spot-on. Said parameter only matters if the last name preceds the first name or the initials (only concerning the first author of every reference here), as then there is two ways of ordering "G. C. Walters, Jr.": "Walters, Jr., G. C." and "Walters, G. C., Jr.", and the "Location of Affixes" parameter specifies which one to expect. If you omit that parameter, the gizmo will simply accept both ways.
If there is variation in this regard (if only on the first authors), it might actually make sense to omit the parameter ... it's one of those parameters you'd only specify if copy editing is really strict about it and consistently enforcing one way or the other. If copy editing can be expected to be a bit sloppy at times, better omit parameters specifying such details to prevent missed author names.

**Comment by truschel** [comment]
Thanks Guido!
Indeed, there is variation between the first author and the others and I will choose to omit the parameter.
