### ISSUE TITLE
word spacing: need some attention

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#864]
here a very recent example where word spacing is not correct
https://zenodo.org/record/3610630#.Xib9fchKjAQ

![image](https://user-images.githubusercontent.com/4609956/72809618-445fac80-3c5c-11ea-90bc-a706d98d6837.png)

http://publication.plazi.org/id/FFA6FFE8FF85CB7DB102C5500823306A

**Comment by gsautter** [comment]
I realized word spacing does vary wildly in this journal, yes ... sometimes to the point where words end up wrongfully joined inside a line. The conflated output is only a downstream effect, need to correct a few word relations in the IMF.

**Comment by gsautter** [comment]
Looking closely, some words are apart as few as 3 or 4 pixels at a line height of 28 or 29 pixels ... considering that the narrowest actual space observed throughout hundreds of fonts is some 25% of the line height, it's obvious why these word distances at times fall short of being considered a space ... Might need to introduce some statistical analysis to assess word spacing and modify the word relations accordingly, and maybe also some template parameter that warns GGI that a specific journal just crams as many words into a line a possible.
The dangerous part here is that we also have seen some journals that stretch lines to the point of adding gaps between individual letters for justification, and with those a general reduction of minimum word gaps might well have quite adverse effects ... "Tools > Join Shattered Words" actually exists to correct the latter ... and most likely it is getting a "Tools > Split Conflated Words" sibling to the reverse avail to counter the current situation.

**Comment by gsautter** [comment]
Done ... I finally got this to work, catching the few lines with problematic word distance _distributions_ based upon an ad-hoc dictionary compiles from all the other lines ... comes with next build.
