### ISSUE TITLE
PDF not opening on GGI

### ISSUE THREAD

**Issue by valdenar** [gsautter/goldengate-imagine#865]
We're having a particular issue opening the paper linked below (this didn't happen with any other papers, so far).

Every time it hits 41%, GGI gets stuck (we've waited for roughly 30 minutes for something else to happen, to no avail). What is quite weird is that this paper was working fine until earlier today, and for some reason now we started to get this error (the .err log file doesn't have any useful information about this particular situation).

We've tried restarting GGI and the computer as well, but the problem persists.
As an experiment, we compressed the PDF file (also linked below, with the IMF), and this time GGI opens it normally. Any guesses as to why we might be dealing with this?

As a final note, at the same time this started to happen, all other files were opening more slowly (in all 4 computers).

![image](https://user-images.githubusercontent.com/57402751/72835996-842d9080-3c6a-11ea-91d0-d321cfb570bd.png)

Link to PDF
https://drive.google.com/open?id=182sgeipcnYh5tzGpon1NTXKmRGmsWusi

Link to PDF (compressed)
https://drive.google.com/open?id=10aQ2zB-oU1W8K_OCYuj2sXkwNIX3Jh15

Link to IMF (compressed)
https://drive.google.com/open?id=1AZOebe9f-pZ23n8H6vajpM_BycRUIMM-

**Comment by gsautter** [comment]
I see GGI is attempting to store figures and graphics when it hangs ... could this be a disk space issue? Merely a thought ... does it work on other machines?

**Comment by gsautter** [comment]
Another (more likely) issue could be that a change in a template drives the PDF decoder into some endless back and forth ... were there any changes to the template between when it last worked this morning and since it started failing on at least one machine later? There were no updates from my end in this time frame, so something else must have changed.

**Comment by mguidoti** [comment]
Hi Guido!

I don't think it's a disk space as we have still something like 200 GB availble in each machine.

And it can't be the templates because we've tested in two machines, one of them without the template.

**Comment by gsautter** [comment]
I would have been amazed about a disk space issue, to be honest, considering how fresh these machines are ... just wanted to make sure.

**Comment by gsautter** [comment]
If nothing else changed, either, this gets even more weird ... I didn't touch the routine the PDF decoder appears to be stuck in in well over a month ... will check out the PDF.

**Comment by mguidoti** [comment]
It's also strange that they all reported some delay in the PDF conversion this day...

**Comment by gsautter** [comment]
Delay or complete hangup? I got something similar, the whole thing appears to be stuck in a call to ImageMagick, a command line image analysis tool the PDF facilities use to decode several image formats ... will have to check what might be going on there.

Wild idea: what happens if you _disconnect_ a machine from the web and try the whole thing offline? It's not outside the realm of possible that ImageMagick is attempting some web lookup that gets stuck on the far end ...

**Comment by mguidoti** [comment]
We'll try!

**Comment by gsautter** [comment]
Looks like the certificate of the ImageMagick version that comes with the PDF facilities ran out yesterday ... I'll download the new version and try again.

**Comment by flsimoes** [comment]
Just tested it (offline) and got the same result:

![image](https://user-images.githubusercontent.com/3343086/72840003-1edd9d80-3c72-11ea-99fc-50e667eafbf3.png)

Not sure if it is relevant, but the Default.imagine date was 2019.12.18.21.14

**Comment by gsautter** [comment]
Thanks, @flsimoes ... no, this is not a GGI versioning issue at all. Apparently, starting today Windows refuses to execute the old ImageMagick version due to an expired security certificate. I already downloaded a new one and got it back to work, if at the cost of having to use a slightly more complicated command ... will try and see if I can overcome the latter.

Bottom line: I'm on it, so you guys might just have to sit back until I got a handle on this.

**Comment by gsautter** [comment]
Figured it out ... a new binary is coming your way soon.

**Comment by flsimoes** [comment]
Thanks Guido!

**Comment by gsautter** [comment]
The new build I just put online comprises a new ImageMagick binary (more recent version) that fixes the certificate problem.

**Comment by mguidoti** [comment]
Guido,

We still couldn't open it... Here's the `err.log`, which doesn't seem to be very informative in this case. Let us know if there is anything we can do from our end. Thanks a lot.

[GgImagine.20200128-0951.err.log](https://github.com/gsautter/goldengate-imagine/files/4122421/GgImagine.20200128-0951.err.log)

**Comment by gsautter** [comment]
The error log reports little beyond the fact that the free fonts the font decoder uses for reference were successfully installed ...
Where does the decoding process hang now with this PDF? Still at the same spot? If so, please go to `<GGI>/ImageMagick` and check the size and change date of `convert-windows.exe` ... should be some 13MB (the old one was 15MB). If you still have the old one, try deleting that and restarting GGI. If the problem remains, please send the `...out.log`, as that one reports on the startup process, which installs these binaries among other things.

**Comment by mguidoti** [comment]
So, the `convert-windows.exe` is around 13 MB as you said, and the process was halted at the exact same point (~41%), every time. 

The `...out.log` is a bit too heavy to be posted here (~120MB), so here's a print screen of the tail of this file:

![image](https://user-images.githubusercontent.com/44419136/73298751-a71cef00-41ec-11ea-9a62-ef264accc707.png)

Let me know if this helps or if you need **anything** else from us.

Thanks, Guido.

**Comment by gsautter** [comment]
Thanks for the tail ... however, this looks like GGI is busy storing the vector graphics, which not even involves file IO at this point. Could be the beef is still in the buffer ...
To avoid the latter, please try starting GGI from the command prompt (not the `.exe`) with this command: `java -jar -Djava.io.tmpdir=./Temp GgImagine.jar RUN ONLINE LOG=IDE` (the `LOG=IDE` part directs log output directly to the console without the buffering, which is what I use for testing and development). The try and open that notorious PDF again, and let's see where the log output on the console stops.

**Comment by mguidoti** [comment]
Will do, thanks!

**Comment by valdenar** [comment]
Hi Guido, here it is.
![image](https://user-images.githubusercontent.com/57402751/73300635-2102a780-41f0-11ea-97d4-9dd8c7364e42.png)
![image](https://user-images.githubusercontent.com/57402751/73300681-34ae0e00-41f0-11ea-9557-bb9dc2391602.png)

**Comment by gsautter** [comment]
OK, this is officially weird ... as stated above, the vector graphics should not pose any stumbling block ... will test.

**Comment by mguidoti** [comment]
If you need anything from here, ping us. 

Thanks for your time, Guido.

**Comment by gsautter** [comment]
Figured out the graphics part, at least: it still actually hangs on image decoding, it's merely that the other threads continue, e.g. storing graphics, and the ultimate hang-up only happens when waiting for that one thread to finish when going back to single-threaded mode after the parallel figure decoding passage ... will take it from there.

**Comment by gsautter** [comment]
This is getting stranger and stranger ... turns out all the ImageMagick based figure decoding terminates normally as supposed to, but something else hangs up downstream ... will dig deeper.

**Comment by gsautter** [comment]
With a bit of black magic, I was able to pinpoint the problems to the very first page now ... one thread hangs up there, while the others continue successfully with the rest of the pages, which is why locating the troublemaker was a bit tricky ... keeping on digging.

**Comment by gsautter** [comment]
Reproduced and verified ... the irony being that the troublemaker is not even part of the article proper, but decoration in the top left corner of the cover page ... will see how far I get ...

**Comment by gsautter** [comment]
Quick workaround for you guys (I'm seeking a more general solution, of course): After GGI hangs up, go to Task Manager, find a process named `convert-windows.exe`, and terminate that process.

Background: ImageMagick runs just fine and even converts and delivers back the decoded image as supposed to, but for some reason the sub process fails to terminate afterwards ... I'll try and figure out why.

**Comment by gsautter** [comment]
Figured it out ... just a minor thing, really, and one that took ~25,000 PDFs before causing any problems at all ... devil's in the details ... update with a fix is out.

**Comment by valdenar** [comment]
Hi Guido,
now it's working, the PDF is opening.

Thanks a lot!

**Comment by mguidoti** [comment]
Guido thanks for taking the time to explore this issue and specially for sharing with us your rationale. We learn A LOT from this, you've no idea.

We end up never trying to end the `convert-windows.exe` task, by the way.
