### ISSUE TITLE
Problem with RegEx for authors in Insecta Mundi journal

### ISSUE THREAD

**Issue by truschel** [gsautter/goldengate-imagine#868]
Hi Guido

I have a problem with a RegEx for authors in the journal Insecta Mundi. I created a RegEx for authors which apparently works, however GGI doesn't identifies the names separately because the journal doesn't have a separator for authors names, such as a comma, for example. Is there a solution for this problem?

![image](https://user-images.githubusercontent.com/57402704/72897403-a671ed80-3d00-11ea-9b42-2c10b0c6b64e.png)

![image](https://user-images.githubusercontent.com/57402704/72897472-d15c4180-3d00-11ea-9bbf-19b8e6ba73e6.png)

See below the links for this paper:

PDF https://drive.google.com/open?id=1mf4moJ9Q4SdHZ3crmbck6eArcxCY7lXE

IMF https://drive.google.com/open?id=11ePznBr7vX-rFucQeGWYH8TuIYNkl3qJ

Template https://drive.google.com/open?id=1hcs-mjX6fSpTwSeceMavtTHnRcOqcwlD

**Comment by gsautter** [comment]
I think there is, if most likely a technical one ... I could interrupt the strings the patterns work on when excluding intermediate words based upon other criteria like the font size, or cut it up at block boundaries. Let me think about this for a bit, I'm sure we'll find a solution.

**Comment by mguidoti** [comment]
Thanks, Guido.

**Comment by gsautter** [comment]
Added the option to use line breaks as value separators in multi-values attributes (authors, editors) now, build is out.

**Comment by flsimoes** [comment]
Hi @gsautter

I've picked up on @truschel 's work and we still got the following situation with the authors' names, even with your individual lines fix.

As you can see below, the `.log` is showing us that the names are being properly split. However, when we check the `Metadata` the names are again merged together (without the "&" to separate them).

Here's the IMF [0733_Medina_etal_2019](https://drive.google.com/open?id=1TKhVrIDZThH20kwVMMqj_SOJP8kOOrPR)

![image](https://user-images.githubusercontent.com/3343086/74039403-7e40ea80-49a0-11ea-82f9-3c34008bd421.png)

![image](https://user-images.githubusercontent.com/3343086/74039449-99135f00-49a0-11ea-832a-83edf3e6d2a1.png)

![image](https://user-images.githubusercontent.com/3343086/74039491-adeff280-49a0-11ea-92f5-3c09fab445c6.png)

**Comment by gsautter** [comment]
Figured it out ... all you need to do is (a) set the "Individual Values on Single Lines?" flag and (b) prevent the `\s*` space matchers from matching line breaks, which works most easily by replacing them with an explicit matcher on the space character, namely `\x20*` (after `\x`, the next two characters are interpreted as a HEX coded character, and `20` (decimal 32) is the regular space).

**Comment by flsimoes** [comment]
That's quite cool! This indeed solved the problem.
Wasn't aware you could specify the amount of spaces. This might be quite useful in other instances as well.
Thanks a lot Guido!

**Comment by gsautter** [comment]
Not the amount of spaces ... the _types_ of spaces ... normal spaces (`x20`) are matched by `\s` as much as line breaks (`x0A`) and carriage returns (`x0D`) and tabs (`x08`), which is why your original pattern matched over the line breaks inserted in the overall string (before the value pattern is applied) when you select "Single Line Values". Now using `\x20` instead of `\s` restricts matching to normal spaces (`x20`) only, so the line breaks act as the separators they are supposed to be.

None of this modifies the behavior of the quantifier `*` (zero or more times) proper, only what this quantifier pertains to.

**Comment by flsimoes** [comment]
Makes more sense, I completely misread the regex logic.
Still, this way it is even more useful as we can use it according to various specific situations.
