### ISSUE TITLE
Zoosystema - Headings 2

### ISSUE THREAD

**Issue by flsimoes** [gsautter/goldengate-imagine#869]
Sorry about the length of this one, but I've been trying to deal with Headings 2 in Zoosystema, and so far I haven't been able to figure out a configuration that will isolate the bits of text I'm interested in. 

In the following series of images, I will try to summarize how complicated these are and show some of the combinations of parameters I've tried out (I've also tried using "Block Layout" in tandem with the headings patterns, but it doesn't seem to make any difference).

For context, font size is 11 all the way through (headings and main text) and it contains _italics_. There are no All-Caps words and **bold** is not necessarily present. Also, the configuration seen in the following image was the one that bore the best results:
![image](https://user-images.githubusercontent.com/3343086/72903020-40d72e80-3d0b-11ea-8e6d-b5e253b3b56a.png)

In all configurations, GGI can't match the "Genus" line when it is connected to higher taxonomic groups, as seen below:
![image](https://user-images.githubusercontent.com/3343086/72903121-69f7bf00-3d0b-11ea-8bc6-c7b1b12551b5.png)

Additionally, bits of main text like the ones below, have exactly the same font details as the headings themselves:
![image](https://user-images.githubusercontent.com/3343086/72903189-8a277e00-3d0b-11ea-8581-751761f225dd.png)
![image](https://user-images.githubusercontent.com/3343086/72902600-88a98600-3d0a-11ea-930c-c55ba46250a0.png)
![image](https://user-images.githubusercontent.com/3343086/72898175-585de980-3d02-11ea-8c5c-93b73bcba35d.png)

Any suggestions on how to deal with this? I've thought about using the vertical and horizontal distances of the "Block Layout", but I'm pretty sure that won't solve it.

For reference, this is my "Block Layout" regex: `{PO:C}\(\s*F\s*i\s*g\s*.*\)`

Template (docStyle) link: https://drive.google.com/open?id=175TPGOji6ICR2_vu_F_B3t29NNNNIomJ
Sample PDFs: https://drive.google.com/open?id=1bCoNHuWrcr4YMExWsbYTxMlCRaHzEDY7
https://drive.google.com/open?id=19fbOA-s8iYM3o-jtSvep-6SvMgJW0aS1
https://drive.google.com/open?id=1at_6TyWGdZuAmUwgwtKzZx2zQLmpPbq1

**Comment by gsautter** [comment]
First of all, I'd recommend to un-tick the "First Line Indented" checkbox.

**Comment by gsautter** [comment]
Second, there already is a ticket on the headings in Zoosystema (and other journals): https://github.com/gsautter/goldengate-imagine/issues/840

Closing this one as a duplicate. Please check with the other guys before opening new tickets ... unless you plan to intentionally swamp me ...
