### ISSUE TITLE
decoding error: words separated with spaces during conversion

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#87]
Is seems, that during the GGI conversion process, words are taken apart. In this case 
http://treatment.plazi.org/id/03C587EA835EFFFEFCE9FC60F8D4FA2D

![image](https://cloud.githubusercontent.com/assets/4609956/23178032/37145948-f869-11e6-9279-e4ea8fc9df61.png)
in comparison to the source
![image](https://cloud.githubusercontent.com/assets/4609956/23178052/4c9f5e16-f869-11e6-9473-322a60375b5f.png)

often it seems to occur inbetween a captial letter and the followin lower case
![image](https://cloud.githubusercontent.com/assets/4609956/23178111/7f613fc2-f869-11e6-94f3-0324577687e3.png)

**Comment by gsautter** [comment]
This looks like coming from the OCR ... little influence we could take there, as this is handled by Tesseract. Does ABBYY fare better?

Or is this done with ABBYY and then imported with OCR text? In that case all the same, the text is taken as it comes.

**Comment by gsautter** [comment]
I've tested page 4 (number 809) now, and the words in questing do come up in exactly the parts that end up in the document ... ABBYY just splits them, so little GGI could even do about it.

You'll just have to merge them one by one. Or maybe it's possible to customize ABBYY to get it right?

**Comment by gsautter** [comment]
see also #68

**Comment by gsautter** [comment]
discussed in most detailed in #89 , no need to duplicate this here.
