### ISSUE TITLE
[Template] Question on the anchors

### ISSUE THREAD

**Issue by mguidoti** [gsautter/goldengate-imagine#872]
Hi Guido,

Again, just clarifying how GGI works. We've come to realize that we'll have to split one template into two due to some small layout changes in one specific issue for Insecta Mundi. No biggy. 

But in order to do this, we'll have to implement two anchors, so GGI can tell them apart. Again, no biggy.

My question here is about how GGI go through the anchors. We noticed that the anchors are displayed on alphabetical order in the template creator, but does this matter? How GGI goes through them? One by one? One after the other? What do you recommend?

I remember that you explained this to me in Paris, last September, but I'm not quite sure if I remember it correctly.

Thanks in advance, Guido.

**Comment by gsautter** [comment]
OK, here the selection routine:
- first, find all templates for which at least one anchor matches
- return match if only one template left
- compute _fraction_ of matching anchors (divided by number of existing anchors) for each remaining template, and determine maximum
- remove all templates that have a matching anchor fraction below that maximum fraction
- return match if only one template left
- get absolute _number_ of matching anchors  for each remaining template, and determine maximum
- remove all templates that have a number of matching anchors below that maximum number
- return first remaining match (if selection remains ambiguous at this point, some anchors should most likely be a bit more selective, or you simply need to add a few more ...)
