### ISSUE TITLE
Question on "Maximum Page After First" for create anchor

### ISSUE THREAD

**Issue by truschel** [gsautter/goldengate-imagine#873]
Hi Guido

As Marcus described on issue #872 , I am creating a second anchor for the Insecta Mundi template. I choose the year placed on the third page of paper and I informed GGI the "Maximum Page After First" as "3". 

![image](https://user-images.githubusercontent.com/57402704/73014317-b53bcb80-3df8-11ea-9368-1514d2a9fe67.png)

However, the GGI is not recognizing this parameter. GGI search for the anchor in the first page (identifies as DPI).

![image](https://user-images.githubusercontent.com/57402704/73014889-bf11fe80-3df9-11ea-9735-4079ecd2e5b5.png)

I tested if the GGI is really looking for the anchor only on the first page, expanding the extraction area. Indeed, GGI does because it found the word "Systematics":

![image](https://user-images.githubusercontent.com/57402704/73014918-c89b6680-3df9-11ea-8f14-6090d1fc3215.png)

This is the page and extraction area for the GGI identify:

![image](https://user-images.githubusercontent.com/57402704/73015640-2ed4b900-3dfb-11ea-8b57-1e0490bca651.png)

What do you suggest?

**Comment by gsautter** [comment]
Suggest I extend anchor _testing_ to actually observe this parameter (document style _assignment_ already does) ... sorry for the inconvenience.

As a stop-gap solution, you might try and use "Date of Issue: ..." on the first page instead, I guess.

**Comment by gsautter** [comment]
Done in the build I just put online.
