### ISSUE TITLE
Parameters of Anchor 

### ISSUE THREAD

**Issue by truschel** [gsautter/goldengate-imagine#874]
Hi Guido

We observed a strange behavior of GGI when the parameters of Anchor are altered. If we delete a determined parameter and close the window (even when we have saved the template), the parameter disappears if the window is opened again. 

![image](https://user-images.githubusercontent.com/57402704/73017276-45c8da80-3dfe-11ea-8bcd-a0b5e62a4421.png)
![image](https://user-images.githubusercontent.com/57402704/73017299-511c0600-3dfe-11ea-84ba-4917f3ccebac.png)

**Comment by gsautter** [comment]
OK, this is weird, if only a bit ... if you un-tick the checkbox to the left of the parameter name, whatever parameter value will _not_ be saved, as the un-ticked checkbox indicates the parameter is inactive.

The part that remains weird (and for me to check) is why not _all_ the anchor parameters come back up after re-opening.

One thing for you to change (at least judging from the `...2009-2019` template name) is the pattern, as `2019` won't match any articles from any other years.

**Comment by gsautter** [comment]
Fixed with the build I just put online.
