### ISSUE TITLE
Block Layout/Heading unusual cases

### ISSUE THREAD

**Issue by valdenar** [gsautter/goldengate-imagine#875]
Hi Guido,

When I place some patterns in the Block layout a green mark appears. however, the blocks are not separated.
![image](https://user-images.githubusercontent.com/57402751/73014010-2b8bfe00-3df8-11ea-86d7-d8ae573b3fad.png)

When I run the tool "Detect Document Structure" some unusual heading markings are made. Examples are below
In the first, within the block only one sentence is marked as a heading.
![image](https://user-images.githubusercontent.com/57402751/73014225-8b82a480-3df8-11ea-89eb-43468b4093c4.png)

In the second image some phrases are marked as the same heading.
![image](https://user-images.githubusercontent.com/57402751/73014362-c553ab00-3df8-11ea-8eff-17c9661dad55.png)

Link to PDF
https://drive.google.com/open?id=1cgxe8PKc8XZZLu5KovA5r2WvkzMMGmHf
Link to template
https://drive.google.com/open?id=1kprU1w81yqEZAQ1WrMdf-wSNseko3QZT

What do you think about this?

**Comment by gsautter** [comment]
The split line patterns exist to identify lines that start new _paragraphs_ in blocks too small (too few lines) to do a conclusive and reliable statistical analysis of the layout ... they are _not_ intended to split blocks proper.

Try hovering over the "Split Line Pattern" field label ... that should bring up an explanation.
