### ISSUE TITLE
table issue: header row shifted FFA6FFE8FF85CB7DB102C5500823306A

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#877]
in this example, the header row has shifted to the left. Is this a GGI issue (http://treatment.plazi.org/id/039F8790FF87CB7AB2DBC0C40BE137DC   )or display at GBIF https://www.gbif.org/species/160690163 ?

![image](https://user-images.githubusercontent.com/4609956/73156213-64202600-40dd-11ea-85d6-eaa4a3b43fe9.png)

**Comment by gsautter** [comment]
Well, the empty top left cell is indicated in the XML (http://treatment.plazi.org/GgServer/xml/039F8790FF87CB7AB2DBC0C40BE137DC , saying `gridcol=1`), but that wasn't correctly translated into an empty cell be the XSLT ... fixed this now, DwC-A is scheduled for repacking.
