### ISSUE TITLE
Images not correctly converted by GGI

### ISSUE THREAD

**Issue by valdenar** [gsautter/goldengate-imagine#883]
Hi Guido! 
We are working on these individual extractions and the same problem has been happening. Some figures are not completely converted in GGI in more than one computer.
This started happening after the last update of the GGI.
Here are an example of one figure that was not loaded.

Link to IMF
https://drive.google.com/open?id=1v8CxfjOpTmUeN5JidZ41y57A98Vl3IMa

Link to PDF
https://drive.google.com/open?id=1ITh5SykAFfRWm203_N5nhJdZlqpkC93c

![image](https://user-images.githubusercontent.com/57402751/73454266-7653cb80-434c-11ea-9ce6-9c503d49a071.png)

![image](https://user-images.githubusercontent.com/57402751/73454842-aa7bbc00-434d-11ea-9d2d-4e6557992221.png)

![image](https://user-images.githubusercontent.com/57402751/73454312-8ff51300-434c-11ea-81eb-ebbcc3e5bfab.png)

**Comment by gsautter** [comment]
You are right in that the figures in this one come up wrong, even though I don't think it has anything to with the last fix ... said fix was for JPEG2000 encoded images (which decode via ImageMagick), and these figures here decode via completely different means.
From my first couple of tests, I tend to think this is mainly a rotation issue, as the raw figures have different orientations from what I see in the PDF when opening it in Acrobat ... digging deeper.

**Comment by gsautter** [comment]
Looking closer, we have another first here ... thus far, we've only had figures rotated some 90° (e.g. landscape images rotated to portrait and rendering bottom-up together with their captions to fit a page in a higher resolution) and images that come flipped about their horizontal or vertical axis (for whatever reasons). Now some of these images are flipped about their either one of their _diagonal_ axes ... didn't have a coping mechanism for that thus far, will see hoe to get a handle on these guys.

**Comment by gsautter** [comment]
Figured it out, finally ... this one required a whole new handling of figure rotation and flipping ... comes with next build.

**Comment by valdenar** [comment]
Hi Guido,
The figures are loading correctly, but there are still cases of rotation. Figures that did not have this problem are rotated.
![image](https://user-images.githubusercontent.com/57402751/73746905-0ae77080-4735-11ea-9843-51583c3096d2.png)

**Comment by gsautter** [comment]
@valdenar got it ... this is another mechanism kicking in here, if one related to rotating figures into their correct position: block flipping, i.e., the mechanism that will turn a whole page block written in bottom-up direction to the horizontal to simplify both analysis and reading. This is aimed primarily at tables, but also at landscape figures, that are turned left by 90° in the PDF (mostly together with their captions) to better fit the portrait page format.

**Comment by gsautter** [comment]
I added a sanity check for the block turning mechanism not to prevent it from taking on such small-area blocks, as its intended target are large blocks that would not fit in the page width if printed in their actual reading direction.

**Comment by valdenar** [comment]
Ok, Guido. Thanks!
