### ISSUE TITLE
PDFs without metadata

### ISSUE THREAD

**Issue by valdenar** [gsautter/goldengate-imagine#884]
Hi Guido!
We have a problem with the Journal of Paleontology. Some PDFs of the year 2019 do not have metadata. This Journal is import because publish a large number of the new species. We worked on the template, but this problem is yet to be solved. Any suggestions to solve this?

link to examples:
https://drive.google.com/open?id=1r8at1sMULG2HpbSEBUR6-Bd03tmEh3Zh
https://drive.google.com/open?id=1qGjCQDbxsMQF4yAfm7picB3QhXvLsl90

**Comment by mguidoti** [comment]
Hi Guido,

To better illustrate and perhaps save you time, here are the screenshots:

**Comment by gsautter** [comment]
@mguidoti your idea with the DOI lookup gizmo is spot-on, that's exactly what we should do in such cases, the more so since the is preciously little else we _could_ do as part of a fully automated process.

A prerequisite would be that the PDFs at least contain the DOI, though, and that we have a good extractor template for the latter. Is that the case?

**Comment by mguidoti** [comment]
Yes, Journal of Paleontology has DOI in the PDF in all papers from at least 2015... 

So, in this case, it _would_ work!

**Comment by gsautter** [comment]
Great ... I'll get to work on the lookup gizmo.

Maybe I should add a flag to the metadata template to the avail of "Use Web Service Lookup" to control the behavior of the gizmo? Makes little sense to do a lookup if all the data _is_ in the PDF proper, like we have in many journals thus far ...

**Comment by mguidoti** [comment]
Totally agree.

If the data is in the paper, we should first try to use it. It's one less step in the process.

Thanks a lot, Guido.

**Comment by gsautter** [comment]
Added the "Use External Sources to Complete Metadata?" now, and straightened out the architecture of the underlying lookup providers ... comes with next build.

Please observe that you can (and always could) also use these guys via the "Search" button in the metadata editing dialog.

**Comment by mguidoti** [comment]
But the metadata editing dialog is not intended to be used when batch processing, right?

Thanks for adding this. We're looking forward to use this feature in the templates.

Best!
