### ISSUE TITLE
bibRefCitation: missing: how to mark up

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#893]
how to fix missing bibRefCitations?
![image](https://user-images.githubusercontent.com/4609956/73816729-a508f080-47e9-11ea-8f47-d7ffa66e60e4.png)

**Comment by gsautter** [comment]
I see why this one got missed ... "Greef" is not "Greeff" ... your best bet in such cases is to re-run "Tools > Mark Bibliographic Citations" (will only show the ones not marked so far if there are any) and manually assign the cited reference.

As you might also want to mark the treatment citation afterwards, you right now have to take a little detour (I will remember to make the function available in the "Tools" menu in the next update):
- go "Edit > View Document as XML" or use XML view of treatment
- go "Tools > Execute GAMTA Script" and run `TreatmentCitationTagger.gScript` in either XML view

**Comment by gsautter** [comment]
Looking at the document (UUID from https://github.com/plazi/EJT-testbed/issues/607 ), the above fix for the "Greef" citation (misspelled more often than spelled correctly as "Greeff", with the latter being in the bibliography), works like a charm ... after manually assigning the cited reference in "Tools > Mark Bibliographic Citations", the treatment citation marker script does the trick in the XML view.
