### ISSUE TITLE
treatmentCitation: how should it look like?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#894]
in ejt-600 in this treatment there is a problem

how should the treatmentCitation, treatmentCitationGroup markup look like?
![image](https://user-images.githubusercontent.com/4609956/73817183-9ec74400-47ea-11ea-9bf4-3b939a54266f.png)

This is how it looks like right now: treatmentCitation.

here the taxonomicNames (see the nesting)
![image](https://user-images.githubusercontent.com/4609956/73817326-e948c080-47ea-11ea-9a7c-6f16926d288a.png)

and here after removing nesting:
![image](https://user-images.githubusercontent.com/4609956/73817359-febdea80-47ea-11ea-8daf-276e34fc7fd1.png)

and here the bibRefCitations. The marked bibRefCitation I added later

![image](https://user-images.githubusercontent.com/4609956/73817420-2614b780-47eb-11ea-8e60-fd351d85589a.png)

here the treatmentCitationGroup, which seems not be right
![image](https://user-images.githubusercontent.com/4609956/73817477-4a709400-47eb-11ea-9201-e4b3d3be82f3.png)

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/73817786-21043800-47ec-11ea-9a32-dac0908d9743.png)

**Comment by gsautter** [comment]
The treatment citation groups in the last one (Greeff, not Bruzelius, please let me reply to one screenshot before posting the next, or number them for reference) look OK, apart from the missing one. Did you go via the XML view as I suggested? And is this last picture before or after that?

The Brozelius picture looks OK as well, just seems "Muller & Troschel" doesn't resolve against the bibliography.

**Comment by gsautter** [comment]
As suspected, looking at the document (UUID from https://github.com/plazi/EJT-testbed/issues/607 ) it turns out there is no reference for "Muller & Troschel 1842", only "Muller & Troschel 1840", so citations of "Muller & Troschel 1842" will not tag, and consequently there won't be any treatment citations, either. All just downstream effects of an incomplete bibliography.

**Comment by gsautter** [comment]
For the "Greef" citation (misspelled more often than spelled correctly as "Greeff", with the latter being in the bibliography), the fix described in #893 works like a charm ... after manually assigning the cited reference in "Tools > Mark Bibliographic Citations", the treatment citation marker script does the trick in the XML view.
