### ISSUE TITLE
font issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#9]
FIŠER is not properly detected

![image](https://cloud.githubusercontent.com/assets/4609956/20917697/51530f7e-bb93-11e6-89af-f3285992d243.png)
[Alther_et_al_2016.pdf](https://github.com/gsautter/goldengate-imagine/files/633235/Alther_et_al_2016.pdf)

Is there a way to fix this with "edit fonts"?

**Comment by myrmoteras** [comment]
same document: 
![image](https://cloud.githubusercontent.com/assets/4609956/20917780/bc9a367c-bb93-11e6-968d-4ee8dcda22ca.png)


the titles are all in two words

**Comment by gsautter** [comment]
This one has pretty nasty fonts in terms of the diacritics. They come as base character ("S" in this case) and a combining (standalone) inverse circumflex (called a "breve"), which is however encoded as a "€" sign. It then renders the character "S", repositions, and renders the breve on top of it. Little we can do here, as the combination does not have a Unicode point as a single character (afaik).

The best we can do here is take out the breve (via marking it as an artifact) and live with a plain "S", I'm afraid.

**Comment by gsautter** [comment]
Regarding the small-caps in "Molecular", simply mark across the "M" and the "olecular" (with text streams showing) and use "Join Words", then they'll show up as one word in the XML.
