### ISSUE TITLE
Problem with header as label

### ISSUE THREAD

**Issue by truschel** [gsautter/goldengate-imagine#904]
Hi Guido

I am working on template for the Acta Entomologica MuseI Pragae and I'm having problems with the header of the first page.  This header contains the informations of Document Metadata as DOI, issue, volume... However GGI identify this header as label and consequently the Document Metadata doesn't work.
We tried change the page content area for exclude: the figure next to the name of journal, to exclude the two figures in the end of first page, and later for exclude the part below the line (considering information of ISSN to below). The problem with it is that the exclusion of the part below the line will affect the others pages.
We also tested mark two headers areas in the Layout of First Page: one for the header of first page and the other for the the two figures in the end of first page. None works.

What do you think about it? What can we do for solve the problem?

Template: https://drive.google.com/open?id=1igXPTRpq1-BnyZbjfQuycXAzvW9q5hrS
PDF of paper: https://drive.google.com/open?id=1sH2VD5frC7q_mtIuePAb4uhpINWD0yqE
IMF of paper: https://drive.google.com/open?id=123WSP6NP8PrQDHELmtWZONuygHrOWInb

**Comment by gsautter** [comment]
What do you mean "nothing works"? I just modeled the DOI, and the only thing not working is the visualization highlights for the regular expression patterns ... both the overall "Test" button for the DOI extraction parameter group and the actual extraction by the metadata gizmo work just fine ... as do the "Test" buttons for the context and value patterns, by the way.
![image](https://user-images.githubusercontent.com/5789714/74587873-32252400-4ff8-11ea-8526-fa1d4cc657ee.png)
![image](https://user-images.githubusercontent.com/5789714/74587878-40734000-4ff8-11ea-90c1-6862ca3de463.png)
![image](https://user-images.githubusercontent.com/5789714/74587885-4a953e80-4ff8-11ea-9769-ec54ffac410d.png)

**Comment by gsautter** [comment]
Ultimately, graphics labels are text streams just like any other (the only exception to the "like any other" are ones of type "artifact", which are chopped up into the individual words), so the graphics at the top of the first page is not really a problem. The DOI extracts just fine, as should volume and issue number and pagination, which are right above the it.

**Comment by truschel** [comment]
Thank you Guido! Indeed it works!
