### ISSUE TITLE
"Allow Connecting to CN" message upon opening GGI

### ISSUE THREAD

**Issue by flsimoes** [gsautter/goldengate-imagine#907]
Just wanted report, as I'm not sure how relevant this is, that when we opened GGI (both through batch processing and through opening the software manually) today, this new dialog appeared:

![InkedBatchUpload Message_LI](https://user-images.githubusercontent.com/3343086/74940068-ae8c7e00-53cf-11ea-8b69-2c35131a7c0f.jpg)

**Comment by gsautter** [comment]
All this means is that the SSL certificate (also used for HTTPS) of the Plazi server in Frankfurt changed, which it does about every month, and thus you need to accept the new certificate.
This will come up in whichever GGI application or command line tool encounters the new certificate first, as the key store holding the trusted certificates is shared between all of them. No worries, just hit "Yes" and continue.
