### ISSUE TITLE
Zootaxa 4687.1.1 - "Table"/List assignment

### ISSUE THREAD

**Issue by flsimoes** [gsautter/goldengate-imagine#909]
I can't mark up this "table" because it is actually a list. Should I just leave it as text?

UUID: 9004D164513B1856FF99FF9FEF381C47

<img width="434" alt="Zootaxa" src="https://user-images.githubusercontent.com/3343086/75566818-25102800-5a2f-11ea-92bf-92e46d8c552f.PNG">

**Comment by gsautter** [comment]
If it's mixed up with the main text, just use "Mark Parenthesis", which is normally intended for text boxes ... in a sense, such a table even is exactly that ... as is any table, only with the added feature of a column structure.

**Comment by flsimoes** [comment]
Thanks Guido!
