### ISSUE TITLE
Can't link figureCitation to caption

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#91]
in this article, the option does not exist, to link the figureCitation to the caption. Any help?

http://tb.plazi.org/GgServer/summary/FFA3FFE35F4BFFC1167EC114FFE3FF8D

**Comment by gsautter** [comment]
Provided it's the same document as in #89 and #90 , simply merge the words ... that prevents spaces from happening into the wrong places, thus throwing off any pattern matching and lookups.

This is, as a lot of the things listed in #90 , a downstream problem of the root problem discussed in #89 .

**Comment by myrmoteras** [comment]
I merged them already, it does not work either

**Comment by myrmoteras** [comment]
You might have to look into this. I can't fix it. I give up.

**Comment by gsautter** [comment]
I just tried removing and re-annotation the figure citations, and it all worked just fine. Updated on the server.
