### ISSUE TITLE
Zoosystema 42(2) - PDF won't open

### ISSUE THREAD

**Issue by flsimoes** [gsautter/goldengate-imagine#910]
Hi Guido,

I've been trying to open this PDF [42(2)](https://drive.google.com/open?id=1P19Ds10ssrN3uHQRETXbrl95Dsr3Z9rA) from Zoosystema, but somehow I can't seem to make it work.

Just so you know, I made several tests before creating this issue:
- Tried to open it with and without a template
- Restarted both GGI and the computer
- Tried opening the PDF in other computers
- Re-downloaded the PDF

None of these worked. However, I did manage to open it resorting to an unorthodox method. I added blank pages to the start of the PDF, as you can see [HERE](https://drive.google.com/open?id=17NjhEthbNHYGLTdCaFW9cRHzNIHxRkcG) (or you can check the [IMF](https://drive.google.com/open?id=1U8DexFMDozXRzwbPFKrQ93MUKiHt_Hdx)).

Any clues to what might be happening?

**Comment by gsautter** [comment]
Got it ... quest for style anchor matches was trying to seek beyond the number of pages available ... therefor increasing the number of pages by adding a few blank ones helped you circumvent the problem ... fix is implemented, comes with next update.

**Comment by flsimoes** [comment]
Awesome! Thanks Guido!
