### ISSUE TITLE
materials citation not marked up zootaxa 70344B2DC016D123332BFFBEFFF69B51

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#911]
![image](https://user-images.githubusercontent.com/4609956/76069030-89346e00-5f92-11ea-9276-f6d623dd3cfa.png)

page 22 

![image](https://user-images.githubusercontent.com/4609956/76070275-88044080-5f94-11ea-9010-81f6382cbcef.png)

**Comment by myrmoteras** [comment]
not completely marked up

![image](https://user-images.githubusercontent.com/4609956/76069164-bbde6680-5f92-11ea-97a1-04387b496a56.png)

**Comment by myrmoteras** [comment]
Wales vs New South Wales tagging

![image](https://user-images.githubusercontent.com/4609956/76069556-58086d80-5f93-11ea-81f1-8a3d005f4274.png)

**Comment by myrmoteras** [comment]
island wrong

![image](https://user-images.githubusercontent.com/4609956/76069845-cd743e00-5f93-11ea-881b-634d5dd89cd2.png)

**Comment by gsautter** [comment]
Now this is an interesting case ... the actual country (Australia) is not mentioned at all, leaving the country/region tagger without any hints at all which list of regions (accessed by country) to use.

I'm coming to think about adding some more context aware "human" style logic, in that the presence of many regions from the same country will imply the country proper ... just like a human knowing federal states will implicitly understand the country ... to be taken care of, thanks for this test case.

**Comment by gsautter** [comment]
Fixed ... the tagger now compiles an index of troublesome country names on initialization, mapping them to regions from other countries they occur in ... this fixes the "Wales" issue, and also any "Scotland" issues incurred by "Nova Scotia".
Further, the tagger now checks if some conflicting country name occurs as a region, using other regions from the same state as evidence, which fixes the "Georgia" issue even in absence of emphases if at least two other US states are mentioned.
Finally, the tagger indexes troublesome country names like "Island" and filters them out if they exclusively occur as suffixes to larger proper names. This also helps with "Salvador" and several others.

Comes with next update.
