### ISSUE TITLE
Blocks that can't be split contributionsToEntomology.69.2.301-317

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#915]
FFE2FFAF6E15390AFFF3FFA0FFE1FFFE

This is an odd article which I can't fix. For example these blocks, or then it had almost all the pages with figures originally marked up as entire figures.
Why are there many regions over each other on some pages?
![image](https://user-images.githubusercontent.com/4609956/76868948-e6200600-6867-11ea-934b-0ea0ee372995.png)

**Comment by gsautter** [comment]
You cannot split what's split already ... the blocks and paragraphs are correct, only the text stream is messed up.

Using "Make Stream" to cut off the right column and then repairing the test streams via "Make Successor" does the trick in such situations.

How this got into this weird state is a different question altogether ... my money is on an accidental "Order Stream" across the whole of the two columns.
