### ISSUE TITLE
Figure extraction failed: only have of the figure extracted

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#92]
from this pdf, some figures got only partially extracted
https://doi.org/10.5281/zenodo.321913 
http://tb.plazi.org/GgServer/summary/4137C632FFBBFFA4FFDDCE50FF83FFD3
docId="BD0EBE4AFFBAFFA7FC9DCFC4FC5EF913"

![image](https://cloud.githubusercontent.com/assets/4609956/23279943/86f3a9f0-fa17-11e6-9ee1-7120c6e4b76e.png)

and here the original
![image](https://cloud.githubusercontent.com/assets/4609956/23279960/97238bb0-fa17-11e6-8897-4eaf16531973.png)

**Comment by gsautter** [comment]
This problem appears to only exist in the page image ... if you use "Copy Image" (which puts the backing figure supplement PNG in your system clipboard) and paste it to, say, Paint, you get the full image.

**Comment by gsautter** [comment]
Got it ... he lower half of the image appears to be over-painted by a white rectangle ... for _whatever_ reason ... will check.

**Comment by gsautter** [comment]
Got it ... this image is rendered in 4 parts, each one with a white background. And as as the images are (correctly) assembled into one by the decoder, rendering order apparently gets mixed up a bit. Will try and fix it.

**Comment by gsautter** [comment]
Done ... moved tiled image merge-up after sorting out background graphics now, so figure does not get painted over any more.

**Comment by gsautter** [comment]
Online update is out including the fix for this weirdo problem.
