### ISSUE TITLE
Problem to open an UUID and change the DOI

### ISSUE THREAD

**Issue by truschel** [gsautter/goldengate-imagine#923]
Hi Guido

I'm have problem to open an UUID from Zootaxa paper. When I try to open the UUID, the GGI show this message: 
![image](https://user-images.githubusercontent.com/57402704/136215186-024994b2-7f0c-454d-96dd-31f3a0c59e9f.png)
I need to open this UUID to change the DOI. 

UUID: 03F887C99B23FF8DE228FBCFFE2AC22D
Correct DOI: 10.11646/zootaxa.436.1.1

The DOI **10.11646/zootaxa.472.1.1** is from another Zootaxa paper which is in the gatekeeper. 
UUID: FFFDF20B615497040914FF84394DE931

**Comment by gsautter** [comment]
No worries, it happens.
