### ISSUE TITLE
Two Adansonia IMF's with errors in gatekeeper 

### ISSUE THREAD

**Issue by truschel** [gsautter/goldengate-imagine#924]
Hi Guido

I'm with two IMF's of Adansonia with errors in the gatekeeper I am not able to solve.
Please, could you check them for me?
The errors of missing taxonomicNames are relative to reference groups. I removed them but they are still in gatekeeper. The other errors I couldn't find on the IMF's.
UUID's:
FFF9E30FFFCF347CFFB42A1FFF8FFFD5
FF9A13618405FF98FFB69008587E3E08

Thanks!
Tatiana

**Comment by gsautter** [comment]
Resolved ... seems to have been the same gatekeeper cache glitch that I cleaned up for a series of documents last weekend.
