### ISSUE TITLE
PDF conversion failed: BMC Zoology. PDF/A issue?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#93]
This PDF did not convert.

[10.1186s40850-017-0013-2.pdf](https://github.com/gsautter/goldengate-imagine/files/798600/10.1186s40850-017-0013-2.pdf)
 
[Logs.zip](https://github.com/gsautter/goldengate-imagine/files/798610/Logs.zip)

**Comment by myrmoteras** [comment]
The hack is to OCR the doc in ABBYY, create a new PDF and it runs

http://treatment.plazi.org/id/03D2A051-2862-FFC8-3C7C-DEA40E4BF69F

The problem then is that you start to insert OCR errors - see eg the legends. That means, it needs a lot of care to get it right.

Better would be to get it done firsthand....

**Comment by gsautter** [comment]
I could reproduce the error ... looks like some issue in the PostScript interpreter that is used in decoding Type 1 fonts. Will try and see how to fix this.

**Comment by gsautter** [comment]
Found the problem ... it's merely "(2017) 2:4" ... or more specifically the font this little piece is rendered in. It's a (rare) Type 1 font that uses PostScript commands and features I'd thus far had no example for. Implemented that now, and it works, even though I have to say what this font does is really weird ...

An online update with the respective PDF decoder fix is out.
