### ISSUE TITLE
how to fix OCR errors from Tesseract

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#94]
How can I fix the OCR errors in this doc  docId="03D2A0512862FFC83C7CDEA40E4BF69F"
A figure legend has not been OCRed and I did it within GGI. the results is not too good, but I don't know how to fix it.

![image](https://cloud.githubusercontent.com/assets/4609956/23299515/1e1df3e8-fa82-11e6-8bca-582184854b08.png)

http://tb.plazi.org/GgServer/html/03D2A0512862FFC83C7CDEA40E4BF69F?cacheControl=force

**Comment by gsautter** [comment]
Why did you end up scanning a 2017 document? Anyway, "Merge Words" or "Join Words" both do the trick in cases where the full word is there. Looking at the caption of Figure 2, however, I find quite a few characters missing altogether.

Do you still have the born-digital original? If so, I'd like to give it a shot with the latest font fixes ... and then, I think I already _have_ solved the issue with loading this one in its born-digital original ... see #93 ... shaking head in disbelief ...

**Comment by myrmoteras** [comment]
@gsautter the source file is here http://bmczool.biomedcentral.com/articles/10.1186/s40850-017-0013-2

GGI would not open this file, so wonder, whether there is a hack around it.
