### ISSUE TITLE
GGI: image decoding error

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#95]
these images from EJT have a problem
https://zenodo.org/record/322371/files/figure.png 
![image](https://cloud.githubusercontent.com/assets/4609956/23307452/e8474302-faa7-11e6-9d3b-637d4b6c8284.png)

https://zenodo.org/record/322376/files/figure.png
![image](https://cloud.githubusercontent.com/assets/4609956/23307474/fd3cfd38-faa7-11e6-971d-439ab3e24b47.png)

they are from docId="CF0187C5A364FFB26B6AD673FE2CFB81" 
http://www.europeanjournaloftaxonomy.eu/index.php/ejt/article/view/352

http://treatment.plazi.org/GgServer/summary/3338FFBDA367FFBA6917D778FFAFFFA2

**Comment by myrmoteras** [comment]
@gs there are more problem with the decoding
![image](https://cloud.githubusercontent.com/assets/4609956/23331174/fedc78f8-fb60-11e6-9d40-b6968266366f.png)

https://zenodo.org/record/322413#.WLF8oJorLAQ

http://treatment.plazi.org/id/C93D87F0FFF9FF9C8ED0FA3DFD43FC81

**Comment by gsautter** [comment]
Not sure how that happened ... I cannot seem to reproduce this, the figures come up just right. Could this be one of the EJTs you decoded with an earlier version of GGI due to the other error in #86 and #88 ?
