### ISSUE TITLE
bug: GGI stalls when pausing loading document dialog

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#97]
when the "loading document from GoldenGate server" dialog is open and then paused, it cannot be resumed or abandoned, it stops GGI working, and GGI has to be killed using the task manager

![image](https://cloud.githubusercontent.com/assets/4609956/23339208/bd8d99f0-fc1d-11e6-8749-3f50a163d606.png)

**Comment by gsautter** [comment]
Reproduced ...

**Comment by gsautter** [comment]
... and fixed, update to be out soon.
