### ISSUE TITLE
annotation element captionTargetID: what is?

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#98]
@gsautter 
I found captionTargetID here. 
![image](https://cloud.githubusercontent.com/assets/4609956/23397697/e78410c2-fd99-11e6-8a37-cf2b6382ee93.png)

It is not the value given in the image attribute, which is needed
![image](https://cloud.githubusercontent.com/assets/4609956/23398088/858d073c-fd9b-11e6-93fd-74fd5167fd16.png)

but in the supplments.csv it is listed

`figure@5.[152,1435,167,1609]","figure","image/png","box<[152,1435,167,1609]>dpi<320>mimeType<image/png>pageId<5>ron<189>type<figure>`

It also seems not be necessary to create a figureCitation?! Why are the two values for the image different?

the source is  http://tb.plazi.org/GgServer/summary/F513FF8FFFC6FE045149A21E8B60FFB0

**Comment by gsautter** [comment]
The `captionTargetId` attribute corresponds to the ID of the document supplement that holds the original PNG image representing the figure. If it is present and matches an available supplement ID, that is what's used. If not, fuzzy matching kicks in as described in #99.

**Comment by gsautter** [comment]
The answer to your question about the discrepancy in the bounding boxes is that the figure most likely has white margins that were not included in the `image` region marking it in the document page.

That exclusion of margins is crucial in page blocking, as in the latter (as for your very eyes) what counts is the amount of whitespace separating non-white document content, independent of what ended up painting that whitespace. That pretty much emulates copy editing, which is all about what a page finally _looks_ like to a pair of human eyeballs, I guess.
